Repository spinnaker/deck, pull requests merged in 2019-10, with the labels that each got.

#7453 refactor(pipeline): Reactify the copy stage modal
  app/scripts/modules/core/src/pipeline/config/copyStage/CopyStageCard.tsx
  app/scripts/modules/core/src/pipeline/config/copyStage/CopyStageModal.tsx
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStage.modal.controller.ts
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStage.modal.html
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStage.modal.less
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStageCard.component.ts
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStageCard.less
  app/scripts/modules/core/src/pipeline/config/copyStage/copyStageModal.less
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
  app/scripts/modules/core/src/pipeline/pipeline.module.ts
Labels: angular2react

#7501 refactor(application): reactify delete application section
  app/scripts/modules/core/src/application/config/DeleteApplicationSection.tsx
  app/scripts/modules/core/src/application/config/applicationConfig.controller.js
  app/scripts/modules/core/src/application/config/deleteApplicationSection.directive.html
  app/scripts/modules/core/src/application/config/deleteApplicationSection.directive.js
  app/scripts/modules/core/src/application/config/deleteApplicationSection.module.ts
  app/scripts/modules/core/src/securityGroup/label/FirewallLabel.tsx
  app/scripts/modules/core/src/securityGroup/label/index.ts
Labels: angular2react

#7546 chore(github): Add mergify config
  .mergify.yml
Labels: ready to merge

#7531 feat(core/jenkins): Refer to Jenkins controller instead of master
  app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsExecutionDetails.html
  app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.html
  app/scripts/modules/core/src/pipeline/config/stages/travis/travisExecutionDetails.html
  app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.html
  app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.html
  app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.html
  app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTrigger.tsx
Labels: ready to merge

#7549 feat(core): alphabetize applications in project config dropdown
  app/scripts/modules/core/src/projects/ProjectHeader.tsx
Labels: ready to merge

#7548 chore(core/presentation): update icon font for managed delivery
  app/fonts/spinnaker/fonts/icomoon.svg
  app/fonts/spinnaker/fonts/icomoon.ttf
  app/fonts/spinnaker/fonts/icomoon.woff
  app/fonts/spinnaker/fonts/icomoon.woff2
  app/fonts/spinnaker/icons.css
  app/fonts/spinnaker/selection.json
Labels: ready to merge

#7542 feat(provider/aws): Show load balancer warning based on settings
  app/scripts/modules/amazon/src/aws.settings.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
  app/scripts/modules/amazon/src/loadBalancer/configure/LoadBalancerTypes.ts
Labels: ready to merge

#7541 fix: credentails typo
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
Labels: ready to merge

#7551 Bump package core to 0.0.425 and amazon to 0.0.218
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
Labels: ready to merge

#7553 chore(settings): Remove unused feature toggle: 'jobs'
  app/scripts/modules/core/src/config/settings.ts
  halconfig/settings.js
  settings.js
Labels: auto merged, ready to merge

#7544 feat(provider/aws): Add capabilities in cloudformation deploy stage
  app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackConfig.html
Labels: auto merged, ready to merge

#7554 chore(titus): remove unused autoScalingEnabled toggle from settings interface
  app/scripts/modules/titus/src/titus.settings.ts
Labels: ready to merge

#7555 fix(core/instance): use fragment on non-UP health code path
  app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx
Labels: ready to merge

#7556 fix(config): Fix typings for SpinnakerSettings
  app/scripts/modules/amazon/src/aws.settings.ts
  app/scripts/modules/core/src/config/settings.ts
Labels: ready to merge

#7557 chore(core/notification): remove remainder of hipchat notifications
  app/scripts/modules/core/src/notification/selector/types/hipchat/HipchatNotificationType.tsx
  app/scripts/modules/core/src/notification/selector/types/hipchat/hipchat.notification.ts
  app/scripts/modules/core/src/notification/selector/types/index.ts
Labels: auto merged, ready to merge

#7563 fix(core/pipeline): make UX less bad when a pipeline stage never happened
  app/scripts/modules/core/src/pipeline/config/stages/pipeline/PipelineStageExecutionDetails.tsx
Labels: auto merged, ready to merge

#7536 feat(provider/aws): Functions (listing and searching)
  app/scripts/modules/amazon/src/aws.module.ts
  app/scripts/modules/amazon/src/domain/IAmazonFunction.ts
  app/scripts/modules/amazon/src/domain/index.ts
  app/scripts/modules/amazon/src/function/function.module.ts
  app/scripts/modules/amazon/src/function/function.transformer.ts
  app/scripts/modules/amazon/src/function/index.ts
  app/scripts/modules/amazon/src/index.ts
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/domain/IFunction.ts
  app/scripts/modules/core/src/domain/index.ts
  app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
  app/scripts/modules/core/src/function/Function.tsx
  app/scripts/modules/core/src/function/FunctionDetails.tsx
  app/scripts/modules/core/src/function/FunctionGroupings.tsx
  app/scripts/modules/core/src/function/FunctionPod.tsx
  app/scripts/modules/core/src/function/Functions.tsx
  app/scripts/modules/core/src/function/filter/FunctionFilterModel.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.spec.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.ts
  app/scripts/modules/core/src/function/filter/FunctionFilters.tsx
  app/scripts/modules/core/src/function/function.dataSource.ts
  app/scripts/modules/core/src/function/function.module.ts
  app/scripts/modules/core/src/function/function.read.service.ts
  app/scripts/modules/core/src/function/function.states.ts
  app/scripts/modules/core/src/function/function.transformer.js
  app/scripts/modules/core/src/function/functionPod.less
  app/scripts/modules/core/src/function/index.ts
  app/scripts/modules/core/src/index.ts
  app/scripts/modules/core/src/state/index.ts
Labels: auto merged, ready to merge

#7562 fix(kubernetes): disable project cluster filtration by stack/detail
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/projects/configure/Clusters.tsx
Labels: ready to merge

#7567 Revert "feat(provider/aws): Functions (listing and searching)"
  app/scripts/modules/amazon/src/aws.module.ts
  app/scripts/modules/amazon/src/domain/IAmazonFunction.ts
  app/scripts/modules/amazon/src/domain/index.ts
  app/scripts/modules/amazon/src/function/function.module.ts
  app/scripts/modules/amazon/src/function/function.transformer.ts
  app/scripts/modules/amazon/src/function/index.ts
  app/scripts/modules/amazon/src/index.ts
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/domain/IFunction.ts
  app/scripts/modules/core/src/domain/index.ts
  app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
  app/scripts/modules/core/src/function/Function.tsx
  app/scripts/modules/core/src/function/FunctionDetails.tsx
  app/scripts/modules/core/src/function/FunctionGroupings.tsx
  app/scripts/modules/core/src/function/FunctionPod.tsx
  app/scripts/modules/core/src/function/Functions.tsx
  app/scripts/modules/core/src/function/filter/FunctionFilterModel.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.spec.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.ts
  app/scripts/modules/core/src/function/filter/FunctionFilters.tsx
  app/scripts/modules/core/src/function/function.dataSource.ts
  app/scripts/modules/core/src/function/function.module.ts
  app/scripts/modules/core/src/function/function.read.service.ts
  app/scripts/modules/core/src/function/function.states.ts
  app/scripts/modules/core/src/function/function.transformer.js
  app/scripts/modules/core/src/function/functionPod.less
  app/scripts/modules/core/src/function/index.ts
  app/scripts/modules/core/src/index.ts
  app/scripts/modules/core/src/state/index.ts
Labels: auto merged, ready to merge

#7568 feat(provider/aws): Functions (listing and searching)
  app/scripts/modules/amazon/src/aws.module.ts
  app/scripts/modules/amazon/src/domain/IAmazonFunction.ts
  app/scripts/modules/amazon/src/domain/index.ts
  app/scripts/modules/amazon/src/function/function.module.ts
  app/scripts/modules/amazon/src/function/function.transformer.ts
  app/scripts/modules/amazon/src/function/index.ts
  app/scripts/modules/amazon/src/index.ts
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/domain/IFunction.ts
  app/scripts/modules/core/src/domain/index.ts
  app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
  app/scripts/modules/core/src/function/Function.tsx
  app/scripts/modules/core/src/function/FunctionDetails.tsx
  app/scripts/modules/core/src/function/FunctionGroupings.tsx
  app/scripts/modules/core/src/function/FunctionPod.tsx
  app/scripts/modules/core/src/function/Functions.tsx
  app/scripts/modules/core/src/function/filter/FunctionFilterModel.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.spec.ts
  app/scripts/modules/core/src/function/filter/FunctionFilterService.ts
  app/scripts/modules/core/src/function/filter/FunctionFilters.tsx
  app/scripts/modules/core/src/function/function.dataSource.ts
  app/scripts/modules/core/src/function/function.module.ts
  app/scripts/modules/core/src/function/function.read.service.ts
  app/scripts/modules/core/src/function/function.states.ts
  app/scripts/modules/core/src/function/function.transformer.js
  app/scripts/modules/core/src/function/functionPod.less
  app/scripts/modules/core/src/function/index.ts
  app/scripts/modules/core/src/index.ts
  app/scripts/modules/core/src/state/index.ts
  settings.js
Labels: auto merged, ready to merge

#7564 feat(rosco): Allow roscoMode per stage/execution
  app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
  app/scripts/modules/amazon/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
  app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
  app/scripts/modules/azure/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
  app/scripts/modules/google/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
  app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
Labels: auto merged, ready to merge

#7571 fix(core/pipeline): fully re-render list of trigger configs after a delete
  app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
Labels: ready to merge

#7572 feat(git/repo): add git/repo artifact support in kustomize bake manifest
  app/scripts/modules/core/src/artifact/ArtifactIconService.ts
  app/scripts/modules/core/src/artifact/ArtifactTypes.ts
  app/scripts/modules/core/src/artifact/icons/git-repo-artifact.svg
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/kustomize/BakeKustomizeConfigForm.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitrepo/GitRepoArtifactEditor.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/index.ts
Labels: ready to merge

#7579 fix(runJob): fix artifact output creation
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
Labels: ready to merge

#7574 feat(kubernetes): permit multiple ReplicaSets to be deployed with a s…
  app/scripts/modules/kubernetes/src/shared/help/kubernetes.help.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifest.validator.ts
Labels: auto merged, ready to merge

#7570 feat(google): add gce scale-down controls
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.html
  app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.js
  app/scripts/modules/google/src/gce.module.ts
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.js
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceAutoScalingFieldLayout.tsx
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceScaleDownControls.tsx
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/gceScaleDownControls.less
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/upsertAutoscalingPolicy.modal.controller.js
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/upsertAutoscalingPolicy.modal.html
  halconfig/settings.js
  settings.js
Labels: auto merged, ready to merge

#7576 fix(core): Ensure default port used for target group healthcheck link
  app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
  app/scripts/modules/amazon/src/instance/details/utils.ts
Labels: ready to merge

#7336 fix(helptext): clarify text for stage timeout
  app/scripts/modules/core/src/help/help.contents.ts
Labels: auto merged, ready to merge

#7583 fix(rerun): Hiding re-run as strategies should not be re-run
  app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
Labels: auto merged, ready to merge
