Repository spinnaker/deck, pull requests merged in 2020-10, with the labels that each got.

#8609 feat(core/presentation): add useInterval hook
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/useInterval.hook.spec.tsx
  app/scripts/modules/core/src/presentation/hooks/useInterval.hook.ts
Labels: ready to merge

#8603 feat(ecs): Enable embedded artifacts for Deploy stage
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
Labels: ready to merge

#8608 feat(webhooks): document stausJsonPath is now optional
  app/scripts/modules/core/src/help/help.contents.ts
Labels: ready to merge

#8611 feat(core/managed): show failed, pending bubbles for any constraint type
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/ColumnHeader.less
Labels: ready to merge

#8610 feat(core/managed): switch to abbreviated timestamp format, add version timestamps
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
  app/scripts/modules/core/src/managed/StatusCard.tsx
  app/scripts/modules/core/src/managed/VersionStateCard.tsx
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
  app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx
Labels: ready to merge

#8612 chore(package): appengine@0.0.19 core@0.0.514 ecs@0.0.265 titus@0.0.145
  app/scripts/modules/appengine/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8588 fix(Oracle): Fixed Oracle object storage selection
  app/scripts/modules/core/src/artifact/ArtifactIconService.ts
  app/scripts/modules/core/src/artifact/ArtifactTypes.ts
  app/scripts/modules/core/src/artifact/icons/oracle-object-artifact.svg
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/index.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/oracle/OracleArtifactEditor.tsx
Labels: ready to merge

#8613 fix(cf): naming typo in EnvironmentVariables
  app/scripts/modules/cloudfoundry/src/cf.module.ts
  app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/EnvironmentVariablesSection.tsx
  app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/index.ts
Labels: ready to merge

#8615 fix(titus): Do not check for autoscaling feature flag, always enable …
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
Labels: ready to merge

#8616 chore(package): cloudfoundry@0.0.100 core@0.0.515 titus@0.0.146
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8617 chore(webpack): webpack/webpack-dev-server to fix excessive cpu use
  package.json
  yarn.lock
Labels: ready to merge

#8586 fix(appname): encodeURIComponent for app name
  app/scripts/modules/amazon/src/image/image.reader.ts
  app/scripts/modules/azure/src/image/image.reader.js
  app/scripts/modules/cloudfoundry/src/image/image.reader.cf.ts
  app/scripts/modules/core/src/api/ApiService.spec.ts
  app/scripts/modules/core/src/api/ApiService.ts
  app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
  app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
  app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
  app/scripts/modules/core/src/pipeline/service/execution.service.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  app/scripts/modules/core/src/slack/SlackReader.spec.ts
  app/scripts/modules/core/src/slack/SlackReader.ts
  app/scripts/modules/dcos/image/image.reader.js
  app/scripts/modules/docker/src/image/DockerImageReader.ts
  app/scripts/modules/google/src/image/image.reader.ts
  app/scripts/modules/oracle/src/image/image.reader.js
  app/scripts/modules/tencentcloud/src/image/image.reader.ts
Labels: ready to merge

#8621 fix(core/pipeline): Always enable "show revision history" in edit pipeline dialog
  app/scripts/modules/core/src/pipeline/config/actions/PipelineConfigActions.tsx
  app/scripts/modules/core/src/pipeline/config/actions/history/ShowPipelineHistoryModal.tsx
  app/scripts/modules/core/src/pipeline/config/actions/pipelineConfigActions.module.ts
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
Labels: ready to merge

#8624 chore(package): amazon@0.0.269 azure@0.0.255 cloudfoundry@0.0.101 core@0.0.516 docker@0.0.60 google@0.0.21 oracle@0.0.9 tencentcloud@0.0.6
  app/scripts/modules/amazon/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
Labels: ready to merge

#8627 Revert "fix(appname): encodeURIComponent for app name (#8586)"
  app/scripts/modules/amazon/src/image/image.reader.ts
  app/scripts/modules/azure/src/image/image.reader.js
  app/scripts/modules/cloudfoundry/src/image/image.reader.cf.ts
  app/scripts/modules/core/src/api/ApiService.spec.ts
  app/scripts/modules/core/src/api/ApiService.ts
  app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
  app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
  app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
  app/scripts/modules/core/src/pipeline/service/execution.service.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  app/scripts/modules/core/src/slack/SlackReader.spec.ts
  app/scripts/modules/core/src/slack/SlackReader.ts
  app/scripts/modules/dcos/image/image.reader.js
  app/scripts/modules/docker/src/image/DockerImageReader.ts
  app/scripts/modules/google/src/image/image.reader.ts
  app/scripts/modules/oracle/src/image/image.reader.js
  app/scripts/modules/tencentcloud/src/image/image.reader.ts
Labels: ready to merge

#8630 chore(package): amazon@0.0.270 azure@0.0.256 cloudfoundry@0.0.102 core@0.0.517 docker@0.0.61 google@0.0.22 oracle@0.0.10 tencentcloud@0.0.7
  app/scripts/modules/amazon/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
Labels: ready to merge

#8628 feat(eslint-plugin): Add a README.md with instructions on creating eslint rules
  packages/eslint-plugin/README.md
Labels: ready to merge

#8631 chore(eslint): eslint --fix api-no-slashes
  app/scripts/modules/amazon/src/image/image.reader.ts
  app/scripts/modules/azure/src/image/image.reader.js
  app/scripts/modules/cloudfoundry/src/image/image.reader.cf.ts
  app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
  app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  app/scripts/modules/core/src/slack/SlackReader.spec.ts
  app/scripts/modules/core/src/slack/SlackReader.ts
  app/scripts/modules/dcos/image/image.reader.js
  app/scripts/modules/docker/src/image/DockerImageReader.ts
  app/scripts/modules/google/src/image/image.reader.ts
  app/scripts/modules/oracle/src/image/image.reader.js
  app/scripts/modules/tencentcloud/src/image/image.reader.ts
Labels: ready to merge

#8633 feat(gce): remove the deprecated ONLY_UP autoscaling mode
  app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.js
  app/scripts/modules/google/src/help/gce.help.ts
Labels: ready to merge

#8629 feat(eslint-plugin): Add a new rule api-no-slashes that forbids using string literals with slashes to API.one()
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/rules/api-no-slashes.js
  packages/eslint-plugin/test/api-no-slashes.spec.js
  packages/eslint-plugin/yarn.lock
Labels: ready to merge

#8596 feat(titus): Add monitored deploy strategy support to titus
  app/scripts/modules/titus/src/titus.module.ts
Labels: ready to merge

#8640 Package bump amazon 0.0.271 azure 0.0.257 cloudfoundry 0.0.103 core 0.0.518 docker 0.0.62 google 0.0.23 oracle 0.0.11 tencentcloud 0.0.8 titus 0.0.147
  app/scripts/modules/amazon/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8639 feat(core/application): sort Environments first for users with it enabled
  app/scripts/modules/core/src/application/service/ApplicationDataSourceRegistry.ts
Labels: ready to merge

#8634 feat(keel): set defaults for managed delivery config
  app/scripts/modules/core/src/config/settings.ts
Labels: ready to merge

#8632 feat(ecs): add cypress tests for the ecs provider
  app/scripts/modules/core/src/artifact/react/StageArtifactSelector.tsx
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
  app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/location/basicSettings.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/logging/logging.component.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/networking/networkingSelector.component.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/serverGroupWizard.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/taskDefinition.html
  test/functional/cypress/fixtures/default/credentials.expand.json
  test/functional/cypress/fixtures/ecs/clusters/clusters.json
  test/functional/cypress/fixtures/ecs/clusters/loadbalancers.json
  test/functional/cypress/fixtures/ecs/shared/artifacts.json
  test/functional/cypress/fixtures/ecs/shared/ecsClusters.json
  test/functional/cypress/fixtures/ecs/shared/images.json
  test/functional/cypress/fixtures/ecs/shared/lb.json
  test/functional/cypress/fixtures/ecs/shared/roles.json
  test/functional/cypress/fixtures/ecs/shared/serviceDiscoveryRegistries.json
  test/functional/cypress/fixtures/ecs/shared/subnets.json
  test/functional/cypress/integration/ecs/clusters_list.spec.js
  test/functional/cypress/integration/ecs/pipelines.spec.js
  test/functional/cypress/integration/ecs/server_group.spec.js
  test/functional/cypress/support/defaultFixtures.js
Labels: ready to merge

#8636 feat(pluginsdk): Add cli flags to scaffold.js to allow non-interactive scaffolding
  packages/pluginsdk/scripts/scaffold.js
  packages/pluginsdk/scripts/write-json.js
Labels: ready to merge

#8635 fix(pluginsdk): Remove package.json 'module' lint rule from check-plugin
  packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
Labels: ready to merge

#8637 feat(pluginsdk-peerdeps): Create a separate package for managing peer dependencies for plugins
  packages/pluginsdk-peerdeps/.gitignore
  packages/pluginsdk-peerdeps/README.md
  packages/pluginsdk-peerdeps/USAGE.txt
  packages/pluginsdk-peerdeps/clean.sh
  packages/pluginsdk-peerdeps/package.json
  packages/pluginsdk-peerdeps/sync-deck.js
  packages/pluginsdk-peerdeps/sync-save.js
  packages/pluginsdk-peerdeps/sync-stage.sh
  packages/pluginsdk/package.json
  packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
  packages/pluginsdk/scripts/syncPeerDependencies.js
  packages/pluginsdk/yarn.lock
Labels: ready to merge

#8643 feat(core): make Environments the default route if enabled
  app/scripts/modules/core/src/application/application.state.provider.ts
  app/scripts/modules/core/src/application/applications.state.provider.ts
  app/scripts/modules/core/src/application/modal/createApplication.modal.controller.js
  app/scripts/modules/core/src/application/search/ApplicationsTable.tsx
  app/scripts/modules/core/src/application/service/ApplicationDataSourceRegistry.ts
  app/scripts/modules/core/src/insight/InsightMenu.tsx
  app/scripts/modules/core/src/navigation/UrlBuilder.ts
  app/scripts/modules/core/src/pagerDuty/Pager.tsx
  app/scripts/modules/core/src/projects/ProjectHeader.tsx
  app/scripts/modules/core/src/projects/projects.states.ts
  app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
  app/scripts/modules/core/src/serverGroup/serverGroup.states.ts
Labels: ready to merge

#8647 chore(package): amazon@0.0.272 appengine@0.0.20 azure@0.0.258 cloudfoundry@0.0.104 core@0.0.519 docker@0.0.63 ecs@0.0.266 google@0.0.24 huaweicloud@0.0.6 kubernetes@0.0.52 oracle@0.0.12 tencentcloud@0.0.9 titus@0.0.148
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8557 fix(aws): Support cross zone load balancing for NLB
  app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/network/NLBAdvancedSettings.tsx
  app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
  app/scripts/modules/core/src/help/help.contents.ts
Labels: ready to merge

#8650 chore(java11): use Java 11 to run Gradle
  Dockerfile.compile
Labels: ready to merge

#8651 chore(build): add git to Dockerfile.compile
  Dockerfile.compile
Labels: ready to merge

#8652 chore(build): change Dockerfile.compile base to openjdk:11-slim
  Dockerfile.compile
Labels: ready to merge

#8653 fix(core/managed): respect line breaks in commit messages
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
Labels: ready to merge, self merge

#8655 chore(package): amazon@0.0.273 core@0.0.520 oracle@0.0.13
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/oracle/package.json
Labels: ready to merge

#8649 fix(eslint-plugin): Cast a wider net in api-no-slashes.js
  packages/eslint-plugin/rules/api-no-slashes.js
  packages/eslint-plugin/test/api-no-slashes.spec.js
  packages/eslint-plugin/utils/utils.js
Labels: ready to merge

#8656 fix(core/managed): surface artifact reference on details pane
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
Labels: ready to merge, self merge

#8658 feat(core/pipeline): Rename "Source" link to "View as JSON"
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
  app/scripts/modules/core/src/task/tasks.html
Labels: ready to merge

#8659 chore(package): core@0.0.521
  app/scripts/modules/core/package.json
Labels: ready to merge

#8661 fix(halyard): Bugfix 6112: settings.js doesn't have Oracle default settings
  halconfig/settings.js
Labels: ready to merge

#8662 fix(kubernetes): remove unneeded application validation warning
  app/scripts/modules/kubernetes/src/validation/applicationName.validator.spec.ts
  app/scripts/modules/kubernetes/src/validation/applicationName.validator.ts
Labels: ready to merge

#8665 fix(deck): Bugfix 6112: provide default settings for oracle provider in deck microservice to remove Halyard dependency.
  app/scripts/modules/core/src/region/RegionSelectInput.tsx
  app/scripts/modules/oracle/src/loadBalancer/loadBalancer.transformer.ts
  app/scripts/modules/oracle/src/oracle.settings.ts
Labels: ready to merge

#8666 fix(core): Check if manifest event is null from k8s.
  app/scripts/modules/core/src/manifest/PodNameProvider.ts
Labels: ready to merge

#8668 chore(package): use node_modules/.bin/* in module scripts, add 'build' script (the old 'lib' script)
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge, self merge

#8671 chore(package): remove unused wdio and webdriver packages
  package.json
  yarn.lock
Labels: ready to merge, self merge

#8679 chore(modules): Reformat package.json with prettier
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge, self merge

#8680 chore(package): amazon@0.0.274 appengine@0.0.21 azure@0.0.259 cloudfoundry@0.0.105 core@0.0.522 docker@0.0.64 ecs@0.0.267 google@0.0.25 huaweicloud@0.0.7 kubernetes@0.0.53 oracle@0.0.14 tencentcloud@0.0.10 titus@0.0.149
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8683 fix(githubactions): switch approve_package_bumps to rebase
  .github/workflows/approve_package_bumps.yml
Labels: ready to merge, self merge

#8676 fix(eslint-plugin): Allow .split('/') in API.one() calls in api-no-slashes lint rule
  packages/eslint-plugin/rules/api-no-slashes.js
  packages/eslint-plugin/test/api-no-slashes.spec.js
Labels: ready to rebase

#8684 chore(eslint): pre-fix linter violations from upcoming eslint-plugin release
  app/scripts/modules/core/src/instance/details/instanceActions.component.ts
  app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
Labels: ready to merge, self merge

#8685 fix(packages): fix show_changelog.sh to work when a package bump is reverted
  app/scripts/modules/show_changelog.sh
Labels: ready to merge, self merge

#8681 feat(core/managed): add DIFF_NOT_ACTIONABLE resource status
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/managedResourceStatusConfig.tsx
Labels: ready to merge, self merge

#8673 feat(eslint-plugin): Add a new rule prefer-promise-like to help migrate off of ng.IPromise
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/rules/prefer-promise-like.js
  packages/eslint-plugin/test/prefer-promise-like.spec.js
Labels: ready to merge, self merge

#8660 refactor(storybook/forms): Rewrite stories for SpinFormik
  .storybook/main.js
  .storybook/preview.js
  app/scripts/modules/core/src/presentation/forms/SpinFormik.stories.mdx
  app/scripts/modules/core/src/presentation/forms/stories/FormikIntro.stories.mdx
  app/scripts/modules/core/src/presentation/forms/stories/SpinFormik.stories.tsx
  app/scripts/modules/core/src/presentation/forms/stories/SpinFormikStoriesHelper.tsx
  package.json
  yarn.lock
Labels: ready to merge

#8687 chore(promiselike): Migrate more code away from angularjs IPromise to PromiseLike
  app/scripts/modules/amazon/src/keyPairs/KeyPairsReader.ts
  app/scripts/modules/appengine/src/loadBalancer/transformer.ts
  app/scripts/modules/appengine/src/serverGroup/details/details.controller.ts
  app/scripts/modules/appengine/src/serverGroup/transformer.ts
  app/scripts/modules/cloudfoundry/src/loadBalancer/loadBalancer.transformer.ts
  app/scripts/modules/core/src/account/AccountTag.tsx
  app/scripts/modules/core/src/api/ApiService.ts
  app/scripts/modules/core/src/api/network.interceptor.ts
  app/scripts/modules/core/src/cancelModal/CancelModal.tsx
  app/scripts/modules/core/src/ci/igor.service.ts
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.ts
  app/scripts/modules/core/src/image/image.reader.ts
  app/scripts/modules/core/src/loadBalancer/loadBalancerDataUtils.ts
  app/scripts/modules/core/src/manifest/ManifestReader.ts
  app/scripts/modules/core/src/naming/nameUtils.ts
  app/scripts/modules/core/src/notification/AppNotificationsService.ts
  app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/bake/BakeryReader.ts
  app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgment.service.ts
  app/scripts/modules/core/src/pipeline/config/stages/monitoreddeploy/DeploymentMonitorReader.ts
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJob.reader.ts
  app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateWriter.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/ArtifactService.ts
  app/scripts/modules/core/src/pipeline/config/triggers/concourse/concourse.service.ts
  app/scripts/modules/core/src/pipeline/config/triggers/nexus/nexusReader.service.ts
  app/scripts/modules/core/src/presentation/hooks/usePollingData.hook.ts
  app/scripts/modules/core/src/pubsub/PubsubSubscriptionReader.ts
  app/scripts/modules/core/src/search/infrastructure/infrastructureSearch.service.ts
  app/scripts/modules/core/src/securityGroup/SecurityGroupWriter.ts
  app/scripts/modules/core/src/securityGroup/securityGroup.states.ts
  app/scripts/modules/core/src/securityGroup/securityGroupTransformer.service.ts
  app/scripts/modules/core/src/serverGroup/configure/common/serverGroupConfiguration.service.ts
  app/scripts/modules/core/src/services/ServicesReader.ts
  app/scripts/modules/core/src/snapshot/SnapshotReader.ts
  app/scripts/modules/core/src/task/monitor/TaskMonitor.ts
  app/scripts/modules/core/src/task/task.read.service.ts
  app/scripts/modules/dcos/pipeline/stages/runJob/dockerImageAndTagSelector.component.ts
  app/scripts/modules/ecs/src/loadBalancer/loadBalancer.transformer.ts
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/serviceDiscovery/ServiceDiscovery.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
  app/scripts/modules/ecs/src/serverGroup/events/serverGroupEventsReader.service.ts
  app/scripts/modules/ecs/src/serverGroup/serverGroup.transformer.ts
  app/scripts/modules/google/src/address/address.reader.ts
  app/scripts/modules/google/src/interceptors/iap.interceptor.ts
  app/scripts/modules/google/src/loadBalancer/configure/common/commonLoadBalancerCommandBuilder.service.ts
  app/scripts/modules/google/src/loadBalancer/details/deleteModal/deleteModal.controller.ts
  app/scripts/modules/google/src/securityGroup/securityGroupHelpText.service.ts
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
  app/scripts/modules/kubernetes/src/loadBalancer/transformer.ts
  app/scripts/modules/kubernetes/src/securityGroup/transformer.ts
  app/scripts/modules/kubernetes/src/serverGroup/serverGroupCommandBuilder.service.ts
  app/scripts/modules/kubernetes/src/serverGroup/serverGroupTransformer.service.ts
  app/scripts/modules/oracle/src/loadBalancer/loadBalancer.transformer.ts
  app/scripts/modules/tencentcloud/src/image/image.reader.ts
  app/scripts/modules/tencentcloud/src/keyPairs/KeyPairsReader.ts
  app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
Labels: ready to merge, self merge

#8689 feat(core/clusterFilter): Sort cluster filter values alphabetically
  app/scripts/modules/core/src/cluster/filter/ClusterFilters.tsx
  app/scripts/modules/core/src/filterModel/dependentFilter/DependentFilterService.spec.ts
  app/scripts/modules/core/src/filterModel/dependentFilter/DependentFilterService.ts
Labels: ready to merge

#8690 fix(core/cronTrigger): Fix regex for weekly cron triggers
  app/scripts/modules/core/src/pipeline/config/triggers/cron/CronTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/cron/CronWeekly.tsx
Labels: ready to merge

#8693 fix(core/clusterFilter): Use filterModel object to retrieve filter values
  app/scripts/modules/core/src/cluster/allClusters.controller.js
  app/scripts/modules/core/src/cluster/allClusters.html
Labels: ready to merge
