Repository spinnaker/deck, pull requests merged in 2020-05, with the labels that each got.

#8229 fix(pluginsdk): Fix sourcemaps in typescript config
  packages/pluginsdk/pluginconfig/tsconfig.json
Labels: ready to merge

#8232 feat(core/presentation): add 'pin' icon
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/pin.svg
Labels: ready to merge

#8233 fix(core/help): make markdown examples code blocks to fix rendering
  app/scripts/modules/core/src/help/help.contents.ts
Labels: ready to merge

#8234 fix(core/presentation): put TetheredSelect menu on critical layer
  app/scripts/modules/core/src/presentation/TetheredSelect.tsx
Labels: ready to merge

#8235 feat(core/presentation): change <textarea class="code"> font size to default
  app/scripts/modules/core/src/presentation/main.less
Labels: ready to merge

#8237 feat(core/presentation): allow custom max widths on Modal, bugfixes
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
  app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
  app/scripts/modules/core/src/presentation/modal/Modal.module.css
  app/scripts/modules/core/src/presentation/modal/Modal.tsx
  app/scripts/modules/core/src/presentation/modal/ModalFooter.module.css
  app/scripts/modules/core/src/presentation/modal/showModal.tsx
Labels: ready to merge

#8231 refactor(core/managed): use reference for identifying artifacts, not name + type
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#8214 feat(core/managed): Add StatusBubble to denote resource status
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/ObjectRow.module.css
  app/scripts/modules/core/src/managed/ObjectRow.tsx
  app/scripts/modules/core/src/managed/StatusBubble.less
  app/scripts/modules/core/src/managed/StatusBubble.tsx
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/mdUnhappy.svg
Labels: ready to merge

#8236 feat(core/presentation): Add two new Validators to test for valid Json and valid XML strings
  app/scripts/modules/core/src/presentation/forms/validation/validators.spec.ts
  app/scripts/modules/core/src/presentation/forms/validation/validators.ts
Labels: ready to merge

#8130 fix(amazon/loadbalancer): change default deregistration delay to 300
  app/scripts/modules/amazon/src/help/amazon.help.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
  app/scripts/modules/amazon/src/loadBalancer/configure/common/targetGroupValidators.spec.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
  app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
Labels: ready to merge

#8247 chore(package): publish amazon 0.0.252 core 0.0.473 ecs 0.0.257 kubernetes 0.0.38
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/kubernetes/package.json
Labels: ready to merge

#8249 feat(core/presentation): Add a formik hook to save/restore data
  app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.spec.tsx
  app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.ts
Labels: ready to rebase

#8248 test(core/presentation): Test SpinFormik touches initial values
  app/scripts/modules/core/src/presentation/forms/SpinFormik.spec.tsx
Labels: ready to merge

#8254 feat(core/utils): Add utility function to filter deeply nested leaf nodes from an object
  app/scripts/modules/core/src/utils/json/filterObjectValues.spec.ts
  app/scripts/modules/core/src/utils/json/filterObjectValues.ts
Labels: ready to merge

#8256 chore(pluginsdk): bump to 0.0.11
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#8259 fix(core/presentation): Export the new save/restore formik fields hook
  app/scripts/modules/core/src/presentation/forms/hooks/index.ts
  app/scripts/modules/core/src/presentation/forms/index.ts
Labels: ready to merge, self merge

#8264 fix(core/presentation): remove unnecessary console.error that snuck in from a debugging session
  app/scripts/modules/core/src/presentation/forms/inputs/SelectInput.tsx
Labels: ready to merge

#8267 fix(core/notification): stop infinite-looping on custom notification input
  app/scripts/modules/core/src/notification/modal/WhenChecklistInput.tsx
Labels: ready to merge

#8262 fix(core/managed): prevent expand/collapse from selecting text
  app/scripts/modules/core/src/managed/EnvironmentRow.less
Labels: ready to merge

#8263 refactor(core): remove `skin` and `providerVersion`
  app/scripts/modules/core/src/account/AccountService.ts
  app/scripts/modules/core/src/cloudProvider/CloudProviderRegistry.spec.ts
  app/scripts/modules/core/src/cloudProvider/CloudProviderRegistry.ts
  app/scripts/modules/core/src/cloudProvider/cloudProvider.module.ts
  app/scripts/modules/core/src/cloudProvider/index.ts
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.spec.ts
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.ts
  app/scripts/modules/core/src/cloudProvider/providerService.delegate.ts
  app/scripts/modules/core/src/cloudProvider/skin.service.spec.ts
  app/scripts/modules/core/src/cloudProvider/skin.service.ts
  app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelection.service.ts
  app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelector.component.ts
  app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelector.html
  app/scripts/modules/core/src/cluster/allClusters.controller.js
  app/scripts/modules/core/src/function/CreateFunctionButton.tsx
  app/scripts/modules/core/src/function/function.transformer.js
  app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
  app/scripts/modules/core/src/instance/instance.states.ts
  app/scripts/modules/core/src/loadBalancer/CreateLoadBalancerButton.tsx
  app/scripts/modules/core/src/loadBalancer/loadBalancer.transformer.js
  app/scripts/modules/core/src/naming/nameUtils.ts
  app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
  app/scripts/modules/core/src/overrideRegistry/Overrides.tsx
  app/scripts/modules/core/src/pipeline/config/PipelineRegistry.spec.ts
  app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts
  app/scripts/modules/core/src/reactShims/react.injector.ts
  app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
  app/scripts/modules/core/src/securityGroup/CreateSecurityGroupButton.tsx
  app/scripts/modules/core/src/securityGroup/securityGroup.states.ts
  app/scripts/modules/core/src/securityGroup/securityGroupTransformer.service.ts
  app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
  app/scripts/modules/core/src/serverGroup/details/ServerGroupDetailsWrapper.tsx
  app/scripts/modules/core/src/serverGroup/serverGroup.transformer.js
  app/scripts/modules/kubernetes/src/kubernetes.module.ts
  app/scripts/modules/kubernetes/src/manifest/manifestCommandBuilder.service.ts
  app/scripts/modules/kubernetes/src/manifest/selector/ManifestSelector.tsx
  app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/DeployManifestStageConfig.tsx
  app/scripts/modules/kubernetes/src/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
Labels: ready to merge

#8266 feat(amazon): Filter SG's that are in exclusion list
  app/scripts/modules/amazon/src/aws.settings.ts
  app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
  app/scripts/modules/core/src/utils/index.ts
Labels: ready to merge

#8270 chore(package): publish amazon 0.0.253 core 0.0.475 kubernetes 0.0.39
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/kubernetes/package.json
Labels: ready to merge

#8277 fix(bake): adding skip region detection checkbox
  app/scripts/modules/amazon/src/pipeline/stages/bake/bakeStage.html
  app/scripts/modules/core/src/help/help.contents.ts
Labels: ready to merge

#8282 feat(core/presentation): Give validators.ts function names for easier debugging
  app/scripts/modules/core/src/presentation/forms/validation/validators.ts
Labels: ready to merge

#8210 feat(tencentcloud): init tencentcloud
  app/scripts/app.ts
  app/scripts/modules/build_order.sh
  app/scripts/modules/tencentcloud/.npmignore
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/tencentcloud/src/index.ts
  app/scripts/modules/tencentcloud/src/logo/tencentcloud.icon.svg
  app/scripts/modules/tencentcloud/src/logo/tencentcloud.logo.less
  app/scripts/modules/tencentcloud/src/logo/tencentcloud.logo.svg
  app/scripts/modules/tencentcloud/src/tencentcloud.module.ts
  app/scripts/modules/tencentcloud/src/tencentcloud.setting.ts
  app/scripts/modules/tencentcloud/tsconfig.json
  app/scripts/modules/tencentcloud/webpack.config.js
  halconfig/settings.js
  settings.js
  tsconfig.json
  webpack.config.js
Labels: ready to merge

#8279 refactor(core/presentation): migrate useData and useLatestPromise to use PromiseLike, not IPromise
  app/scripts/modules/core/src/presentation/hooks/useData.hook.ts
  app/scripts/modules/core/src/presentation/hooks/useLatestPromise.hook.ts
Labels: ready to merge

#8289 fix(core/presentation): Memoize defaultResult in useData.hook.ts
  app/scripts/modules/core/src/presentation/hooks/useData.hook.ts
Labels: ready to merge

#8291 feat(tencentcloud): add type definition files for tencentcloud
  app/scripts/modules/tencentcloud/src/domain/IKeyPair.ts
  app/scripts/modules/tencentcloud/src/domain/IScalingPolicy.ts
  app/scripts/modules/tencentcloud/src/domain/IScalingProcess.ts
  app/scripts/modules/tencentcloud/src/domain/ITargetTrackingPolicy.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudCertificate.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudHealth.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudInstance.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudLoadBalancer.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudLoadBalancerSourceData.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudScalingPolicy.ts
  app/scripts/modules/tencentcloud/src/domain/ITencentCloudServerGroup.ts
  app/scripts/modules/tencentcloud/src/domain/index.ts
Labels: ready to merge

#8290 fix(core/presentation): clear out prior 'touched' values in useSaveRestoreMutuallyExclusiveField
  app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.spec.tsx
  app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.ts
Labels: ready to merge

#8293 chore(core): Upgrade babel to v7
  .babelrc
  package.json
  yarn.lock
Labels: ready to merge

#8299 feat(core/presentation): adds managed delivery illustrations
  app/scripts/modules/core/src/presentation/illustrations/managedDeliveryMarkAsBad.svg
  app/scripts/modules/core/src/presentation/illustrations/managedDeliveryPause.svg
  app/scripts/modules/core/src/presentation/illustrations/managedDeliveryPin.svg
  app/scripts/modules/core/src/presentation/illustrations/managedDeliveryRun.svg
  app/scripts/modules/core/src/presentation/illustrations/managedDeliveryUnpin.svg
Labels: ready to merge

#8297 feat(core/presentation): adds form field icons
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/add.svg
  app/scripts/modules/core/src/presentation/icons/vectors/config.svg
  app/scripts/modules/core/src/presentation/icons/vectors/delete.svg
  app/scripts/modules/core/src/presentation/icons/vectors/done.svg
  app/scripts/modules/core/src/presentation/icons/vectors/duplicate.svg
  app/scripts/modules/core/src/presentation/icons/vectors/edit.svg
  app/scripts/modules/core/src/presentation/icons/vectors/fileJson.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formDrag.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formError.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formInfo.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formNetworkBad.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formNetworkGood.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formRefresh.svg
  app/scripts/modules/core/src/presentation/icons/vectors/formWarning.svg
  app/scripts/modules/core/src/presentation/icons/vectors/toggleOff.svg
  app/scripts/modules/core/src/presentation/icons/vectors/toggleOn.svg
Labels: ready to merge

#8296 feat(tencentcloud): add help, image, keyPairs, reactShims, search, va…
  app/scripts/modules/tencentcloud/src/help/tencentcloud.help.ts
  app/scripts/modules/tencentcloud/src/image/image.reader.ts
  app/scripts/modules/tencentcloud/src/image/index.ts
  app/scripts/modules/tencentcloud/src/index.ts
  app/scripts/modules/tencentcloud/src/keyPairs/KeyPairsReader.ts
  app/scripts/modules/tencentcloud/src/keyPairs/index.ts
  app/scripts/modules/tencentcloud/src/reactShims/index.ts
  app/scripts/modules/tencentcloud/src/reactShims/tencentcloud.ngReact.ts
  app/scripts/modules/tencentcloud/src/reactShims/tencentcloud.react.injector.ts
  app/scripts/modules/tencentcloud/src/reactShims/tencentcloud.react.module.ts
  app/scripts/modules/tencentcloud/src/search/searchResultFormatter.js
  app/scripts/modules/tencentcloud/src/tencentcloud.module.ts
  app/scripts/modules/tencentcloud/src/tencentcloud.settings.ts
  app/scripts/modules/tencentcloud/src/validation/ApplicationNameValidator.ts
  app/scripts/modules/tencentcloud/tsconfig.json
Labels: ready to merge

#8305 chore(pluginsdk): do not share tslib
  app/scripts/modules/core/src/plugins/sharedLibraries.ts
Labels: ready to merge, self merge

#8287 fix(pipelines): prevent pipelineConfig pollution caused by retrying a trigger unsuccessfully.
  app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
  app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.spec.js
Labels: ready to merge

#8308 chore(package): publish core 0.0.478 tencentcloud 0.0.2
  app/scripts/modules/core/package.json
  app/scripts/modules/tencentcloud/package.json
Labels: ready to merge

#8302 fix(amazon): Include custom component form state for validation
  app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.html
  app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
  app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroup.html
  app/scripts/modules/amazon/src/securityGroup/configure/editSecurityGroup.html
Labels: ready to merge

#8314 Do not index into strings for FormikFormField error handling
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.spec.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
Labels: ready to rebase
