Repository spinnaker/deck, pull requests merged in 2020-01, with the labels that each got.

#7735 chore(amazon): Bump amazon version to 0.0.227
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7736 fix(plugins): Default plugins to empty list to prevent NPE
  app/scripts/modules/core/src/config/settings.ts
Labels: auto merged, ready to merge

#7737 fix(amazon): Fix additionalIpRules component imports
  app/scripts/modules/amazon/src/securityGroup/configure/additionalIpRules.tsx
Labels: auto merged, ready to merge

#7738 chore(amazon): Bump Amazon version to 0.0.228
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7741 fix(ecs): Fixes AmazonLoadBalancerChoiceModal for ecs
  app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
Labels: ready to merge

#7721 refactor(core): provide wrapper for dangerously setting html
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  app/scripts/modules/cloudfoundry/src/deploymentStrategy/CloudFoundryDeploymentStrategySelector.tsx
  app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/cloneSettings/CloneSettings.cf.tsx
  app/scripts/modules/core/src/cancelModal/CancelModal.tsx
  app/scripts/modules/core/src/deploymentStrategy/DeploymentStrategySelector.tsx
  app/scripts/modules/core/src/help/HelpField.tsx
  app/scripts/modules/core/src/pagerDuty/Pager.tsx
  app/scripts/modules/core/src/pipeline/config/graph/PipelineGraphNode.tsx
  app/scripts/modules/core/src/presentation/Markdown.less
  app/scripts/modules/core/src/presentation/Markdown.tsx
  app/scripts/modules/core/src/search/infrastructure/SearchResult.tsx
  app/scripts/modules/core/src/widgets/notifier/Notifier.tsx
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/ManifestDeploymentOptions.tsx
Labels: ready to merge

#7732 refactor(core/amazon): remove unused CSS rules
  app/scripts/modules/amazon/src/loadBalancer/configure/common/configure.less
  app/scripts/modules/canary/canary.less
  app/scripts/modules/core/src/application/application.less
  app/scripts/modules/core/src/application/applications.less
  app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.less
  app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.ts
  app/scripts/modules/core/src/application/newapplication.less
  app/scripts/modules/core/src/chaosMonkey/chaosMonkeyConfig.component.less
  app/scripts/modules/core/src/cluster/rollups.less
  app/scripts/modules/core/src/function/FunctionPod.tsx
  app/scripts/modules/core/src/function/functionPod.less
  app/scripts/modules/core/src/healthCounts/healthCounts.less
  app/scripts/modules/core/src/instance/instanceSelection.less
  app/scripts/modules/core/src/modal/modals.less
  app/scripts/modules/core/src/navigation/navigation.less
  app/scripts/modules/core/src/notification/modal/editNotification.less
  app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.less
  app/scripts/modules/core/src/pipeline/pipeline.less
  app/scripts/modules/core/src/presentation/main.less
  app/scripts/modules/core/src/presentation/navPopover.less
  app/scripts/modules/core/src/presentation/stickyHeader.less
Labels: auto merged, ready to merge

#7745 feat(core): add validator for stage/trigger providing repository info
  app/scripts/modules/core/src/domain/IStageOrTriggerTypeConfig.ts
  app/scripts/modules/core/src/pipeline/config/pipelineConfig.module.js
  app/scripts/modules/core/src/pipeline/config/triggers/git/git.trigger.ts
  app/scripts/modules/core/src/pipeline/config/validation/repositoryInformationProvided.validator.ts
  app/scripts/modules/core/src/pipeline/config/validation/upstreamHasFlagValidator.builder.ts
  app/scripts/modules/core/src/pipeline/config/validation/upstreamVersionProvided.validator.ts
Labels: auto merged, ready to rebase

#7729 feat(core): add pause/resume to managed resource menu
  app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
  app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.html
  app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.html
  app/scripts/modules/core/src/help/HelpField.tsx
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/managedResourceDetailsIndicator.component.ts
  app/scripts/modules/core/src/managed/toggleResourceManagement.ts
  app/scripts/modules/core/src/pipeline/config/stages/common/stageConfigField/stageConfigField.directive.spec.js
  app/scripts/modules/core/src/serverGroup/details/ServerGroupDetails.tsx
Labels: auto merged, ready to rebase

#7728 feat(core): offer to pause managed resources before performing actions
  app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
  app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx
  app/scripts/modules/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx
  app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingProcessesDetailsSection.tsx
  app/scripts/modules/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx
  app/scripts/modules/core/src/managed/index.ts
  app/scripts/modules/core/src/managed/toggleResourceManagement.ts
  app/scripts/modules/core/src/managed/toggleResourceManagement.tsx
Labels: ready to rebase

#7746 chore(core): bump package to 0.0.438
  app/scripts/modules/core/package.json
Labels: ready to rebase

#7747 chore(amazon): bump package to 0.0.229
  app/scripts/modules/amazon/package.json
Labels: ready to merge, ready to rebase

#7756 fix(core): Update functional tests with new modal heading el
  test/functional/tests/google/pages/CreateServerGroupModalPage.ts
Labels: ready to merge

#7760 fix(kubernetes): remove accidental static from resolveIndexedSecurity…
  app/scripts/modules/kubernetes/src/shared/securityGroup/securityGroup.reader.ts
Labels: ready to merge

#7733 feat(managed-delivery): Add UI for importDeliveryConfig stage
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/domain/IStageOrTriggerTypeConfig.ts
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/managed/importDeliveryConfigStage.ts
  app/scripts/modules/core/src/pipeline/pipeline.module.ts
  app/scripts/modules/core/src/presentation/forms/inputs/TextInput.tsx
  settings.js
Labels: ready to merge

#7757 fix(core): keep health counts on one line in server group title
  app/scripts/modules/core/src/cluster/rollups.less
  app/scripts/modules/core/src/healthCounts/HealthCounts.tsx
  app/scripts/modules/core/src/healthCounts/healthCounts.less
  app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.html
  app/scripts/modules/core/src/serverGroup/ServerGroupHeader.tsx
Labels: auto merged, ready to merge

#7758 fix(core): catch/handle confirmation modal dismissal
  app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts
Labels: auto merged, ready to merge

#7754 feat(core/amazon/titus): do not allow create/clone in managed clusters
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  app/scripts/modules/core/src/managed/DeployingIntoManagedClusterWarning.tsx
  app/scripts/modules/core/src/managed/index.ts
  app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
  app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
Labels: auto merged, ready to merge

#7761 chore(core): Bump version to 0.0.440
  app/scripts/modules/core/package.json
Labels: ready to merge

#7762 chore(amazon): bump package to 0.0.231
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7765 fix(core/pipeline): use fresh trigger + stage list for upstream flag validation
  app/scripts/modules/core/src/pipeline/config/validation/upstreamHasFlagValidator.builder.ts
Labels: ready to merge

#7766 chore(core): bump to 0.0.441
  app/scripts/modules/core/package.json
Labels: ready to merge

#7767 fix(plugins): Remove plugins entry that is causing runtime errors
  halconfig/settings.js
Labels: ready to merge

#7772 fix(core): display task monitor above page navigator chrome
  app/scripts/modules/core/src/modal/modals.less
Labels: ready to merge

#7775 fix(titus): Blank IAM profile unclickable
  app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx
Labels: ready to merge

#7774 fix(core): do not render the server group warning message in <pre>
  app/scripts/modules/appengine/src/loadBalancer/details/details.controller.ts
  app/scripts/modules/appengine/src/serverGroup/details/details.controller.ts
  app/scripts/modules/core/src/pipeline/details/stageSummary.component.ts
  app/scripts/modules/core/src/serverGroup/details/serverGroupWarningMessage.service.ts
Labels: auto merged, ready to merge

#7776 feat(titus): add Managed by Spinnaker section to details
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
Labels: ready to merge

#7792 feat(artifacts): link to updated docs from Match Artifact tooltip
  app/scripts/modules/core/src/help/help.contents.ts
Labels: auto merged, ready to merge

#7795 fix(aws): Fixing cross-app security group lookup
  app/scripts/modules/amazon/src/securityGroup/securityGroup.reader.ts
  app/scripts/modules/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx
Labels: ready to merge

#7797 chore(core): clean up import warnings
  app/scripts/modules/core/src/modal/index.ts
  app/scripts/modules/core/src/modal/wizard/ModalWizard.ts
  app/scripts/modules/core/src/modal/wizard/WizardPage.tsx
  app/scripts/modules/core/src/modal/wizard/index.ts
  app/scripts/modules/core/src/modal/wizard/v2wizardPage.component.ts
  app/scripts/modules/core/src/pagerDuty/Pager.tsx
Labels: ready to merge

#7740 feat(spel): add SpEL-awareness to FormikFormField
  app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.spec.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
  app/scripts/modules/core/src/presentation/forms/forms.less
  app/scripts/modules/core/src/presentation/forms/layouts/ResponsiveFieldLayout.tsx
  app/scripts/modules/core/src/presentation/spel/FormikSpelContext.ts
  app/scripts/modules/core/src/presentation/spel/SpelInput.tsx
  app/scripts/modules/core/src/presentation/spel/SpelService.ts
  app/scripts/modules/core/src/presentation/spel/SpelToggle.tsx
  app/scripts/modules/core/src/presentation/spel/index.ts
Labels: auto merged, ready to merge

#7801 fix(artifacts): Fix find artifacts from execution stage
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/defaultBase64.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/bitbucket.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/defaultBitbucket.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/defaultDocker.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/defaultGcs.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/gcs.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/defaultGithub.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/defaultGitlab.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/gitlab.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/helm.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/defaultHttp.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/http.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/ivy/ivy.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/jenkins/jenkins.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/maven/maven.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/defaultS3.artifact.ts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/s3.artifact.ts
Labels: ready to merge

#7803 fix(aws): Component for additional security group details
  app/scripts/modules/amazon/src/securityGroup/configure/EditSecurityGroupCtrl.js
  app/scripts/modules/amazon/src/securityGroup/configure/additionalIpRules.component.ts
  app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
  app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupIngress.html
  app/scripts/modules/amazon/src/securityGroup/configure/securityGroupDetailsCustom.component.ts
  app/scripts/modules/amazon/src/securityGroup/configure/securityGroupDetailsCustom.tsx
  app/scripts/modules/amazon/src/securityGroup/securityGroup.module.ts
  app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
Labels: auto merged, ready to merge

#7806 chore(aws): Bump aws to version v0.0.232
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7807 refactor(titus): Removing container migration as it is no longer used
  app/scripts/modules/titus/src/migration/titusMigrationConfig.component.html
  app/scripts/modules/titus/src/migration/titusMigrationConfig.component.less
  app/scripts/modules/titus/src/migration/titusMigrationConfig.component.ts
  app/scripts/modules/titus/src/migration/titusMigrationConfigurer.component.html
  app/scripts/modules/titus/src/migration/titusMigrationConfigurer.component.ts
  app/scripts/modules/titus/src/titus.module.ts
Labels: ready to merge

#7788 feat(plugins): read plugin config from plugin-manifest.json
  app/scripts/modules/core/src/plugins/plugin.module.ts
  plugin-manifest.js
  webpack.config.js
Labels: ready to merge

#7809 chore(deps): bump @spinnaker/kayenta from 0.0.88 to 0.0.89
  package.json
  yarn.lock
Labels: ready to merge

#7811 feat(core): Forward params through execution lookup
  app/scripts/modules/core/src/pipeline/pipeline.states.ts
Labels: ready to merge

#7812 fix(deck): use label for parameters in manual execution if supplied
  app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
  test/functional/tests/core/manual_execution_smoke_test.spec.ts.mountebank_fixture.json
  test/functional/tests/core/pages/ManualExecutionModalPage.ts
Labels: ready to merge

#7814 feat(deck): Add execution error details to Task Status in Cloud Formation Stage
  app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationExecutionDetails.tsx
  app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackStage.ts
  app/scripts/modules/core/src/pipeline/config/stages/common/index.ts
Labels: ready to merge

#7818 feat(core): enable the "Override Helm chart artifact" checkbox in man…
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManualExecutionBakeManifest.tsx
Labels: ready to merge

#7820 fix(titus/serverGroup): use correct prop name for managed resource banner
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
Labels: auto merged, ready to merge

#7824 fix(gce logo): Use a proper GCE logo
  app/scripts/modules/google/src/logo/gce.logo.png
Labels: ready to merge

#7815 chore(kubernetes): Bump version to 0.0.31
  app/scripts/modules/kubernetes/package.json
Labels: auto merged, ready to merge
