Repository spinnaker/deck, pull requests merged in 2020-03, with the labels that each got.

#7989 fix(artifacts): fix editing expected artifacts in artifact rewrite tr…
  app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
Labels: ready to merge

#7983 feat(scripts): Add show_package_bumps script that outputs all package bumps and their commit shas.
  app/scripts/modules/show_changelog.sh
  app/scripts/modules/show_dirty_modules.sh
  app/scripts/modules/show_package_bumps.js
  app/scripts/modules/show_unpublished_commits.sh
Labels: ready to merge

#7993 fix(assert_clean_master): Output error messages to stderr, not stdout
  app/scripts/modules/assert_clean_master.sh
Labels: ready to merge, self merge

#7984 feat(core/presentation): add usePollingData hook for scheduled fetching
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/usePollingData.hook.spec.tsx
  app/scripts/modules/core/src/presentation/hooks/usePollingData.hook.ts
Labels: ready to merge

#7977 feat(core/application): export navigation category registry
  app/scripts/modules/core/src/application/index.ts
Labels: ready to merge

#7996 feat(publish): Add a package publishing helper script in modules/
  app/scripts/modules/publish.js
  app/scripts/modules/publish.sh
  package.json
  yarn.lock
Labels: ready to merge

#8000 fix(core/presentation): useData: continue to return the default value…
  app/scripts/modules/core/src/presentation/hooks/useData.hook.spec.tsx
  app/scripts/modules/core/src/presentation/hooks/useData.hook.ts
Labels: ready to merge

#8001 fix(aws): Export security group interfaces
  app/scripts/modules/amazon/src/securityGroup/details/index.ts
  app/scripts/modules/amazon/src/securityGroup/index.ts
Labels: ready to merge

#7987 feat(core/presentation): add imperative showModal API (née ReactModal)
  app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
  app/scripts/modules/core/src/presentation/ReactModal.tsx
  app/scripts/modules/core/src/presentation/modal/Modal.tsx
  app/scripts/modules/core/src/presentation/modal/index.ts
  app/scripts/modules/core/src/presentation/modal/showModal.tsx
Labels: ready to merge

#8005 chore(bump): Bump Amazon to 0.0.241
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7988 feat(core/managed): use showModal API for history modal
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#7997 feat(core/managed): add history modal button to status popovers, revise language
  app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
Labels: ready to rebase

#7985 feat(core/managed): poll for new history events in modal
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
  app/scripts/modules/core/src/presentation/hooks/index.ts
Labels: ready to merge

#8008 fix(amazon): Export securityGroup interfaces
  app/scripts/modules/amazon/src/index.ts
Labels: ready to merge

#8009 chore(bump): Amazon package bump to 0.0.242
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#8010 fix(core): Order executions by startTime not endTime
  app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Labels: ready to merge

#8015 chore(package): publish amazon 0.0.243 core 0.0.456
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
Labels: ready to merge

#8017 fix(core/pipeline): Fix default values for preconfigured job parameters
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.ts
Labels: ready to merge

#8018 Allow markdown in stage descriptions
  app/scripts/modules/core/src/pipeline/config/stages/stage.html
  app/scripts/modules/core/src/presentation/markdown.component.ts
  app/scripts/modules/core/src/presentation/presentation.module.js
Labels: ready to merge

#8019 chore(package): publish core 0.0.457
  app/scripts/modules/core/package.json
Labels: ready to merge

#8020 feat(md): Types and new data source for environments
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/managed.dataSource.ts
Labels: Do Not Merge

#8013 fix(core): Fixing AccountSelectInput sync issue
  app/scripts/modules/core/src/account/accountSelectField.component.ts
Labels: ready to merge

#8024 fix(core): Explain characters are invalid in hostname
  app/scripts/modules/amazon/src/validation/ApplicationNameValidator.ts
Labels: ready to merge

#7982 chore(lint): Update eslint plugin to include react hooks
  package.json
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/package.json
  yarn.lock
Labels: ready to merge

#7940 fix(amazon/iamRole): Do not default iamRole in deploy edit scenario
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
Labels: ready to merge

#8022 feat(md): Types and new data source for environments
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/managed.dataSource.ts
Labels: ready to merge

#8027 chore(package): publish amazon 0.0.244 core 0.0.458
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
Labels: ready to merge

#8029 feat(amazon/serverGroupDetails): Make server group's details field overridable
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/fields/ServerGroupDetailsField.tsx
Labels: ready to merge

#8030 refactor(core/pipeline): Migrate Preconfigured Job default config UI to use FormikStageConfig
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/index.ts
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJob.reader.ts
Labels: ready to merge

#8033 chore(package): update eslint-plugin to 1.0.6
  package.json
  yarn.lock
Labels: ready to merge, self merge

#8031 feat(pluginsdk): Create a plugin sdk npm package that can be depended on by plugins
  packages/pluginsdk/package.json
  packages/pluginsdk/pluginconfig/README.md
  packages/pluginsdk/pluginconfig/rollup.config.js
  packages/pluginsdk/pluginconfig/tsconfig.json
  packages/pluginsdk/rollup.config.js
  packages/pluginsdk/src/index.ts
  packages/pluginsdk/tsconfig.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge

#8028 fix(plugins): better error messages when loading plugin information
  app/scripts/modules/core/src/plugins/plugin.registry.ts
Labels: ready to merge

#8035 chore(package): publish amazon 0.0.245 appengine 0.0.9 azure 0.0.249 cloudfoundry 0.0.94 core 0.0.459 ecs 0.0.252 google 0.0.10 huaweicloud 0.0.2 kubernetes 0.0.33 oracle 0.0.4
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
Labels: ready to merge

#8036 chore(pluginsdk): bump to @spinnaker/core@0.0.459
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#7862 fix(kubernetes): Shorten displayed digest to the first 7 characters i…
  app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
Labels: ready to merge

#8037 Bump pluginsdk to 0.0.4
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#8039 release pluginsdk 0.0.5
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#8038 fix(core): Do not initialize strategies on mount
  app/scripts/modules/core/src/deploymentStrategy/DeploymentStrategySelector.tsx
Labels: ready to merge

#8032 feat(md): Initial draft of Environments view
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactRow.module.css
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/ColumnHeader.module.css
  app/scripts/modules/core/src/managed/ColumnHeader.tsx
  app/scripts/modules/core/src/managed/Environments.module.css
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/NoticeCard.module.css
  app/scripts/modules/core/src/managed/NoticeCard.tsx
  app/scripts/modules/core/src/managed/ObjectRow.module.css
  app/scripts/modules/core/src/managed/ObjectRow.tsx
  app/scripts/modules/core/src/managed/Pill.module.css
  app/scripts/modules/core/src/managed/Pill.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#8042 fix(core/application): rearrange init ordering of member variables on data sources
  app/scripts/modules/core/src/application/service/applicationDataSource.ts
Labels: ready to merge

#8043 refactor(md): Use useDataSource hook
  app/scripts/modules/core/src/managed/Environments.tsx
Labels: ready to merge

#8041 fix(amazon/instance): Show health status failure reason for load balancers
  app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx
Labels: ready to merge

#8046 chore(package): core to 0.0.460
  app/scripts/modules/core/package.json
Labels: ready to merge

#8047 feat(md): Generate fallback artifact info using Frigga
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/Frigga.ts
Labels: ready to merge

#8048 feat(core/managed): add artifact detail pane to environments
  app/scripts/modules/core/src/managed/ArtifactDetail.less
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
  app/scripts/modules/core/src/managed/ArtifactRow.module.css
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
Labels: ready to merge

#8049 fix(ecs): Update tooltip for using previous server group capacity
  app/scripts/modules/ecs/src/ecs.help.ts
Labels: ready to merge

#8050 chore(titus): Reenable previous image rollbacks for titus
  app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
  app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.html
Labels: ready to merge

#8053 fix(kubernetes): whitelist helm artifact types for bake manifest stage
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
Labels: ready to merge

#8058 fix(core/managed): fix check for row expandability on history table
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#8059 chore(package): titus to 0.0.130
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8055 refactor(svg): add SVGR loader for inlined react SVG support
  app/scripts/modules/amazon/src/aws.module.ts
  app/scripts/modules/amazon/src/svg.d.ts
  app/scripts/modules/amazon/webpack.config.js
  app/scripts/modules/appengine/src/svg.d.ts
  app/scripts/modules/appengine/webpack.config.js
  app/scripts/modules/azure/src/svg.d.ts
  app/scripts/modules/azure/webpack.config.js
  app/scripts/modules/cloudfoundry/src/cf.module.ts
  app/scripts/modules/cloudfoundry/src/svg.d.ts
  app/scripts/modules/cloudfoundry/webpack.config.js
  app/scripts/modules/core/src/artifact/ArtifactIconService.ts
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/svg.d.ts
  app/scripts/modules/core/webpack.config.js
  app/scripts/modules/docker/src/svg.d.ts
  app/scripts/modules/docker/webpack.config.js
  app/scripts/modules/ecs/src/ecs.module.ts
  app/scripts/modules/ecs/src/svg.d.ts
  app/scripts/modules/ecs/webpack.config.js
  app/scripts/modules/google/src/svg.d.ts
  app/scripts/modules/google/webpack.config.js
  app/scripts/modules/huaweicloud/src/svg.d.ts
  app/scripts/modules/huaweicloud/webpack.config.js
  app/scripts/modules/kubernetes/src/svg.d.ts
  app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts
  app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
  app/scripts/modules/kubernetes/webpack.config.js
  app/scripts/modules/oracle/src/svg.d.ts
  app/scripts/modules/oracle/webpack.config.js
  app/scripts/modules/titus/src/svg.d.ts
  app/scripts/modules/titus/webpack.config.js
  package.json
  webpack.config.js
  yarn.lock
Labels: ready to merge

#8056 feat(core/presentation): add Icon component w/ inline SVG
  .gitignore
  app/scripts/modules/core/src/presentation/icons/Icon.tsx
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/index.ts
  app/scripts/modules/core/src/presentation/icons/vectors/artifact.svg
  app/scripts/modules/core/src/presentation/icons/vectors/close.svg
  app/scripts/modules/core/src/presentation/icons/vectors/environment.svg
  app/scripts/modules/core/src/presentation/index.ts
Labels: ready to merge

#8052 fix(core): replace default account select option
  app/scripts/modules/core/src/account/AccountSelectInput.tsx
Labels: ready to merge

#8062 chore(titus/amazon): Bump to amazon@0.0.246, titus@0.0.131
  app/scripts/modules/amazon/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8060 feat(core/managed): use real data for version progress in Environments
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactRow.module.css
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
Labels: ready to merge

#8063 feat(core/managed): add resource breakdown to artifact details
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/ObjectRow.tsx
Labels: ready to merge

#8064 chore(package): publish appengine 0.0.10 azure 0.0.250 cloudfoundry 0.0.95 core 0.0.461 docker 0.0.54 ecs 0.0.253 google 0.0.11 huaweicloud 0.0.3 kubernetes 0.0.34 oracle 0.0.5
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
Labels: ready to merge

#8065 fix(kubernetes): specify manifest source as text for ad-hoc applies
  app/scripts/modules/kubernetes/src/v2/manifest/ManifestSource.ts
  app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
Labels: ready to merge

#8070 fix(core): Fix effect in TaskMonitorWrapper
  app/scripts/modules/core/src/task/monitor/TaskMonitorWrapper.tsx
Labels: ready to merge

#8077 fix(artifacts): only remove deleted expected artifacts from stages on…
  app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
Labels: ready to merge

#8078 chore(titus): Bump to 0.0.132
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8075 refactor(artifacts): clean up ArtifactReferenceService
  app/scripts/modules/core/src/artifact/ArtifactReferenceService.spec.ts
  app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts
Labels: ready to merge

#8069 feat(core/managed): status indicators, explanation cards on artifacts
  app/scripts/modules/core/src/managed/ArtifactDetail.less
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactRow.module.css
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/NoticeCard.module.css
  app/scripts/modules/core/src/managed/NoticeCard.tsx
  app/scripts/modules/core/src/managed/ObjectRow.module.css
Labels: ready to merge

#8079 chore(package): publish core 0.0.463
  app/scripts/modules/core/package.json
Labels: ready to merge

#8068 feat(amazon/details): Pass application to details field
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/fields/ServerGroupDetailsField.tsx
Labels: ready to merge

#8081 feat(core/managed): Group resources under EnvironmentRow
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/EnvironmentRow.less
  app/scripts/modules/core/src/managed/EnvironmentRow.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/Frigga.ts
  app/scripts/modules/core/src/managed/ObjectRow.module.css
  app/scripts/modules/core/src/managed/ObjectRow.tsx
Labels: ready to merge

#8080 feat(core/managed): show relevant resources on version details
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
Labels: ready to merge

#8084 chore(package): publish amazon 0.0.247 core 0.0.464
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
Labels: ready to merge

#8085 fix(core): Stop propagation of task monitor close event
  app/scripts/modules/core/src/task/monitor/TaskMonitor.ts
Labels: ready to merge

#8083 feat(core/presentation): adds svg icons for new ui designs
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/accordionCollapse.svg
  app/scripts/modules/core/src/presentation/icons/vectors/accordionExpand.svg
  app/scripts/modules/core/src/presentation/icons/vectors/accordionExpandAll.svg
  app/scripts/modules/core/src/presentation/icons/vectors/build.svg
  app/scripts/modules/core/src/presentation/icons/vectors/canaryFail.svg
  app/scripts/modules/core/src/presentation/icons/vectors/canaryMarginal.svg
  app/scripts/modules/core/src/presentation/icons/vectors/canaryPass.svg
  app/scripts/modules/core/src/presentation/icons/vectors/canaryRunning.svg
  app/scripts/modules/core/src/presentation/icons/vectors/checkBadge.svg
  app/scripts/modules/core/src/presentation/icons/vectors/checkboxChecked.svg
  app/scripts/modules/core/src/presentation/icons/vectors/checkboxIndeterminate.svg
  app/scripts/modules/core/src/presentation/icons/vectors/checkboxUnchecked.svg
  app/scripts/modules/core/src/presentation/icons/vectors/closeSmall.svg
  app/scripts/modules/core/src/presentation/icons/vectors/cloudDecommissioned.svg
  app/scripts/modules/core/src/presentation/icons/vectors/cloudDeployed.svg
  app/scripts/modules/core/src/presentation/icons/vectors/cloudError.svg
  app/scripts/modules/core/src/presentation/icons/vectors/cloudProgress.svg
  app/scripts/modules/core/src/presentation/icons/vectors/cluster.svg
  app/scripts/modules/core/src/presentation/icons/vectors/copyClipboard.svg
  app/scripts/modules/core/src/presentation/icons/vectors/fn.svg
  app/scripts/modules/core/src/presentation/icons/vectors/fnNew.svg
  app/scripts/modules/core/src/presentation/icons/vectors/instances.svg
  app/scripts/modules/core/src/presentation/icons/vectors/loadBalancer.svg
  app/scripts/modules/core/src/presentation/icons/vectors/manualJudgement.svg
  app/scripts/modules/core/src/presentation/icons/vectors/md.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdActuating.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdActuationLaunched.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdCreated.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdDeltaDetected.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdDeltaResolved.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdDiff.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdError.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdFlapping.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdPaused.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdResumed.svg
  app/scripts/modules/core/src/presentation/icons/vectors/mdUnknown.svg
  app/scripts/modules/core/src/presentation/icons/vectors/placeholder.svg
  app/scripts/modules/core/src/presentation/icons/vectors/servergroupAws.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spCIBranch.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spCIBuild.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spCICommit.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spCIMaster.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spCIPullRequest.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuCanaryConfig.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuCanaryReport.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuClusters.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuConfig.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuLoadBalancers.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuPager.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuPipelines.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuProperties.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuSecurityGroups.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuTasks.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuTimeline.svg
  app/scripts/modules/core/src/presentation/icons/vectors/spel.svg
  app/scripts/modules/core/src/presentation/icons/vectors/templateFull.svg
  app/scripts/modules/core/src/presentation/icons/vectors/templateWorkflow.svg
Labels: ready to merge

#8082 fix(core/deploymentStrategy): Handle missing rollback property in command
  app/scripts/modules/core/src/deploymentStrategy/strategies/redblack/AdditionalFields.tsx
Labels: ready to merge

#8091 feat(core/managed): add real icons to Environments view
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
  app/scripts/modules/core/src/managed/ColumnHeader.module.css
  app/scripts/modules/core/src/managed/ColumnHeader.tsx
  app/scripts/modules/core/src/managed/EnvironmentRow.less
  app/scripts/modules/core/src/managed/EnvironmentRow.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/NoticeCard.module.css
  app/scripts/modules/core/src/managed/NoticeCard.tsx
  app/scripts/modules/core/src/managed/ObjectRow.module.css
  app/scripts/modules/core/src/managed/ObjectRow.tsx
Labels: ready to merge

#8090 feat(scripts): switch show_changelog.sh --expand-links to --markdown
  app/scripts/modules/show_changelog.sh
Labels: ready to merge, self merge

#8092 chore(package): publish core 0.0.465
  app/scripts/modules/core/package.json
Labels: ready to merge

#8088 fix(webhook): Show 'Progress' as Info instead of Warning in webhookExecutionDetails
  app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts
  app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.html
Labels: ready to merge

#8094 fix(changelog): Render entire commit sha, add two spaces (a markdown newline) after every commit
  app/scripts/modules/show_changelog.sh
Labels: ready to merge, self merge

#8095 chore(package): publish core 0.0.466
  app/scripts/modules/core/package.json
Labels: ready to merge

#8096 refactor(artifacts): consolidate artifacts feature flags checks
  app/scripts/modules/core/src/artifact/ArtifactsModeService.ts
  app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
  app/scripts/modules/core/src/artifact/imageSourceSelector.component.ts
  app/scripts/modules/core/src/artifact/index.ts
  app/scripts/modules/core/src/artifact/react/StageArtifactSelectorDelegate.tsx
  app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
  app/scripts/modules/core/src/pipeline/config/stages/stage.html
  app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
  app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/Triggers.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
  app/scripts/modules/core/src/pipeline/status/ParametersAndArtifacts.tsx
  app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
  app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/ManifestBindArtifactsSelectorDelegate.tsx
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceStage.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
Labels: ready to merge

#8098 fix(amazon,ecs,titus): Match targetGroup by name and account
  app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
  app/scripts/modules/amazon/src/instance/details/utils.ts
  app/scripts/modules/ecs/src/instance/details/instance.details.controller.js
  app/scripts/modules/titus/src/instance/details/instance.details.controller.js
Labels: ready to merge

#8099 fix(core): fix NPE in getBaseOsDescription
  app/scripts/modules/core/src/pipeline/config/stages/bake/bakeStageChooseOs.component.ts
Labels: ready to merge

#8097 refactor(titus/serverGroupDetails): Move details field to core and use that in titus
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/serverGroup/configure/common/index.ts
  app/scripts/modules/core/src/serverGroup/configure/common/wizard/fields/ServerGroupDetailsField.tsx
  app/scripts/modules/core/src/serverGroup/configure/common/wizard/fields/index.ts
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
Labels: ready to merge

#8102 fix(titus): Solidify mapping of titus to awsAccount
  app/scripts/modules/titus/src/securityGroup/securityGroup.read.service.js
  app/scripts/modules/titus/src/serverGroup/serverGroup.transformer.js
Labels: ready to merge

#8103 chore(bump): Bump core to 0.0.467
  app/scripts/modules/core/package.json
Labels: ready to merge

#8104 chore(bump): Bump amazon to 0.0.248
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#8105 chore(bump): Bump titus to 0.0.133
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8106 chore(core): remove versionedProviders flag
  app/scripts/modules/core/src/cloudProvider/skin.service.ts
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
  app/scripts/modules/core/src/pipeline/config/stages/savePipelines/savePipelinesStage.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestStage.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestStage.ts
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestStage.ts
  halconfig/settings.js
  settings.js
Labels: ready to merge

#7908 feat(pubsub): Add amazon as pubsubProvider
  halconfig/settings.js
Labels: ready to merge

#8109 chore(pluginsdk): upgrade transitive dependencies
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#8108 chore(eslint-plugin): Update peerDependencies to latest versions
  packages/eslint-plugin/package.json
  packages/eslint-plugin/yarn.lock
Labels: ready to merge, self merge

#8100 refactor(amazon/details): Use details field from core and remove amazon-specific implementation
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/fields/ServerGroupDetailsField.tsx
Labels: ready to merge

#8110 chore(package): upgrade eslint-plugin to 1.0.7
  package.json
  yarn.lock
Labels: ready to merge, self merge

#8107 feat(core/managed): add read-only stateful constraint support
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/NoticeCard.module.css
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
  app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx
Labels: ready to merge

#8113 chore(package): publish amazon 0.0.249 core 0.0.468 ecs 0.0.254 google 0.0.12 kubernetes 0.0.36
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/kubernetes/package.json
Labels: ready to merge

#8115 feat(core/managed): Deep link resources to their infrastructure view
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/ObjectRow.module.css
  app/scripts/modules/core/src/managed/ObjectRow.tsx
Labels: ready to merge
