Repository spinnaker/deck, pull requests merged in 2020-07, with the labels that each got.

#8392 fix(core/presentation): protect against width overflow on Modal + StandardGridTableLayout
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
  app/scripts/modules/core/src/presentation/modal/Modal.module.css
  app/scripts/modules/core/src/presentation/modal/Modal.tsx
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx
Labels: ready to merge

#8395 feat(bakeManifest): can override bakemanifestdetails
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestDetailsTab.tsx
Labels: ready to merge

#8394 feat(gce): add support multi instance family type for custom instances,
  app/scripts/modules/google/src/instance/custom/customInstance.filter.js
  app/scripts/modules/google/src/instance/custom/customInstanceBuilder.gce.service.js
  app/scripts/modules/google/src/instance/gceInstanceType.service.js
  app/scripts/modules/google/src/instance/gceInstanceTypeDisks.ts
  app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
  app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
  app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
  app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/CustomInstanceConfigurer.tsx
  app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
  app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceConfigurer.component.ts
Labels: ready to merge

#8393 chore(core): improvement docker build
  .dockerignore
  Dockerfile.slim
  Dockerfile.ubuntu
Labels: ready to merge

#8239 feat(core): Integrated v1 Layout
  app/scripts/modules/core/src/application/ApplicationComponent.tsx
  app/scripts/modules/core/src/application/application.less
  app/scripts/modules/core/src/application/config/applicationConfig.view.html
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.spec.tsx
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
  app/scripts/modules/core/src/application/nav/NavItem.spec.tsx
  app/scripts/modules/core/src/application/nav/NavItem.tsx
  app/scripts/modules/core/src/application/nav/verticalNav.less
  app/scripts/modules/core/src/cluster/filter/ClusterFilters.tsx
  app/scripts/modules/core/src/cluster/filter/FilterSearch.less
  app/scripts/modules/core/src/cluster/filter/FilterSearch.tsx
  app/scripts/modules/core/src/cluster/filter/FilterSection.tsx
  app/scripts/modules/core/src/cluster/filter/filterSearch.component.ts
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/entityTag/notifications/DataSourceNotifications.tsx
  app/scripts/modules/core/src/entityTag/notifications/notifications.popover.less
  app/scripts/modules/core/src/filterModel/FilterCollapse.less
  app/scripts/modules/core/src/filterModel/FilterCollapse.tsx
  app/scripts/modules/core/src/function/filter/FunctionFilters.tsx
  app/scripts/modules/core/src/header/SpinnakerHeader.css
  app/scripts/modules/core/src/header/SpinnakerHeader.tsx
  app/scripts/modules/core/src/insight/InsightLayout.tsx
  app/scripts/modules/core/src/insight/insight.less
  app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilters.tsx
  app/scripts/modules/core/src/modal/modals.less
  app/scripts/modules/core/src/navigation/navigation.less
  app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
  app/scripts/modules/core/src/pipeline/executions/Executions.tsx
  app/scripts/modules/core/src/pipeline/executions/executions.less
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
  app/scripts/modules/core/src/pipeline/filter/executionFilters.less
  app/scripts/modules/core/src/presentation/details.less
  app/scripts/modules/core/src/presentation/main.less
  app/scripts/modules/core/src/presentation/navigation/pageNavigation.less
  app/scripts/modules/core/src/presentation/navigation/pageNavigator.component.ts
  app/scripts/modules/core/src/presentation/navigation/pageSection.component.ts
  app/scripts/modules/core/src/projects/project.less
  app/scripts/modules/core/src/search/global/globalSearch.less
  app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilters.tsx
  app/scripts/modules/core/src/task/tasks.html
  app/scripts/modules/core/src/task/tasks.less
  app/scripts/modules/core/src/widgets/notifier/notifier.component.less
  test/functional/cypress/integration/core/manual_execution.spec.js
Labels: Do Not Merge

#8402 chore(package): publish core 0.0.487
  app/scripts/modules/core/package.json
Labels: ready to merge

#8405 chore(package): publish core 0.0.488
  app/scripts/modules/core/package.json
Labels: ready to merge

#8406 feat(plugins): Add a basic UI for the plugin trigger
  app/scripts/modules/core/src/pipeline/config/triggers/index.ts
  app/scripts/modules/core/src/pipeline/config/triggers/plugin/PluginTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/plugin/plugin.trigger.ts
  settings.js
Labels: ready to merge

#8410 chore(package): publish core 0.0.490
  app/scripts/modules/core/package.json
Labels: ready to merge

#8417 chore(pluginsdk): release 0.0.19
  packages/pluginsdk/package.json
Labels: ready to merge, self merge

#8419 fix(project dashboard) columns not overlapping
  app/scripts/modules/core/src/projects/dashboard/dashboard.html
  app/scripts/modules/core/src/projects/dashboard/dashboard.less
Labels: ready to rebase

#8421 config(pipeline/executions): Increase executions per pipeline options
  app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Labels: ready to rebase

#8416 fix(amazon): Instance details is not displayed
  app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
Labels: ready to merge

#8424 feat(core): refactor insight menu from dropdown to buttons
  app/scripts/modules/core/src/insight/InsightMenu.spec.tsx
  app/scripts/modules/core/src/insight/InsightMenu.tsx
  app/scripts/modules/core/src/projects/projects.controller.js
  app/scripts/modules/core/src/projects/projects.html
  app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
  app/scripts/modules/core/src/search/infrastructure/infrastructure.html
  test/functional/cypress/integration/core/create_application.js
Labels: ready to merge

#8427 fix(bake): show advanced options
  app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
  app/scripts/modules/azure/src/pipeline/stages/bake/bakeStage.html
Labels: ready to merge

#8433 chore(gradle): upgrade spinnaker gradle plugin
  gradle.properties
Labels: ready to merge

#8434 fix(titus): Make iamProfile a required field in the UI and offer to fill in the default value if it's missing.
  app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
  app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
Labels: ready to merge

#8435 fix(tooltips): Fixes instance tooltips (which jquery 3.5.0 broke)
  package.json
  yarn.lock
Labels: ready to merge

#8436 fix(safari): Do not store securityGroups cache in local storage, use memory instead
  app/scripts/modules/core/src/cache/deckCacheFactory.ts
  app/scripts/modules/core/src/cache/infrastructureCacheConfig.ts
Labels: ready to merge

#8438 refactor(kubernetes): exclude manifest from infrastructure interfaces
  app/scripts/modules/kubernetes/src/instance/details/IKubernetesInstance.ts
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
  app/scripts/modules/kubernetes/src/instance/details/details.html
  app/scripts/modules/kubernetes/src/loadBalancer/details/IKubernetesLoadBalancer.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.controller.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.html
  app/scripts/modules/kubernetes/src/manifest/annotationCustomSections.component.ts
  app/scripts/modules/kubernetes/src/manifest/traffic/ManifestTrafficService.spec.ts
  app/scripts/modules/kubernetes/src/manifest/traffic/ManifestTrafficService.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/IKubernetesSecurityGroup.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/details.html
  app/scripts/modules/kubernetes/src/serverGroup/details/IKubernetesServerGroup.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.html
  app/scripts/modules/kubernetes/src/serverGroupManager/IKubernetesServerGroupManager.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html
Labels: ready to merge

#8442 fix(core/nav): Apply new class to Page App Owner
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
Labels: ready to merge

#8448 chore(package): publish core 0.0.496
  app/scripts/modules/core/package.json
Labels: ready to merge, self merge

#8449 style(appengine): Fix typo in Server Group settings
  app/scripts/modules/appengine/src/serverGroup/configure/wizard/advancedSettings.html
Labels: ready to merge

#8450 refactor(kubernetes): clean up infrastructure interfaces
  app/scripts/modules/core/src/cluster/cluster.service.ts
  app/scripts/modules/core/src/domain/IServerGroup.ts
  app/scripts/modules/core/src/domain/IServerGroupManager.ts
  app/scripts/modules/core/src/entityTag/clusterTargetBuilder.ts
  app/scripts/modules/kubernetes/src/instance/details/IKubernetesInstance.ts
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
  app/scripts/modules/kubernetes/src/instance/index.ts
  app/scripts/modules/kubernetes/src/interfaces/index.ts
  app/scripts/modules/kubernetes/src/interfaces/infrastructure.types.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/IKubernetesLoadBalancer.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.controller.ts
  app/scripts/modules/kubernetes/src/loadBalancer/index.ts
  app/scripts/modules/kubernetes/src/loadBalancer/transformer.ts
  app/scripts/modules/kubernetes/src/manifest/rollout/RollingRestart.tsx
  app/scripts/modules/kubernetes/src/manifest/traffic/ManifestTrafficService.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/IKubernetesSecurityGroup.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/securityGroup/index.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/IKubernetesServerGroup.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/resize/resize.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/index.ts
  app/scripts/modules/kubernetes/src/serverGroup/serverGroupTransformer.service.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/IKubernetesServerGroupManager.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/index.ts
Labels: ready to merge

#8451 fix(amazon/rollback): Wait 500 ms before opening a second modal
  app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
Labels: ready to merge

#8437 refactor(instance): Migrate the instance chiclet tooltip from raw bootstrap to Tooltip component
  app/scripts/modules/core/src/instance/Instance.tsx
Labels: ready to merge

#8452 refactor(kubernetes): do not augment infrastructure data with manifes…
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.controller.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.controller.ts
Labels: ready to merge

#8453 fix(core/config): Make app config account dropdowns wider
  app/scripts/modules/core/src/account/AccountSelectInput.tsx
  app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.html
  app/scripts/modules/core/src/chaosMonkey/chaosMonkeyExceptions.component.html
Labels: ready to merge

#8456 fix(core/projects): fix layout for projects view
  app/scripts/modules/core/src/projects/ProjectHeader.tsx
Labels: ready to merge

#8457 chore(package): publish amazon 0.0.260 appengine 0.0.14 core 0.0.497 kubernetes 0.0.44 titus 0.0.139
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge, self merge
