Repository spinnaker/deck, pull requests merged in 2020-02, with the labels that each got.

#7826 feat(k8s): ManifestStatus can now be overridden
  app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/manifestStatus/ManifestStatus.tsx
Labels: ready to merge

#7798 feat(codebuild): Add AWS CodeBuild Stage
  app/scripts/modules/core/src/ci/igor.service.ts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildValidator.ts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/awsCodeBuildStage.ts
  app/scripts/modules/core/src/pipeline/pipeline.module.ts
Labels: ready to merge

#7834 chore(builds): Adds GHActions as CI job (PRs, master, release branches
  .github/workflows/ci.yml
  karma.conf.js
Labels: auto merged, ready to merge

#7831 feat(travis): Enable Travis stage as an artifact producer
  app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.ts
Labels: auto merged, ready to merge

#7829 fix(core): Re-exporting types from ExecutionMarkerIcon to make it available outside core
  app/scripts/modules/core/src/index.ts
Labels: auto merged, ready to merge

#7816 fix(core/confirmationModal): Supply the 'source' location when canceling
  app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
  app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx
  app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts
Labels: auto merged, ready to merge

#7833 feat(readme): add UI SIG link to README
  README.adoc
Labels: auto merged, ready to merge

#7841 fix(app engine logo): Use the new hexagon-free App Engine logo
  app/scripts/modules/appengine/src/appengine.module.ts
  app/scripts/modules/appengine/src/logo/appengine.logo.png
  app/scripts/modules/appengine/src/logo/appengine.logo.svg
Labels: ready to merge

#7837 fix(ecs): enable filtering on container image and target group
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
Labels: ready to merge

#7830 fix(amazon): parse healthCheckPort as integer before using it
  app/scripts/modules/amazon/src/instance/details/utils.ts
Labels: auto merged, ready to merge

#7840 chore(eslint): Add license to eslint-plugin package.json
  packages/eslint-plugin/package.json
Labels: auto merged, ready to merge

#7839 chore(gha): Build all npm packages in CI
  .github/workflows/ci.yml
  app/scripts/modules/assert_package_bumps_standalone.sh
  app/scripts/modules/build_modules.sh
  app/scripts/modules/build_order.sh
  karma.conf.js
Labels: auto merged, ready to merge

#7844 chore(package): bump amazon to 233
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7843 chore(package): bump core to 445
  app/scripts/modules/core/package.json
Labels: ready to merge

#7845 refactor(bash): Run our bash scripts through bash linter and make recommended changes
  app/scripts/modules/assert_clean_master.sh
  app/scripts/modules/assert_package_bumps_standalone.sh
  app/scripts/modules/build_order.sh
  app/scripts/modules/github_actions_publish.sh
  app/scripts/modules/show_dirty_modules.sh
  app/scripts/modules/show_unpublished_commits.sh
Labels: auto merged, ready to merge

#7842 feat(plugins): Load plugins and plugin manifest from gate
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/index.ts
  app/scripts/modules/core/src/plugins/index.ts
  app/scripts/modules/core/src/plugins/plugin.module.ts
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
Labels: auto merged, ready to merge

#7850 fix(packages): Preserve webpackIgnore comments when bundling for npm packages
  app/scripts/modules/amazon/webpack.config.js
  app/scripts/modules/appengine/webpack.config.js
  app/scripts/modules/azure/webpack.config.js
  app/scripts/modules/cloudfoundry/webpack.config.js
  app/scripts/modules/core/webpack.config.js
  app/scripts/modules/docker/webpack.config.js
  app/scripts/modules/ecs/webpack.config.js
  app/scripts/modules/google/webpack.config.js
  app/scripts/modules/huaweicloud/webpack.config.js
  app/scripts/modules/kubernetes/webpack.config.js
  app/scripts/modules/titus/webpack.config.js
  webpack.config.js
Labels: ready to merge

#7857 Pull request not to master
  app/scripts/modules/assert_package_bumps_standalone.sh
Labels: ready to merge, self merge

#7860 feat(deck): show expression in check precondition execution details
  app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/CheckPreconditionsExecutionDetails.tsx
Labels: ready to merge

#7863 fix(purebump): Fix purebump detection script to not false positive
  app/scripts/modules/assert_package_bumps_standalone.sh
Labels: ready to merge, self merge

#7865 feat(travis): remove travis
  .travis.yml
Labels: ready to merge, self merge

#7859 chore(purebump): use SPINNAKERBOT_TOKEN in github actions to auto-approve pure bumps
  .github/workflows/approve_package_bumps.yml
Labels: ready to merge, self merge

#7870 chore: move readme badge from travis to github actions
  README.adoc
Labels: ready to merge, self merge

#7869 fix(ecs): add memory and cpu properties to container inputs
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
Labels: ready to merge

#7836 fix(core): Use "Authorization" header instead of query parameter to get changelog (what's new) from gist
  app/scripts/modules/core/src/whatsNew/WhatsNewReader.ts
  settings.js
Labels: ready to merge

#7875 fix(purebump): Use double quotes to pass "ready to merge" label to action
  .github/workflows/approve_package_bumps.yml
Labels: ready to merge, self merge

#7878 chore(actions): 1.18.x release branch needs ci workflow definition.
  .github/workflows/ci.yml
  app/scripts/modules/build_modules.sh
Labels: ready to merge

#7881 fix(core/presentation): allow 0 in NumberInput.tsx
  app/scripts/modules/core/src/presentation/forms/inputs/NumberInput.tsx
Labels: ready to merge

#7861 feat(codebuild): Add more options to AWS CodeBuild stage
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildValidator.ts
Labels: ready to merge

#7882 feat(codebuild): Allow AWS CodeBuild stage to produce artifacts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/awsCodeBuildStage.ts
Labels: ready to merge

#7884 fix(aws): Fix to set right state while cloning security group
  app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js
Labels: ready to merge

#7886 chore(amazon): Bump amazon to 0.0.237
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7888 chore(bump): Bump amazon to v.238
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7880 Revert "chore(actions): 1.18.x release branch needs ci workflow definition."
  .github/workflows/ci.yml
  app/scripts/modules/build_modules.sh
Labels: ready to merge

#7835 Update ui-router libraries
  app/scripts/modules/core/src/instance/Instances.tsx
  package.json
  yarn.lock
Labels: ready to merge

#7892 feat(codebuild): Add support for overriding image and buildspec
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
Labels: ready to merge

#7897 fix(amazon): Preserve policyNames in CLB descriptions
  app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
  app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
Labels: ready to merge

#7895 Update eslint-plugin
  package.json
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/none.config.js
  packages/eslint-plugin/package.json
  yarn.lock
Labels: ready to merge

#7904 fix(core/account): AccountSelectInput pass 'name' in synthetic event
  app/scripts/modules/core/src/account/AccountSelectInput.tsx
Labels: ready to merge, self merge

#7868 feat(plugins): Prefer plugins from deck manifest (over gate) if they have the same ID
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
Labels: ready to merge, self merge

#7891 fix(core/securityGroups): Render view if managed resources can't be loaded
  app/scripts/modules/core/src/securityGroup/SecurityGroups.tsx
Labels: ready to merge

#7894 fix(amazon/loadBalancer): Fix the default dereg delay value in help text
  app/scripts/modules/amazon/src/help/amazon.help.ts
Labels: ready to merge

#7906 Readme
  README.adoc
  README.md
Labels: ready to merge

#7909 chore(buildtool): add an empty .gcloudignore file
  .gcloudignore
Labels: ready to merge

#7911 chore(amazon): Bump to 0.0.239
  app/scripts/modules/amazon/package.json
Labels: ready to merge, self merge

#7916 fix(titus): Fix resetting region when updated account is not in region
  app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
Labels: ready to merge

#7901 feat(core/presentation): add experimental useIsMobile hook
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/useIsMobile.hook.ts
Labels: ready to merge

#7896 fix(docker): Fix handling Docker Image name with digest
  app/scripts/modules/docker/src/image/DockerImageUtils.spec.ts
  app/scripts/modules/docker/src/image/DockerImageUtils.ts
  app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx
Labels: ready to merge

#7912 feat(plugins): imperative initialization
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
Labels: ready to merge

#7917 feat(spel): default new pipelines to spel v4
  app/scripts/modules/core/src/domain/IPipeline.ts
  app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
Labels: ready to merge

#7913 fix(ecs): add memory and cpu to container inputs
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
Labels: cherry-pick

#7899 refactor(core): Prefix search result table components with 'Search'
  app/scripts/modules/core/src/application/applicationSearchResultType.tsx
  app/scripts/modules/core/src/cluster/clusterSearchResultType.tsx
  app/scripts/modules/core/src/instance/instanceSearchResultType.tsx
  app/scripts/modules/core/src/loadBalancer/loadBalancerSearchResultType.tsx
  app/scripts/modules/core/src/projects/projectSearchResultType.tsx
  app/scripts/modules/core/src/search/searchResult/Renderers.tsx
  app/scripts/modules/core/src/securityGroup/securityGroupSearchResultType.tsx
  app/scripts/modules/core/src/serverGroup/serverGroupSearchResultType.tsx
Labels: ready to merge

#7921 Eslint plugin release 1.0.4
  packages/eslint-plugin/package.json
Labels: ready to merge, self merge

#7922 fix(pipeline): Not 'Use default' should be empty string
  app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js
Labels: ready to merge

#7919 chore(container builds): exclude large cache directories from GCB upload
  .gcloudignore
Labels: ready to merge

#7924 feat(helm): Add HELM3 as Render Engine in Bake Manifest Stage
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManualExecutionBakeManifest.tsx
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
Labels: ready to merge

#7915 feat(codebuild): Add support for multiple sources
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildSourceList.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/IAwsCodeBuildSource.tsx
Labels: ready to merge

#7920 fix(managed-delivery): Avoid displaying unnecessary error box
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
Labels: ready to merge

#7923 feat(managed): Scaffolding environments route
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/index.ts
  app/scripts/modules/core/src/managed/managed.module.js
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#7927 fix(core): Letting angular know when the promises resolve
  app/scripts/modules/core/src/plugins/plugin.module.ts
Labels: ready to merge

#7926 feat(codebuild): List project names
  app/scripts/modules/core/src/ci/igor.service.ts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
Labels: ready to merge

#7929 chore(core): bump to 0.0.450
  app/scripts/modules/core/package.json
Labels: ready to merge

#7928 feat(core/presentation): add useDeepObjectDiff hook for easier memoization of objects
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/useDeepObjectDiff.hook.spec.tsx
  app/scripts/modules/core/src/presentation/hooks/useDeepObjectDiff.hook.ts
Labels: ready to merge

#7930 fix(managed-delivery): Yet another fix for rendering import delivery config errors
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
Labels: ready to merge

#7933 fix(core/pipeline): handle missing trigger fields in importDeliveryConfig stage
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
Labels: ready to merge

#7905 feat(plugins): Switch from /plugin-manifest.js to /plugin-manifest.json
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  plugin-manifest.js
  plugin-manifest.json
  webpack.config.js
Labels: ready to merge, self merge

#7943 Revert "feat(plugins): Switch from /plugin-manifest.js to /plugin-manifest.json"
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  plugin-manifest.js
  plugin-manifest.json
  webpack.config.js
Labels: ready to merge

#7944 fix(ci): require functional tests to pass
  .github/workflows/ci.yml
Labels: ready to merge

#7947 GithubActions: add description to Deck CI job
  .github/workflows/ci.yml
Labels: ready to merge

#7936 feat(core/presentation): add left-align class on vertical flex containers
  app/scripts/modules/core/src/presentation/flex-layout.less
Labels: ready to merge

#7952 refactor(core/account): In AccountSelectInput, delegate to SelectInput and ReactSelectInput
  app/scripts/modules/core/src/account/AccountSelectInput.tsx
  app/scripts/modules/core/src/presentation/forms/inputs/SelectInput.tsx
  app/scripts/modules/core/src/slack/SlackReader.spec.ts
Labels: ready to merge

#7937 fix(core/modal): display: flex on body, remove outline on close button
  app/scripts/modules/core/src/presentation/modal/ModalBody.module.css
  app/scripts/modules/core/src/presentation/modal/ModalHeader.module.css
Labels: ready to merge

#7954 refactor(core/region): RegionSelectInput: delegate to SelectInput
  app/scripts/modules/core/src/region/RegionSelectInput.tsx
Labels: ready to merge

#7953 fix(core/presentation): Fix controlled/uncontrolled warning for number input
  app/scripts/modules/core/src/presentation/forms/inputs/NumberInput.tsx
  app/scripts/modules/core/src/presentation/forms/inputs/utils.ts
Labels: ready to merge

#7951 fix(aws): Support security group ip range rule description
  app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
Labels: ready to merge

#7955 chore(package): bump core to 0.0.451
  app/scripts/modules/core/package.json
Labels: ready to merge

#7948 feat(codebuild): Add help text to CodeBuild stage
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
Labels: ready to merge

#7956 fix(core/account): use relative import for IFormInputProps interface
  app/scripts/modules/core/src/account/AccountSelectInput.tsx
Labels: ready to merge

#7958 chore(core): bump to 0.0.452
  app/scripts/modules/core/package.json
Labels: ready to merge

#7949 fix(ecs): use preferSourceCapacity instead of useSourceCapacity when configuring a serverGroup
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
Labels: ready to merge

#7957 chore(fonts): update icomoon font files
  app/fonts/spinnaker/fonts/icomoon.svg
  app/fonts/spinnaker/fonts/icomoon.ttf
  app/fonts/spinnaker/fonts/icomoon.woff
  app/fonts/spinnaker/fonts/icomoon.woff2
  app/fonts/spinnaker/icons.css
  app/fonts/spinnaker/selection.json
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx
Labels: ready to merge

#7960 fix(core/managed): add even more message fields on history events
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#7961 fix(core/managed): remove arrow visual treatment on history modal
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.less
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#7963 chore(core): bump to 0.0.453
  app/scripts/modules/core/package.json
Labels: ready to merge

#7950 feat(plugins): Switch from /plugin-manifest.js to /plugin-manifest.json
  app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
  app/scripts/modules/core/src/plugins/plugin.registry.ts
  plugin-manifest.js
  plugin-manifest.json
  webpack.config.js
Labels: ready to merge, self merge

#7932 fix(plugins): if gate doesn't have plugin-manifest.json, ignore the error
  app/scripts/modules/core/src/plugins/plugin.registry.ts
Labels: ready to merge

#7965 chore(webpack): only display --progress if we're in a TTY and not running in CI
  package.json
  webpack.config.js
Labels: ready to merge, self merge

#7966 fix(core/region): restore css classes on region select input
  app/scripts/modules/core/src/region/RegionSelectInput.tsx
Labels: ready to merge, self merge

#7968 refactor(core/presentation): Switch the default value of formik fastField from true to false
  app/scripts/modules/amazon/src/function/configure/ExecutionRole.tsx
  app/scripts/modules/amazon/src/function/configure/FunctionBasicInformation.tsx
  app/scripts/modules/amazon/src/function/configure/FunctionEnvironmentVariables.tsx
  app/scripts/modules/amazon/src/function/configure/FunctionTags.tsx
  app/scripts/modules/amazon/src/function/configure/Network.tsx
  app/scripts/modules/amazon/src/loadBalancer/configure/classic/AdvancedSettings.tsx
  app/scripts/modules/cloudfoundry/src/presentation/forms/serverGroup/HealthCheck.tsx
  app/scripts/modules/cloudfoundry/src/presentation/forms/serverGroup/InstanceParameters.tsx
  app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/FormikAccountRegionClusterSelector.tsx
  app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/basicSettings/BasicSettings.cf.tsx
  app/scripts/modules/core/src/artifact/react/ExpectedArtifactModal.tsx
  app/scripts/modules/core/src/pipeline/config/copyStage/CopyStageModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesStageConfig.tsx
  app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/artifactory/ArtifactoryTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/nexus/NexusTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTrigger.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTrigger.tsx
  app/scripts/modules/core/src/pipeline/manualExecution/DryRun.tsx
  app/scripts/modules/core/src/pipeline/manualExecution/NotificationDetails.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.spec.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
  app/scripts/modules/google/src/serverGroup/details/stateful/UpdateBootImageButton.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/PolicyOptions.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/RateOptions.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/WindowPicker.tsx
  app/scripts/modules/titus/src/serverGroup/details/resize/TitusResizeServerGroupModal.tsx
Labels: ready to merge

#7970 fix(aws): Add description to IPRangeRule interface
  app/scripts/modules/amazon/src/securityGroup/details/IPRangeRules.tsx
Labels: ready to merge

#7973 chore(amazon): Bump to version 0.0.240
  app/scripts/modules/amazon/package.json
Labels: ready to merge

#7974 chore: bump core to 454
  app/scripts/modules/core/package.json
Labels: ready to merge

#7975 chore: bump docker to 53
  app/scripts/modules/docker/package.json
Labels: ready to merge

#7976 chore: bump titus to 129
  app/scripts/modules/titus/package.json
Labels: ready to merge

#7979 Chore: bump core to 455
  app/scripts/modules/core/package.json
Labels: ready to merge

#7942 feat(mocks): Move test mocks to their own npm package
  app/scripts/modules/amazon/src/subnet/SubnetSelectInput.spec.tsx
  package.json
  packages/mocks/package.json
  packages/mocks/src/index.ts
  packages/mocks/src/mockCluster.ts
  packages/mocks/src/mockDataSourceConfig.ts
  packages/mocks/src/mockHealth.ts
  packages/mocks/src/mockInstance.ts
  packages/mocks/src/mockInstanceCounts.ts
  packages/mocks/src/mockLoadBalancer.ts
  packages/mocks/src/mockMoniker.ts
  packages/mocks/src/mockNotification.ts
  packages/mocks/src/mockPipeline.ts
  packages/mocks/src/mockSecurityGroup.ts
  packages/mocks/src/mockServerGroup.ts
  packages/mocks/src/mockStage.ts
  packages/mocks/src/mockSubnet.ts
  packages/mocks/src/mockTrigger.ts
  packages/mocks/tsconfig.json
  packages/mocks/yarn.lock
  packages/tsconfig.base.json
  yarn.lock
Labels: ready to merge

#7967 fix(core): Fix missing maxRemainingAsgs
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
  app/scripts/modules/core/src/deploymentStrategy/strategies/redblack/redblack.strategy.ts
Labels: ready to merge

#7959 feat(managed-delivery): Improve errors displayed from unparseable delivery configs
  app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
Labels: ready to merge

#7986 fix(core/presentation): properly contain sticky row headers on scroll
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx
Labels: ready to merge
