Repository spinnaker/deck, pull requests merged in 2020-08, with the labels that each got.

#8458 refactor(kubernetes): remove some unused code
  app/scripts/modules/core/src/manifest/IManifestSubscription.ts
  app/scripts/modules/core/src/manifest/ManifestService.ts
  app/scripts/modules/core/src/manifest/ManifestWriter.ts
  app/scripts/modules/core/src/manifest/index.ts
  app/scripts/modules/kubernetes/src/manifest/manifest.service.ts
Labels: ready to merge

#8455 fix(helm): Fix helm artifacts not updating name and vesions
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/HelmArtifactEditor.tsx
Labels: ready to merge

#8464 fix(kubernetes): Don't overwrite namespace on instance
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.html
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html
Labels: ready to merge

#8465 fix(core/help): fix Manual Judgment help text
  app/scripts/modules/core/src/help/help.contents.ts
Labels: ready to merge

#8466 refactor(kubernetes/pipelines): clean up ManifestStatus and DeployStatus components.
  app/scripts/modules/kubernetes/src/manifest/manifest.service.ts
  app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/DeployStatus.tsx
  app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/ManifestStatus.tsx
Labels: ready to merge

#8471 chore(package): publish amazon 0.0.261 core 0.0.498 kubernetes 0.0.45
  app/scripts/modules/amazon/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/kubernetes/package.json
Labels: ready to merge

#8472 fix(functions): available lambda runtimes not up to date
  app/scripts/modules/amazon/src/function/configure/FunctionBasicInformation.tsx
Labels: ready to merge

#8474 fix(core/presentation): Do not render the form input even once ...
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.spec.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
Labels: ready to merge

#8441 config(auth): update default value of authEnabled
  settings.js
Labels: ready to merge

#8397 feat(gce): Add GCP internal http(s) load balancer.
  app/scripts/modules/google/src/domain/loadBalancer.ts
  app/scripts/modules/google/src/gce.module.ts
  app/scripts/modules/google/src/gceNetworkSelectField.directive.js
  app/scripts/modules/google/src/healthCheck/healthCheck.read.service.ts
  app/scripts/modules/google/src/help/gce.help.ts
  app/scripts/modules/google/src/loadBalancer/configure/choice/loadBalancerTypeToWizardMap.constant.ts
  app/scripts/modules/google/src/loadBalancer/configure/common/sessionAffinityNameMaps.ts
  app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.html
  app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.js
  app/scripts/modules/google/src/loadBalancer/configure/http/basicSettings/basicSettings.component.html
  app/scripts/modules/google/src/loadBalancer/configure/http/commandBuilder.service.js
  app/scripts/modules/google/src/loadBalancer/configure/http/httpLoadBalancer.write.service.js
  app/scripts/modules/google/src/loadBalancer/configure/http/listeners/listener.component.html
  app/scripts/modules/google/src/loadBalancer/configure/http/listeners/listener.component.js
  app/scripts/modules/google/src/loadBalancer/configure/http/transformer.service.js
  app/scripts/modules/google/src/loadBalancer/configure/internalhttp/createInternalHttpLoadBalancer.controller.ts
  app/scripts/modules/google/src/loadBalancer/details/loadBalancerDetail.controller.js
  app/scripts/modules/google/src/loadBalancer/details/loadBalancerDetails.html
  app/scripts/modules/google/src/loadBalancer/httpLoadBalancerUtils.service.ts
  app/scripts/modules/google/src/loadBalancer/loadBalancer.setTransformer.ts
  app/scripts/modules/google/src/networkSelectField.directive.html
  app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
  app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.js
Labels: ready to merge

#8480 fix(docker/tag): Make help content explicit for tag field by placing it below the field.
  app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
Labels: ready to rebase

#8468 fix(aws/functions): normalizeFunction is synchronous
  app/scripts/modules/core/src/function/function.read.service.spec.ts
  app/scripts/modules/core/src/function/function.read.service.ts
  app/scripts/modules/core/src/function/function.transformer.ts
Labels: backport-candidate, ready to merge

#8478 feat(core/managed): new visual iteration for version sidebar, 'decommissioned' cards
  app/scripts/modules/core/src/managed/ArtifactRow.module.css
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/StatusBubble.less
  app/scripts/modules/core/src/managed/StatusBubble.tsx
  app/scripts/modules/core/src/managed/StatusCard.less
  app/scripts/modules/core/src/managed/StatusCard.tsx
  app/scripts/modules/core/src/managed/VersionStateCard.tsx
Labels: ready to merge

#8479 feat(core/managed): new visual treatment for environment badges
  app/scripts/modules/core/src/managed/EnvironmentBadge.less
  app/scripts/modules/core/src/managed/EnvironmentBadge.tsx
  app/scripts/modules/core/src/managed/EnvironmentRow.less
  app/scripts/modules/core/src/managed/EnvironmentRow.tsx
  app/scripts/modules/core/src/managed/icons/star.svg
Labels: ready to merge

#8482 chore(package): publish core 0.0.500 docker 0.0.58 google 0.0.17
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/google/package.json
Labels: ready to merge

#8483 chore(messages): Replace the word "previous" with "prerequisite" in depends-on constraint text
  app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx
Labels: ready to merge

#8485 fix(core/managed): supply references when updating constraints
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ManagedWriter.ts
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
Labels: ready to merge

#8486 fix(kubernetes): add nullable createdTime to base resource interface
  app/scripts/modules/kubernetes/src/interfaces/infrastructure.types.ts
Labels: ready to merge

#8487 fix(kubernetes): do not self-close element in angular template
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html
Labels: ready to merge

#8489 chore(package): publish core 0.0.501 kubernetes 0.0.46
  app/scripts/modules/core/package.json
  app/scripts/modules/kubernetes/package.json
Labels: ready to merge

#8491 fix(core/widgets): Remove CustomDropdown widget
  app/scripts/modules/core/src/widgets/CustomDropdown.tsx
  app/scripts/modules/core/src/widgets/index.ts
Labels: ready to rebase

#8493 fix(google): do not self-close react2Angular-created elements
  app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
  app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts
  app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
  app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html
Labels: ready to merge

#8494 chore(dockerfile): replace deprecated MAINTAINER with LABEL
  Dockerfile.compile
  Dockerfile.slim
  Dockerfile.ubuntu
Labels: ready to merge

#8495 feat(google): add predictive autoscaling support
  app/scripts/modules/google/src/autoscalingPolicy/GceAutoScalingFieldLayout.tsx
  app/scripts/modules/google/src/autoscalingPolicy/IGceAutoscalingPolicy.ts
  app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/GcePredictiveAutoscaling.tsx
  app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.html
  app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.js
  app/scripts/modules/google/src/autoscalingPolicy/gceAutoscalingFieldLayout.less
  app/scripts/modules/google/src/autoscalingPolicy/index.ts
  app/scripts/modules/google/src/gce.module.ts
  app/scripts/modules/google/src/gce.settings.ts
  app/scripts/modules/google/src/help/gce.help.ts
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.js
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceScaleInControls.tsx
  app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/upsertAutoscalingPolicy.modal.html
Labels: ready to merge

#8499 perf(kubernetes): Load manifest and instance details in parallel
  app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
Labels: ready to merge

#8500 perf(kubernetes): Send server group and firewall requests in parallel
  app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts
Labels: ready to merge

#8502 fix(ecs): update z-index for uibModal
  app/scripts/modules/core/src/cluster/allClusters.controller.js
  app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
  app/scripts/modules/core/src/presentation/main.less
  app/scripts/modules/ecs/src/serverGroup/details/serverGroupDetails.ecs.controller.js
  app/scripts/modules/ecs/src/serverGroup/events/events.component.ts
Labels: ready to merge

#8492 fix(RunJobStage): Make RunJobStage restartable
  app/scripts/modules/core/src/pipeline/config/stages/runJob/runJobStage.js
Labels: ready to merge

#8508 fix(RunJobStage): Add restartability to Kubernetes RunJobStage
  app/scripts/modules/kubernetes/src/pipelines/stages/runJob/runJobStage.ts
Labels: ready to merge

#8510 chore(package): publish core 0.0.502 ecs 0.0.260 google 0.0.18 kubernetes 0.0.47
  app/scripts/modules/core/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/kubernetes/package.json
Labels: self merge

#8501 feature(UI): Add support for displaying colors in console outputs
  app/scripts/modules/core/src/instance/InstanceReader.ts
  app/scripts/modules/core/src/manifest/stage/JobManifestPodLogs.tsx
  app/scripts/modules/core/src/modal/modals.less
  package.json
  yarn.lock
Labels: ready to merge

#8515 feat(oracle): Reinstate oracle module
  app/scripts/app.ts
Labels: ready to merge

#8507 fix(gitRepoArtifact): move subpath value to location field.
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitrepo/GitRepoArtifactEditor.tsx
Labels: ready to merge

#8420 feat(tencentcloud pipeline): add disableCluster, disableServerGroup, …
  app/scripts/modules/tencentcloud/src/pipeline/stages/disableCluster/DisableClusterConfig.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/disableCluster/DisableClusterStageForm.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/disableCluster/disableClusterStage.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/disableCluster/disableClusterValidators.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/rollbackCluster/RollbackClusterConfig.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/rollbackCluster/RollbackClusterStageForm.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/rollbackCluster/rollbackClusterStage.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/rollbackCluster/rollbackClusterValidators.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/scaleDownCluster/ScaleDownClusterConfig.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/scaleDownCluster/ScaleDownClusterStageForm.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/scaleDownCluster/scaleDownClusterStage.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/scaleDownCluster/scaledownClusterValidators.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/shrinkCluster/ShrinkClusterConfig.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/shrinkCluster/ShrinkClusterStageForm.tsx
  app/scripts/modules/tencentcloud/src/pipeline/stages/shrinkCluster/shrinkClusterStage.ts
  app/scripts/modules/tencentcloud/src/pipeline/stages/shrinkCluster/shrinkClusterValidators.ts
  app/scripts/modules/tencentcloud/src/tencentcloud.module.ts
Labels: ready to merge

#8519 feat(core/managed): use displayName for resources in place of moniker
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/displayNames.ts
Labels: ready to merge

#8520 chore(package): publish amazon 0.0.263 appengine 0.0.15 azure 0.0.253 cloudfoundry 0.0.97 core 0.0.504 docker 0.0.59 ecs 0.0.261 google 0.0.19 huaweicloud 0.0.5 kubernetes 0.0.48 oracle 0.0.7 tencentcloud 0.0.4 titus 0.0.140
  app/scripts/modules/amazon/package.json
  app/scripts/modules/appengine/package.json
  app/scripts/modules/azure/package.json
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/core/package.json
  app/scripts/modules/docker/package.json
  app/scripts/modules/ecs/package.json
  app/scripts/modules/google/package.json
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/oracle/package.json
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/titus/package.json
Labels: ready to merge

#8522 fix(core/securityGroup): Add job type while updating security groups via infrastructure view
  app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts
Labels: ready to merge

#8521 feat(core/notifier): Make notifier service work with react components
  app/scripts/modules/core/src/application/service/InferredApplicationWarningService.tsx
  app/scripts/modules/core/src/config/VersionChecker.tsx
  app/scripts/modules/core/src/widgets/notifier/Notifier.tsx
  app/scripts/modules/core/src/widgets/notifier/notifier.service.ts
Labels: ready to merge

#8516 fix(appengine): fix rendering of StageArtifactSelector when artifacts are created
  app/scripts/modules/appengine/src/serverGroup/configure/wizard/ConfigFileArtifactList.tsx
  app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFileArtifactList.spec.tsx
  app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.ts
Labels: ready to merge

#8524 fix(amazon/firewall): Ensure we use a valid default vpc instead of none
  app/scripts/modules/amazon/src/securityGroup/configure/CreateSecurityGroup.controller.spec.js
  app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
Labels: ready to merge
