Repository spinnaker/deck, pull requests merged in 2020-11, with the labels that each got.

#8704 refactor(core): Remove componentWillUpdate and componentWillMount methods
  app/scripts/modules/amazon/src/function/details/FunctionActions.tsx
  app/scripts/modules/core/src/pagerDuty/Pager.tsx
  app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
Labels: ready to rebase

#8710 fix(amazon/securityGroup): Initialize accounts while cloning security groups
  app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js
Labels: ready to merge

#8711 fix(titus/pipeline): Set backingData before accessing it
  app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
Labels: ready to merge

#8709 feat(core/search): Make the search results dropdown wider
  app/scripts/modules/core/src/search/global/globalSearch.less
Labels: ready to merge

#8708 feat(core): Add Registry object to DebugWindow for easier debugging
  app/scripts/modules/core/src/registry/Registry.ts
Labels: ready to merge

#8707 fix(core/pipeline): Handle null restrictedExecutionWindow
  app/scripts/modules/core/src/pipeline/config/stages/executionWindows/ExecutionWindowActions.tsx
Labels: ready to merge

#8702 Fix new resource versions not showing up in environment view
  app/scripts/modules/core/src/managed/resources/registerNativeResourceKinds.ts
Labels: ready to merge

#8718 chore(eslint-plugin): publish 1.0.9
  packages/eslint-plugin/package.json
Labels: ready to merge, self merge

#8720 chore(pluginsdk-peerdeps): Publish 0.0.2
  packages/pluginsdk-peerdeps/package.json
Labels: ready to merge, self merge

#8722 Publish pluginsdk 0.0.23
  packages/pluginsdk/package.json
  packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
Labels: ready to merge, self merge

#8723 chore(package): core@0.0.527
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8725 chore(pluginsdk-peerdeps): Publish 0.0.3
  packages/pluginsdk-peerdeps/package.json
Labels: ready to merge, self merge

#8715 Pager feature in Spinnaker application navigation bar as an optional feature
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.spec.tsx
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
Labels: ready to merge

#8727 fix(amazon/targetGroups): Handle empty healthCheckPath
  app/scripts/modules/amazon/src/instance/details/utils.ts
  app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx
Labels: ready to merge

#8731 chore(package): core@0.0.530
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8732 fix(core/loadBalancer): Handle null healthCheckProtocol
  app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx
Labels: ready to merge

#8733 chore(package): core@0.0.531
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8462 feat(core/pipelines): Add execution breadcrumbs to the pipeline execution component
  app/scripts/modules/core/src/pipeline/executionBuild/ExecutionBuildLink.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionBreadcrumbs.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/execution.less
  app/scripts/modules/core/src/pipeline/executions/execution/executionInformation.service.ts
Labels: ready to merge

#8734 Titus target healthy percentage
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupCapacity.tsx
  app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
  app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
Labels: ready to merge

#8713 fix(config): Make running executions limit configurable
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/pipeline/service/execution.service.ts
Labels: ready to merge

#8737 fix(core): Initialize cache for executions permalink
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
Labels: ready to merge

#8738 feat(core/managed): fill some usage logging gaps in Environments
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/MarkArtifactAsBadModal.tsx
  app/scripts/modules/core/src/managed/PinArtifactModal.tsx
  app/scripts/modules/core/src/managed/UnpinArtifactModal.tsx
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
Labels: ready to merge

#8743 feat(bake): include git/repo artifacts in the list of artifacts to ch…
  app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
Labels: ready to merge

#8746 fix(titus): Fallback dimensions for target tracking policy
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
Labels: ready to merge

#8747 fix(titus): Disable edits of step scaling dimensions
  app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.html
  app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
  app/scripts/modules/titus/src/serverGroup/serverGroup.transformer.js
Labels: ready to merge

#8750 feat(core/managed): surface pre-deployment steps for versions
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/PreDeploymentRow.less
  app/scripts/modules/core/src/managed/PreDeploymentRow.tsx
  app/scripts/modules/core/src/managed/PreDeploymentStepCard.tsx
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/bake.svg
Labels: ready to merge

#8756 chore(package): core@0.0.534
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8764 fix(amazon/instanceDetails): Fix typo
  app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
  app/scripts/modules/titus/src/instance/details/instance.details.controller.js
Labels: ready to merge
