Repository spinnaker/deck, pull requests merged in 2021-02, with the labels that each got.

#8878 feat(ecs): Determine invalid capacity providers
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx
Labels: ready to merge

#8864 feat(cloudfoundry): support docker deployments on cloudfoundry
  app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings/ArtifactSettings.cf.tsx
Labels: ready to merge

#8889 feat(eslint): New eslint rule for ensuring import order
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/rules/import-sort.js
  packages/eslint-plugin/test/import-sort.spec.js
Labels: ready to rebase

#8897 refactor(md): organized MD files by folders
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ManagedResourceStatusPopover.tsx
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.less
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetailHeader.less
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetailHeader.tsx
  app/scripts/modules/core/src/managed/artifactDetail/MarkArtifactAsBadModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PinArtifactModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentRow.less
  app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentRow.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/UnpinArtifactModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/VersionStateCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/constraints/ConstraintCard.less
  app/scripts/modules/core/src/managed/artifactDetail/constraints/ConstraintCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/constraints/constraintRegistry.tsx
  app/scripts/modules/core/src/managed/artifactsList/ArtifactRow.less
  app/scripts/modules/core/src/managed/artifactsList/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/artifactsList/StatusBubbleStack.less
  app/scripts/modules/core/src/managed/artifactsList/StatusBubbleStack.tsx
  app/scripts/modules/core/src/managed/environment/EnvironmentRow.less
  app/scripts/modules/core/src/managed/environment/EnvironmentRow.tsx
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceDiffTable.tsx
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.less
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#8886 refactor(eslint): Lint rules to prevent presentation import from core
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/rules/import-from-presentation-not-core.js
  packages/eslint-plugin/test/import-from-presentation-not-core.spec.js
Labels: ready to rebase

#8888 fix(dev): load external source maps in development
  package.json
  webpack.config.js
  yarn.lock
Labels: ready to merge

#8892 refactor(core/ci): Migrate to builds api v3
  app/scripts/modules/core/src/ci/igor.service.ts
Labels: ready to merge, self merge

#8890 fix(CiBuild): Allow for empty SCM information when pulling builds
  app/scripts/modules/core/src/ci/CIReader.ts
Labels: ready to merge

#8904 fix(core/ci): Fix endpoint url typo in getJobConfig()
  app/scripts/modules/core/src/ci/igor.service.ts
Labels: ready to merge

#8905 chore(package): core@0.0.549
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8907 feat(presentation): mdVerification icon
  packages/presentation/src/icons/iconsByName.ts
  packages/presentation/src/icons/vectors/mdVerification.svg
Labels: ready to merge

#8908 chore(pre(presentation): publish 0.0.1
  packages/presentation/package.json
Labels: ready to merge, self merge

#8910 chore(pre(presentation): publish 0.0.2
  packages/presentation/package.json
Labels: ready to merge, self merge

#8915 chore(eslint-plugin): publish 1.0.11
  packages/eslint-plugin/package.json
Labels: ready to merge, self merge

#8914 Add spinnaker/presentation to pluginsdk-peerdeps
  packages/pluginsdk-peerdeps/package.json
Labels: ready to merge, self merge

#8917 bump pluginsdk dependencies and release 0.0.24
  packages/pluginsdk/package.json
  packages/pluginsdk/yarn.lock
Labels: ready to merge, self merge

#8887 feat(ecs): Determine invalid default capacity provider strategy
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx
Labels: ready to rebase

#8916 fix(core/serverGroup): Ensure failsafe SpEL expressions are provided
  app/scripts/modules/core/src/serverGroup/configure/common/ServerGroupNamePreview.tsx
Labels: ready to rebase

#8920 fix(lint): Handle non-import declaration nodes in import-sort rule
  packages/eslint-plugin/rules/import-sort.js
  packages/eslint-plugin/test/import-sort.spec.js
Labels: ready to rebase

#8921 feat(lint): Add prettier linter
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/yarn.lock
Labels: ready to rebase

#8922 refactor(core/md): split environment cards into multiple files
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/artifactDetail/EnvironmentCards.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PinnedCard.tsx
  app/scripts/modules/core/src/managed/utils/logging.ts
Labels: ready to merge

#8924 fix: broken link to renamed BlockDeviceConfig.groovy
  app/scripts/modules/amazon/src/help/amazon.help.ts
Labels: ready to merge

#8926 fix(gha): use full commit hash for actions
  .github/workflows/approve_package_bumps.yml
Labels: ready to merge

#8928 fix(core): Only forward to permalink on initial load
  app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Labels: ready to merge

#8929 chore(prettier): Format code using prettier
  app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
  app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/ScalingPolicyWriter.ts
  app/scripts/modules/amazon/src/vpc/VpcReader.ts
  app/scripts/modules/core/src/account/AccountTag.tsx
  app/scripts/modules/core/src/application/service/ApplicationWriter.ts
  app/scripts/modules/core/src/cancelModal/CancelModal.tsx
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.ts
  app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts
  app/scripts/modules/core/src/domain/ITask.ts
  app/scripts/modules/core/src/entityTag/entityTags.write.service.ts
  app/scripts/modules/core/src/function/function.write.service.ts
  app/scripts/modules/core/src/instance/details/instanceActions.component.ts
  app/scripts/modules/core/src/loadBalancer/loadBalancer.write.service.ts
  app/scripts/modules/core/src/loadBalancer/loadBalancerDataUtils.ts
  app/scripts/modules/core/src/manifest/ManifestWriter.ts
  app/scripts/modules/core/src/naming/nameUtils.ts
  app/scripts/modules/core/src/pagerDuty/pagerDuty.write.service.ts
  app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
  app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
  app/scripts/modules/core/src/pipeline/config/validation/PipelineConfigValidator.ts
  app/scripts/modules/core/src/projects/service/ProjectWriter.ts
  app/scripts/modules/core/src/retry/retry.service.ts
  app/scripts/modules/core/src/scheduler/SchedulerFactory.ts
  app/scripts/modules/core/src/securityGroup/SecurityGroupWriter.ts
  app/scripts/modules/core/src/snapshot/SnapshotWriter.ts
  app/scripts/modules/core/src/utils/retryablePromise.ts
  app/scripts/modules/ecs/src/ecs.module.ts
  app/scripts/modules/ecs/src/ecsCluster/IEcsCapacityProviderDetails.ts
  app/scripts/modules/ecs/src/ecsCluster/ecsCluster.read.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
  app/scripts/modules/google/src/loadBalancer/configure/common/commonLoadBalancerCommandBuilder.service.ts
  app/scripts/modules/kubernetes/src/manifest/traffic/ManifestTrafficService.ts
Labels: ready to rebase

#8749 fix(core): add dotted underline visual indicator to hover-able popovers
  app/scripts/modules/core/src/presentation/HoverablePopover.css
Labels: ready to merge

#8933 feat(lint): Handle local named imports while sorting imports
  packages/eslint-plugin/package.json
  packages/eslint-plugin/rules/import-sort.js
  packages/eslint-plugin/test/import-sort.spec.js
Labels: ready to rebase

#8927 fix(UI): Fixes hamburger menu icon alignment
  app/scripts/modules/core/src/header/SpinnakerHeader.css
Labels: ready to merge

#8940 chore(lint): Run lint before commit
  package.json
  yarn.lock
Labels: ready to rebase

#8938 fix(core): avoid fetching security groups twice
  app/scripts/modules/core/src/securityGroup/securityGroupReader.service.spec.ts
  app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
Labels: ready to merge

#8944 chore(eslint): fix some eslint rules violations in test code
  karma-shim.js
  test/helpers/customMatchers.ts
Labels: ready to merge, self merge

#8942 fix(core/presentation): Apply `flex: 1` to responsive table cell so the cell takes up the available width
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
Labels: ready to merge

#8947 chore(lint): Remove lint rule for prettier
  packages/eslint-plugin/base.config.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/yarn.lock
Labels: ready to rebase

#8950 fix(amazon/loadBalancer): Fix text for cross-zone load balancing
  app/scripts/modules/amazon/src/loadBalancer/configure/network/NLBAdvancedSettings.tsx
Labels: ready to rebase

#8943 chore: make sort-imports rule a warning, rather than an error
  packages/eslint-plugin/base.config.js
Labels: ready to merge

#8951 chore(lint): Upgrade @spinnaker/eslint-plugin
  package.json
  yarn.lock
Labels: ready to rebase

#8949 chore(md): Enable TS strict null check in MD (only in IDE)
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
  app/scripts/modules/core/src/managed/Button.tsx
  app/scripts/modules/core/src/managed/DeployingIntoManagedClusterWarning.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedMenuItem.tsx
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
  app/scripts/modules/core/src/managed/StatusCard.tsx
  app/scripts/modules/core/src/managed/ToggleManagedResourceForApplication.tsx
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetailHeader.tsx
  app/scripts/modules/core/src/managed/artifactDetail/EnvironmentCards.tsx
  app/scripts/modules/core/src/managed/artifactDetail/MarkArtifactAsBadModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PinArtifactModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PinnedCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/UnpinArtifactModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/VersionStateCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/constraints/constraintRegistry.tsx
  app/scripts/modules/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
  app/scripts/modules/core/src/managed/artifactsList/ArtifactsList.tsx
  app/scripts/modules/core/src/managed/environment/EnvironmentRow.tsx
  app/scripts/modules/core/src/managed/managedResourceDecorators.ts
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
  app/scripts/modules/core/src/managed/toggleResourceManagement.tsx
  app/scripts/modules/core/src/managed/tsconfig.json
Labels: ready to merge
