Repository spinnaker/deck, pull requests merged in 2021-08, with the labels that each got.

#9550 fix(md): text for BLOCKED status in allowed times constraint
  packages/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge, self merge

#9548 fix(md): the raw delivery config is not showing up properly. Hiding it for now
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge, self merge

#9541 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9554 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9560 fix(md): hide completed task status and progress bar if completed
  packages/core/src/managed/overview/ResourceTask.tsx
Labels: ready to merge, self merge

#9558 feat(md): an option to enable the auto import delivery config from git
  app/scripts/modules/app/src/settings.js
  packages/core/src/config/settings.ts
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/GitIntegration.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge

#9559 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9572 fix(lint): run yarn lint against packages/ and app/
  .eslintignore
  package.json
Labels: ready to merge, self merge

#9574 refactor(eslint-plugin): register ts-node in eslint-plugin.js
  packages/eslint-plugin/eslint-plugin.js
  packages/eslint-plugin/package.json
  yarn.lock
Labels: ready to merge, self merge

#9575 chore(lint): yarn lint --fix
  packages/core/src/application/config/dataSources/applicationDataSourceEditor.component.ts
  packages/core/src/config/VersionChecker.tsx
  packages/core/src/modal/wizard/WizardModal.tsx
  packages/core/src/overrideRegistry/Overridable.tsx
  packages/core/src/pipeline/config/actions/history/ShowPipelineHistoryModal.tsx
  packages/core/src/pipeline/config/pipelineConfig.module.js
  packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageConfig.tsx
  packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildValidator.ts
  packages/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSecondarySourceVersionModal.tsx
  packages/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
  packages/core/src/pipeline/config/stages/awsCodeBuild/awsCodeBuildStage.ts
  packages/core/src/pipeline/config/stages/bakeManifest/BakeManifestDetailsTab.tsx
  packages/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
  packages/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageConfig.tsx
  packages/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
  packages/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildStage.ts
  packages/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildValidators.ts
  packages/core/src/pipeline/config/stages/savePipelines/SavePipelinesStageConfig.tsx
  packages/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
  packages/core/src/pipeline/executions/execution/ExecutionMarkerInformationModal.tsx
  packages/core/src/search/searchResult/SearchResults.tsx
  packages/core/src/serverGroup/configure/common/wizard/fields/ServerGroupDetailsField.tsx
  packages/core/src/slack/SlackChannelSelector.tsx
  packages/core/src/snapshot/diff/snapshotDiff.modal.controller.js
  packages/core/src/utils/json/JsonUtils.ts
  packages/dcos/src/search/resultFormatter.js
  packages/mocks/src/amazon/mockAmazonBlockDeviceMapping.ts
  packages/mocks/src/amazon/mockAmazonLaunchTemplate.ts
  packages/mocks/src/amazon/mockAmazonServerGroup.ts
  packages/mocks/src/mockEntityTags.ts
  packages/mocks/src/mockLoadBalancer.ts
  packages/mocks/src/mockSecurityGroup.ts
  packages/oracle/src/pipeline/disableAsg/disableAsgStage.js
  packages/presentation/rollup.config.js
  packages/titus/src/serverGroup/details/TitusCapacityDetailsSection.tsx
  packages/titus/src/serverGroup/details/scalingActivity/TitusScalingActivitiesModal.tsx
Labels: ready to merge, self merge

#9569 chore(md): removed old ui code
  packages/core/src/application/config/managedResources/ManagedResourceConfig.tsx
  packages/core/src/managed/AbsoluteTimestamp.tsx
  packages/core/src/managed/ColumnHeader.less
  packages/core/src/managed/ColumnHeader.tsx
  packages/core/src/managed/EnvironmentBadge.less
  packages/core/src/managed/EnvironmentBadge.tsx
  packages/core/src/managed/Environments.less
  packages/core/src/managed/Environments.tsx
  packages/core/src/managed/Environments2.less
  packages/core/src/managed/Environments2.tsx
  packages/core/src/managed/EnvironmentsHeader.less
  packages/core/src/managed/EnvironmentsHeader.tsx
  packages/core/src/managed/EnvironmentsList.tsx
  packages/core/src/managed/ManagedReader.ts
  packages/core/src/managed/ManagedResourceObject.tsx
  packages/core/src/managed/ManagedWriter.ts
  packages/core/src/managed/StatusBubble.less
  packages/core/src/managed/StatusBubble.tsx
  packages/core/src/managed/StatusCard.less
  packages/core/src/managed/StatusCard.tsx
  packages/core/src/managed/ToggleManagedResourceForApplication.tsx
  packages/core/src/managed/artifactDetail/ArtifactDetail.less
  packages/core/src/managed/artifactDetail/ArtifactDetail.tsx
  packages/core/src/managed/artifactDetail/ArtifactDetailHeader.less
  packages/core/src/managed/artifactDetail/ArtifactDetailHeader.tsx
  packages/core/src/managed/artifactDetail/EnvironmentCards.tsx
  packages/core/src/managed/artifactDetail/MarkArtifactAsBadModal.tsx
  packages/core/src/managed/artifactDetail/PinArtifactModal.tsx
  packages/core/src/managed/artifactDetail/PinnedCard.tsx
  packages/core/src/managed/artifactDetail/PreDeploymentRow.less
  packages/core/src/managed/artifactDetail/PreDeploymentRow.tsx
  packages/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
  packages/core/src/managed/artifactDetail/UnpinArtifactModal.tsx
  packages/core/src/managed/artifactDetail/VersionStateCard.tsx
  packages/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
  packages/core/src/managed/artifactsList/ArtifactRow.less
  packages/core/src/managed/artifactsList/ArtifactsList.tsx
  packages/core/src/managed/artifactsList/StatusBubbleStack.less
  packages/core/src/managed/artifactsList/StatusBubbleStack.tsx
  packages/core/src/managed/constraints/ConstraintCard.less
  packages/core/src/managed/constraints/ConstraintCard.tsx
  packages/core/src/managed/environment/EnvironmentRow.less
  packages/core/src/managed/environment/EnvironmentRow.tsx
  packages/core/src/managed/managed.dataSource.ts
  packages/core/src/managed/managed.states.ts
  packages/core/src/managed/overview/artifact/ArtifactActionModal.tsx
  packages/core/src/managed/utils/ActionModal.tsx
  packages/core/src/managed/utils/Button.less
  packages/core/src/managed/utils/Button.tsx
  packages/core/src/managed/utils/sortEnvironments.spec.ts
  packages/core/src/managed/utils/sortEnvironments.ts
Labels: ready to merge, self merge

#9581 chore(core/pipeline/ExecutionStatus): Remove unused css classes: execution-info and .subheading Remove unused trigger-type class from markup
  packages/core/src/pipeline/status/ExecutionStatus.tsx
  packages/core/src/pipeline/status/executionStatus.less
Labels: ready to merge, self merge

#9583 fix(md): git integration improvements
  packages/core/src/managed/ManagedReader.ts
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/config/GitIntegration.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/messages/Messages.tsx
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge, self merge

#9571 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/presentation/CHANGELOG.md
  packages/presentation/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9586 style(md): small updates for the git integration styles
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/config/GitIntegration.less
  packages/core/src/managed/config/GitIntegration.tsx
  packages/core/src/presentation/forms/inputs/CheckboxInput.tsx
Labels: ready to merge, self merge

#9587 feat(md): updated preview environment titles to use the branch name, link to the PR, and show basedOn
  packages/core/src/managed/environmentBaseElements/BaseEnvironment.less
  packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/EnvironmentOverview.tsx
  packages/core/src/managed/overview/queries.graphql
  packages/core/src/managed/versionsHistory/VersionContent.tsx
  packages/core/src/managed/versionsHistory/VersionHeading.tsx
  packages/core/src/managed/versionsHistory/VersionsHistory.less
  packages/core/src/managed/versionsHistory/VersionsHistory.tsx
  packages/core/src/managed/versionsHistory/types.ts
Labels: ready to merge, self merge

#9589 feat(md): support max and actual deploys in allowed times constraint
  packages/core/src/domain/IManagedEntity.ts
  packages/core/src/managed/constraints/AllowedTimes.less
  packages/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge

#9590 chore(core): show "Deleting" when environment gets deleted
  packages/core/package.json
  packages/core/src/managed/environmentBaseElements/BaseEnvironment.less
  packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/overview/EnvironmentOverview.tsx
  packages/core/src/managed/overview/baseStyles.less
  packages/core/src/managed/overview/queries.graphql
  yarn.lock
Labels: ready to merge

#9591 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9594 feat(md): use isCurrent to identify the current version + show secondary status when needed (deploying/vetoed)
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/overview/artifact/Artifact.tsx
  packages/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  packages/core/src/managed/overview/artifact/CurrentVersion.tsx
  packages/core/src/managed/overview/queries.graphql
  packages/core/src/managed/versionsHistory/VersionContent.tsx
  packages/core/src/managed/versionsHistory/VersionHeading.tsx
  packages/core/src/managed/versionsHistory/VersionsHistory.less
  packages/core/src/managed/versionsHistory/VersionsHistory.tsx
Labels: ready to merge

#9595 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9600 fix(md): increased pinned icon size
  packages/core/src/managed/versionMetadata/MetadataComponents.tsx
Labels: ready to merge, self merge

#9602 remove postcss nested
  packages/app/package.json
  packages/core/src/fonts/icons.css
  packages/scripts/config/rollup.config.base.js
  packages/scripts/package.json
  postcss.config.js
  yarn.lock
Labels: ready to merge, self merge

#9598 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/presentation/CHANGELOG.md
  packages/presentation/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9606 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9620 feat(provider/azure): Allow empty load balancer for Azure scale sets
  packages/azure/src/loadBalancer/details/loadBalancerDetail.html
  packages/azure/src/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
  packages/azure/src/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.html
  packages/azure/src/serverGroup/configure/wizard/networkSettings/ServerGroupNetworkSettingsSelector.directive.html
Labels: ready to merge

#9621 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9626 fix(aws): Clarify compatible target groups
  packages/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
  packages/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
Labels: ready to merge

#9628 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish
