Repository spinnaker/deck, pull requests merged in 2021-06, with the labels that each got.

#9260 feat(md): improve styles on mobile
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/environmentBaseElements/BaseEnvironment.less
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.less
  app/scripts/modules/core/src/presentation/main.less
Labels: ready to merge

#9170 feat(kubernetes/job): Use mostRecentPodName from response
  app/scripts/modules/kubernetes/src/pipelines/stages/runJob/RunJobExecutionDetails.tsx
Labels: ready to merge

#9267 fix(presentation): center close icon
  packages/presentation/package.json
  packages/presentation/src/icons/vectors/closeSmall.svg
Labels: ready to merge

#9268 feat(md): version history collapsible icon - switch to arrow and cross icon
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
  package.json
  yarn.lock
Labels: ready to merge

#9276 style(md): add spacing above actions if there is a description
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
Labels: ready to merge, self merge

#9277 feat(md): show resource account in metadata
  app/scripts/modules/core/src/managed/overview/Resource.tsx
Labels: ready to merge, self merge

#9278 fix(md): only show git link if the commit message is not a link
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
Labels: ready to merge, self merge

#9280 fix(md): allowed time default timezone as PST
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge, self merge

#9281 feat(md): added logs to the important actions and events
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/config/Configuration.tsx
  app/scripts/modules/core/src/managed/overview/Resource.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  app/scripts/modules/core/src/managed/resources/ResourceTitle.tsx
  app/scripts/modules/core/src/managed/utils/ActionModal.tsx
  app/scripts/modules/core/src/managed/utils/logging.ts
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.tsx
Labels: ready to merge, self merge

#9279 feat(md): moved createdAt to the metadata instead of on the left
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
  app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.less
  app/scripts/modules/core/src/presentation/main.less
Labels: ready to merge, self merge

#9287 fix(md): properly redirect the old ui links to the new ui
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge, self merge

#9285 fix(nav): fix unsubscribe on unmount
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
Labels: ready to merge

#9269 feat(md): New option to display environments side by side
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/BaseEnvironment.less
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/managed/versionsHistory/types.ts
  app/scripts/modules/core/src/presentation/hooks/useDimensions.hook.ts
  app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.less
  app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.tsx
  package.json
  yarn.lock
Labels: ready to merge

#9288 chore(package): core@0.0.591
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9289 fix(md): minor improvements based on feedback from #9269
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
  app/scripts/modules/core/src/presentation/hooks/useDimensions.hook.ts
Labels: ready to merge

#9286 feat(md): show delivery config yml in the configuration tab
  app/scripts/modules/core/src/api/ApiService.ts
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/config/Configuration.tsx
  app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
  app/scripts/modules/core/src/managed/utils/logging.ts
Labels: ready to merge, self merge

#9290 feat(md): set the new UI as the default one, and allow users to opt out
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#9291 feat(md): change the deploying state blinking green instead of teal
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  package.json
  yarn.lock
Labels: ready to merge

#9294 chore(package): core@0.0.592
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9299 fix(scripts): Add path separator for scoped packages
  packages/scripts/helpers/rollup-node-auto-external-configurer.js
  packages/scripts/package.json
Labels: self merge

#9032 fix(ecs): Switch to securityGroupNames and update on subnet change in server group wizard
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/networking/Networking.tsx
Labels: ready to merge

#9300 feat(scripts): Add postcss colorfix processor
  packages/scripts/config/rollup.config.base.js
  packages/scripts/package.json
  packages/scripts/yarn.lock
Labels: self merge

#9303 feat(core): Add type definition for png files
  app/scripts/modules/core/src/types/index.d.ts
  app/scripts/modules/core/src/types/png.d.ts
Labels: self merge

#9302 feat(md): Preview environments v0
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/EnvironmentOverview.tsx
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/presentation/hooks/useDimensions.hook.ts
  graphql.schema.json
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9305 feat(md): added branch details to the history branch
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
Labels: ready to merge, self merge

#9307 feat(md): change url when expanding a version
  app/scripts/modules/core/src/managed/managed.states.ts
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
Labels: ready to merge

#9309 feat(core): navbar logging
  app/scripts/modules/core/src/header/SpinnakerHeader.tsx
Labels: ready to merge

#9310 feat(build): Add support for stripping during bundling
  packages/scripts/config/rollup.config.base.module.js
  packages/scripts/package.json
  packages/scripts/yarn.lock
Labels: self merge

#9312 chore(package): core@0.0.594
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9316 chore(package): core@0.0.595
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9317 chore(package-bump): Update core versions in amazon and docker
  app/scripts/modules/amazon/package.json
  app/scripts/modules/amazon/tsconfig.json
  app/scripts/modules/amazon/yarn.lock
  app/scripts/modules/docker/package.json
  app/scripts/modules/docker/tsconfig.json
  app/scripts/modules/docker/yarn.lock
Labels: self merge

#9320 chore(package): titus@0.0.184
  app/scripts/modules/titus/package.json
Labels: ready to rebase

#9322 chore(package): core@0.0.596
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9325 feat(md): log envs direction
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
Labels: ready to merge, self merge

#9107 fix(containerlogs): add ability to view multiple pod logs
  app/scripts/modules/core/src/manifest/stage/JobManifestPodLogs.tsx
  app/scripts/modules/core/src/manifest/stage/JobStageExecutionLogs.tsx
  app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
  app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/ManifestEvents.tsx
  app/scripts/modules/kubernetes/src/pipelines/stages/runJob/RunJobExecutionDetails.tsx
Labels: ready to merge

#9329 fix(core): Clearer execution details in ServerGroupStageContext
  app/scripts/modules/core/src/pipeline/config/stages/common/ServerGroupStageContext.tsx
  app/scripts/modules/core/src/pipeline/config/stages/disableCluster/DisableClusterExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/config/stages/scaleDownCluster/ScaleDownClusterExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/config/stages/shrinkCluster/ShrinkClusterExecutionDetails.tsx
Labels: ready to merge

#9293 feat(md): improve error handling for non-managed applications
  app/scripts/modules/core/src/managed/ApplicationQueryError.tsx
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/UnmanagedMessage.tsx
  app/scripts/modules/core/src/managed/config/Configuration.tsx
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
Labels: ready to merge, self merge

#9306 feat(md): set grid view as default and improve styles
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentItem.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
  app/scripts/modules/core/src/managed/overview/baseStyles.less
Labels: ready to merge, self merge

#9332 fix(md): constraint time position
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
Labels: ready to merge, self merge

#9337 chore(package): titus@0.0.186
  app/scripts/modules/titus/package.json
Labels: ready to rebase

#9338 fix(md): remove loadingIndicator.svg and use Spinner instead
  app/scripts/modules/core/src/managed/config/Configuration.tsx
  app/scripts/modules/core/src/managed/overview/Resource.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
  app/scripts/modules/core/src/managed/overview/loadingIndicator.svg
  app/scripts/modules/core/src/widgets/spinners/Spinner.tsx
Labels: ready to merge

#9339 feat(md): retry version actions (verifications and post deploy)
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.less
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/VersionOperation.tsx
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/overview/types.ts
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/widgets/notifier/notifier.service.ts
  graphql.schema.json
Labels: ready to merge, self merge

#9343 fix(md): improve error logging
  app/scripts/modules/core/src/managed/ApplicationQueryError.tsx
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/utils/logging.ts
  app/scripts/modules/core/src/utils/Logger.ts
Labels: ready to merge

#9351 chore(package): docker@0.0.81
  app/scripts/modules/docker/package.json
Labels: ready to rebase

#9352 fix(md): fix pin icon from cropping due to overflow-x: auto
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
Labels: ready to merge, self merge

#9355 feat(md): change allowed times fail message
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge, self merge

#9345 fix(logging): ignore noisy errors
  app/scripts/modules/core/src/utils/Logger.ts
Labels: ready to merge, self merge

#9357 fix(core/serverGroup): Add space in scaling activity details
  app/scripts/modules/core/src/serverGroup/details/scalingActivities/ScalingActivitiesModal.tsx
Labels: ready to rebase

#9360 fix(core): expose user menu
  app/scripts/modules/core/src/authentication/index.ts
Labels: ready to merge

#9365 fix(md): make allowed time attributes nullable
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge, self merge

#9367 chore(package): core@0.0.602
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9370 fix(md): css fix for no artifacts
  app/scripts/modules/core/src/managed/overview/baseStyles.less
Labels: ready to merge, self merge

#9356 feat(md): added links to resources
  app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/Resource.less
  app/scripts/modules/core/src/managed/overview/Resource.tsx
  app/scripts/modules/core/src/managed/overview/ResourceTask.tsx
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.less
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  app/scripts/modules/core/src/managed/overview/artifact/VersionOperation.tsx
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/presentation/LoadingAnimation.tsx
  app/scripts/modules/core/src/presentation/hooks/useDataWithRefresh.hook.ts
  app/scripts/modules/core/src/task/TaskProgressBar.tsx
  graphql.schema.json
Labels: ready to merge, self merge

#9366 feat(md): backend messages
  app/scripts/modules/core/src/managed/config/ManagementWarning.less
  app/scripts/modules/core/src/managed/config/ManagementWarning.tsx
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/messages/MessageBox.less
  app/scripts/modules/core/src/managed/messages/MessageBox.tsx
  app/scripts/modules/core/src/managed/messages/Messages.tsx
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  graphql.schema.json
Labels: ready to merge, self merge

#9375 fix(core/diffs): NPE on ViewChangesLink, minor style tweak
  app/scripts/modules/core/src/diffs/ChangesModal.tsx
  app/scripts/modules/core/src/diffs/ViewChangesLink.tsx
Labels: ready to rebase

#9380 fix(md): only show messages section if not empty
  app/scripts/modules/core/src/managed/config/ManagementWarning.tsx
  app/scripts/modules/core/src/managed/messages/Messages.tsx
Labels: ready to merge, self merge

#9361 feat(tasks): Use stage context over variables
  app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
Labels: ready to merge

#8657 feat(aws): Support UDP and TLS listeners for NLB
  app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/network/CertificateSelectors.tsx
  app/scripts/modules/amazon/src/loadBalancer/configure/network/NLBListeners.tsx
  app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
Labels: Do Not Merge
