Repository spinnaker/deck, pull requests merged in 2021-12, with the labels that each got.

#9779 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, publish

#9764 Amazon server group command builder typescript migration
  packages/amazon/src/domain/IAmazonLaunchTemplate.ts
  packages/amazon/src/domain/IAmazonServerGroup.ts
  packages/amazon/src/reactShims/aws.react.injector.ts
  packages/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
  packages/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
  packages/amazon/src/serverGroup/configure/wizard/instanceType/advancedMode/InstanceTypeTable.tsx
  packages/amazon/src/serverGroup/configure/wizard/pages/ServerGroupInstanceType.tsx
  packages/amazon/src/serverGroup/serverGroup.transformer.ts
  packages/mocks/src/amazon/mockAmazonLaunchTemplate.ts
Labels: ready to rebase

#9780 update README for necessary `yarn modules` step before `yarn start`
  README.md
Labels: ready to merge

#9784 fix(cf): fix casing of Cloud Foundry across components
  packages/cloudfoundry/src/cf.module.ts
  packages/cloudfoundry/src/common/applicationName.validator.ts
  packages/cloudfoundry/src/pipeline/stages/cloneServerGroup/CloudFoundryCloneServerGroupStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/cloneServerGroup/cloudFoundryCloneServerGroupStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsStageConfigForm.tsx
  packages/cloudfoundry/src/pipeline/stages/createServiceKey/CloudFoundryCreateServiceKeyStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/createServiceKey/cloudFoundryCreateServiceKeyStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/deleteServiceBindings/CloudFoundryDeleteServiceBindingsStageConfigForm.tsx
  packages/cloudfoundry/src/pipeline/stages/deleteServiceKey/CloudFoundryDeleteServiceKeyStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/deleteServiceKey/cloudFoundryDeleteServiceKeyStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/deployService/CloudFoundryDeployServiceStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/deployService/CreateServiceInstanceDirectInput.tsx
  packages/cloudfoundry/src/pipeline/stages/deployService/ICloudFoundryServiceManifestSource.ts
  packages/cloudfoundry/src/pipeline/stages/deployService/cloudFoundryDeployServiceStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/destroyAsg/cloudFoundryDestroyAsgStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/destroyService/CloudFoundryDestroyServiceStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/destroyService/CloudFoundryDestroyServiceStageConfigForm.tsx
  packages/cloudfoundry/src/pipeline/stages/destroyService/cloudFoundryDestroyServiceStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/disableAsg/cloudFoundryDisableAsgStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/enableAsg/cloudFoundryEnableAsgStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/mapLoadBalancers/cloudFoundryMapLoadBalancersStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/resizeAsg/CloudFoundryResizeAsgStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/resizeAsg/cloudFoundryResizeAsgStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/rollbackCluster/CloudFoundryRollbackClusterStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/rollbackCluster/cloudFoundryRollbackClusterStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/runJob/CloudFoundryRunJobStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/runJob/cloudFoundryRunJob.module.ts
  packages/cloudfoundry/src/pipeline/stages/shareService/CloudFoundryShareServiceExecutionDetails.tsx
  packages/cloudfoundry/src/pipeline/stages/shareService/CloudFoundryShareServiceStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/shareService/cloudFoundryShareServiceStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/unmapLoadBalancers/cloudFoundryUnmapLoadBalancersStage.module.ts
  packages/cloudfoundry/src/pipeline/stages/unshareService/CloudFoundryUnshareServiceExecutionDetails.tsx
  packages/cloudfoundry/src/pipeline/stages/unshareService/CloudFoundryUnshareServiceStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/unshareService/cloudFoundryUnshareServiceStage.module.ts
  packages/cloudfoundry/src/presentation/pipeline/stages/CloudFoundryAsgStageConfig.tsx
  packages/cloudfoundry/src/presentation/pipeline/stages/CloudFoundryLoadBalancersExecutionDetails.tsx
  packages/cloudfoundry/src/presentation/pipeline/stages/CloudFoundryLoadBalancersStageConfig.tsx
  packages/cloudfoundry/src/presentation/pipeline/stages/CloudFoundryServiceExecutionDetails.tsx
  packages/cloudfoundry/src/presentation/pipeline/stages/CloudFoundryServiceKeyExecutionDetails.tsx
  packages/cloudfoundry/src/presentation/pipeline/stages/index.ts
Labels: ready to merge

#9702 fix(Kubernetes): Support instance links in k8s
  packages/kubernetes/src/instance/details/details.controller.ts
  packages/kubernetes/src/instance/details/details.html
  packages/kubernetes/src/interfaces/infrastructure.types.ts
Labels: ready to merge

#9771 fix(core): conditionally hide expression evaluation warning messages
  packages/core/src/pipeline/details/StageFailureMessage.tsx
Labels: ready to merge

#9783 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, publish

#9777 feat(pipeline executions/deck): Add support for max concurrent pipeli…
  packages/core/src/domain/IPipeline.ts
  packages/core/src/help/help.contents.ts
  packages/core/src/help/helpContents.registry.spec.ts
  packages/core/src/pipeline/config/triggers/ExecutionOptionsPageContent.spec.tsx
  packages/core/src/pipeline/config/triggers/ExecutionOptionsPageContent.tsx
Labels: ready to merge

#9787 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9788 feat(core/pipeline): Load quiet period configuration from Gate, not from SETTINGS
  packages/core/src/config/settings.ts
  packages/core/src/pipeline/triggers/QuietPeriodBadge.tsx
  packages/core/src/pipeline/triggers/TriggersTag.tsx
  packages/core/src/pipeline/triggers/useQuietPeriod.hook.ts
Labels: ready to merge
