Repository spinnaker/deck, pull requests merged in 2021-07, with the labels that each got.

#9386 fix(md): remove the built-in search box
  app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
Labels: ready to merge

#9385 fix(core): properly load ReactGA
  app/scripts/modules/core/src/core.module.ts
  app/scripts/modules/core/src/reactShims/react.ga.ts
Labels: ready to merge

#9390 fix(core): make ignored errors public
  app/scripts/modules/core/src/utils/Logger.ts
Labels: ready to merge, self merge

#9391 fix(publish): missing dependencies in publish.js
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9394 chore(amazon): Export subnet files
  app/scripts/modules/amazon/src/index.ts
Labels: ready to rebase

#9395 chore(package): amazon@0.0.323
  app/scripts/modules/amazon/package.json
Labels: ready to rebase

#9393 fix(md): convert error message to simple text
  app/scripts/modules/core/src/managed/overview/EnvironmentOverview.tsx
  app/scripts/modules/core/src/managed/overview/baseStyles.less
Labels: ready to merge, self merge

#9399 feat(md): Display the raw delivery config instead of the processed one
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
Labels: ready to merge, self merge

#9384 feat(cloudfoundry/unbind): Delete Service Bindings stage
  app/scripts/modules/cloudfoundry/src/cf.module.ts
  app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceBindings/CloudFoundryDeleteServiceBindingsConfig.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceBindings/CloudFoundryDeleteServiceBindingsStageConfigForm.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceBindings/cloudFoundryDeleteServiceBindingsStage.ts
  app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceBindings/cloudFoundryDeleteServiceBindingsStageForm.spec.tsx
Labels: ready to merge

#9187 feat(cloudfoundry): show baked manifest
  app/scripts/modules/cloudfoundry/src/pipeline/stages/bakeCloudFoundryManifest/BakeCloudFoundryManifestDetailsTab.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/bakeCloudFoundryManifest/bakeCloudFoundryManifestStage.ts
  test/functional/cypress/fixtures/cloudfoundry/pipelines/01F6848ZR2N8NJAPBVTEP9R8FV.succeeded.json
  test/functional/cypress/fixtures/cloudfoundry/pipelines/pipelineConfigs.json
  test/functional/cypress/fixtures/cloudfoundry/pipelines/pipelines.json
  test/functional/cypress/fixtures/default/application.cfapp.json
  test/functional/cypress/integration/cloudfoundry/pipelines.spec.js
  test/functional/cypress/support/defaultFixtures.js
Labels: ready to merge

#9401 feat(md): MD debug mode
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  app/scripts/modules/core/src/managed/utils/debugMode.ts
  app/scripts/modules/core/src/utils/clipboard/copyTextToClipboard.ts
Labels: ready to merge

#9403 fix(tasks): Handle tasks with no stages
  app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
Labels: ready to merge

#9416 fix(managed-delivery): Fix resource deleting icon
  app/scripts/modules/core/src/managed/overview/Resource.tsx
Labels: ready to merge

#8669 feat(trigger): Show Payload Constraints option for build triggers
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
Labels: ready to merge

#9424 fix(core): move all graphql code generator components to core and fix the build script
  README.md
  graphql.schema.json
  package.json
  packages/core/codegen.yml
  packages/core/package.json
  yarn.lock
Labels: ready to merge

#9407 feat(cf/versioning): Feat cloudFoundry service versioning
  packages/cloudfoundry/src/pipeline/stages/deployService/CloudfoundryDeployServiceStageConfig.tsx
  packages/cloudfoundry/src/pipeline/stages/deployService/CreateServiceInstanceDirectInput.tsx
  packages/cloudfoundry/src/pipeline/stages/deployService/CreateUserProvidedInput.tsx
  packages/cloudfoundry/src/pipeline/stages/deployService/ICloudFoundryServiceManifestSource.ts
  packages/core/src/help/help.contents.ts
Labels: ready to merge

#9428 chore(verbiage): Change verbiage from 'Enable IMDSv2' -> 'Require IMDSv2'
  packages/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx
Labels: ready to rebase

#9430 feat: add description (just testing release-please)
  .github/release-please-manifest.app.json
  .github/release-please-manifest.tools.json
  packages/scripts/package.json
Labels: ready to merge, self merge

#9431 fix(release-please): use separate source branch names for app and tools (git symbolic-ref refs/heads/release-please-app refs/head/smaster)
  .github/workflows/release-please.yml
Labels: ready to merge, self merge

#9432 fix(release-please): fix pull request title config
  .github/workflows/release-please.yml
Labels: ready to merge, self merge

#9434 feat(release-please): Consolidate all releases into a single PR
  .github/release-please-config.json
  .github/release-please-config.tools.json
  .github/release-please-manifest.json
  .github/release-please-manifest.tools.json
  .github/workflows/release-please.yml
Labels: ready to merge, self merge

#9435 release please single pr
  .github/release-please-config.json
Labels: ready to merge, self merge

#9438 fix(core): missing/broken types
  packages/core/src/domain/IPipeline.ts
  packages/core/src/pipeline/config/validation/PipelineConfigValidator.ts
  packages/core/src/pipeline/manualExecution/TriggerTemplate.tsx
Labels: ready to merge

#9439 chore(core): bump manually to 6.0.10
  packages/core/package.json
Labels: ready to merge, self merge

#9440 test(karma-shim): Limit test matching to files inside /src directories
  karma-shim.js
Labels: ready to merge, self merge

#9441 chore: update yarn.lock (not sure why this is stale)
  yarn.lock
Labels: ready to merge, self merge

#9446 fix(publishing): Fix indent in lerna-release-pr.yml GHA workflow
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9447 fix(publishing): Add git user.name and user.email
  .github/workflows/lerna-release-pr.yml
Labels: ready to rebase, self merge

#9449 fix(publishing): Add --no-push to lerna version
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9450 fix(publishing): Actually run the .github/gha_output_* scripts
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9455 lerna
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9456 fix(publishing): Apply conventional commit AFTER running 'gha - get bumped packages'
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9458 fix(publishing): Auto approve instead of adding "ready to merge" label
  .github/workflows/lerna-release-pr.yml
Labels: ready to merge, self merge

#9462 feat(amazon): sample commit to test publish PR generation
  packages/amazon/src/index.ts
Labels: ready to merge, self merge

#9463 lerna
  .github/workflows/package-bump-pr.yml
  .github/workflows/publish.yml
  scripts/gha_output_bumped_packages.sh
  scripts/gha_output_changelog.sh
  scripts/gha_publish.sh
Labels: ready to merge, self merge

#9464 chore(publishing): fix if/then syntax in scripts/gha_output_* scripts
  scripts/gha_output_bumped_packages.sh
  scripts/gha_output_changelog.sh
Labels: ready to merge, self merge

#9467 fix(publishing): Pass pull request number to approve-pull-request action
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9468 fix(publishing): use latest hmarr/auto-approve-action
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9469 fix(publishing): Use lerna to publish packages
  scripts/gha_publish.sh
Labels: ready to merge, self merge

#9470 fix(publishing): Fetch tags for use by lerna publish using fetch-depth: 0
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9472 fix(publishing): Get publish git-tag from ${package}/package.json
  scripts/gha_publish.sh
Labels: ready to merge, self merge

#9473 fix(publishing): Configure git user/email before pushing tags to github
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9476 fix(publishing): Use actions/checkout@v2 when publishing packages
  .github/workflows/package-bump-pr.yml
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9478 fix(publishing): pass --yes to lerna publish from-git Also re-organize the workflow steps
  .github/workflows/publish.yml
  scripts/gha_tag_bumped_packages.sh
Labels: ready to merge, self merge

#9480 fix(publishing): build all packges before publishing
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9481 feat: sample amazon commit to test package publishin
  packages/amazon/src/index.ts
Labels: ready to merge, self merge

#9483 fix(publishing): regenerate package publish PR when tags are pushed
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9484 fix(publishing): always run create-pull-request even if there are no new changes (to close the open PR hopefully)
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9485 fix(publishing): use spinnakerbot2 personal access token
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9486 fix(publishing): Close PR using octokit.pulls.update({})
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9487 feat: commit to test package bump PR creation
  packages/amazon/src/index.ts
Labels: ready to merge, self merge

#9489 fix(publishing): pass PAT as with.token: ${{ PAT }}
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9491 fix(publishing): approve spinnakerbot2's PR using spinnakerbot creds
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9492 feat: commit to test package bump PR creation
  packages/titus/src/index.ts
Labels: ready to merge, self merge

#9493 fix(titus): Display entryPointList if not empty
  packages/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx
Labels: ready to merge

#9494 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9497 fix(publishing): try using spinnakerbot2 access token to push tags
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9500 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9502 fix(publishing): set github token for pushing tags using an env variable
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9501 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish, ready to merge

#9505 fix: sample commit to test publishing scripts
  packages/amazon/src/index.ts
Labels: ready to merge, self merge

#9506 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9508 feat(publishing): Split publish job into multiple steps
  .github/workflows/package-bump-pr.yml
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9509 fix: sample commit to test publishing scripts
  packages/core/src/index.ts
Labels: ready to merge, self merge

#9510 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish, ready to merge

#9512 feat(publishing): Checkout repo using spinnakerbot PAT hopefully this allows 'git push [tag]' to trigger a second github action workflow
  .github/workflows/publish.yml
Labels: ready to merge, self merge

#9513 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9519 feat(publishing): Always check out the master branch when updating the package bump pr
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9522 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9530 fix(build): Upgrade uirouter/react version
  package.json
  packages/amazon/package.json
  packages/cloudfoundry/package.json
  packages/core/package.json
  packages/ecs/package.json
  packages/kubernetes/package.json
  packages/titus/package.json
  yarn.lock
Labels: self merge

#9533 unweirdify node env logging
  packages/scripts/.eslintrc.js
  packages/scripts/config/rollup.config.base.js
Labels: ready to merge

#9498 feat: introduce a separate timeout config property for api timeouts
  packages/core/src/api/ApiService.ts
  packages/core/src/config/settings.ts
Labels: ready to merge

#9524 fix(ecs/securityGroups): Rename the securityGroups attribute due Clou…
  packages/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
Labels: ready to merge

#9529 chore(publish): set NODE_ENV=production when publishing
  .github/workflows/publish.yml
Labels: ready to merge

#9537 fix(md): fetch raw delivery config via graphql
  packages/core/src/managed/ManagedReader.ts
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/config/ManagementWarning.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge, self merge

#9526 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9540 Publish packages to NPM
  app/scripts/modules/app/CHANGELOG.md
  app/scripts/modules/app/package.json
Labels: publish

#9543 fix(publishing): checkout master explicitly. do not try to close PR when no PR was matched by create-pull-request.
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge
