Repository spinnaker/deck, pull requests merged in 2021-04, with the labels that each got.

#9066 fix(dependabot): Add spinnaker/presentation to the list of deps that get updated
  .github/dependabot.yml
Labels: ready to merge, self merge

#9063 feat(md): Show resource history link on hover
  app/scripts/modules/core/src/managed/EnvironmentsList.tsx
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
  app/scripts/modules/core/src/managed/ManagedResourceStatusPopover.tsx
  app/scripts/modules/core/src/managed/ObjectRow.less
  app/scripts/modules/core/src/managed/ObjectRow.tsx
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.less
  app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
  app/scripts/modules/core/src/managed/overview/ResourceDeploymentStatus.tsx
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#9068 chore(package): core@0.0.564
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9069 fix(md): fix order of environments based on the constraints
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/constraints/DependsOn.tsx
Labels: ready to merge

#9070 chore(package): core@0.0.565
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9071 feat(md): sort environments based on constraints on the main page
  app/scripts/modules/core/src/managed/ManagedReader.ts
  app/scripts/modules/core/src/managed/utils/sortEnvironments.spec.ts
  app/scripts/modules/core/src/managed/utils/sortEnvironments.ts
Labels: ready to merge

#9074 fix(titus): Fix Run Job execution details imageId
  app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx
Labels: ready to merge

#7822 feat(infrastructure/buttons): Add a new property configurable on sett…
  app/scripts/modules/core/src/cloudProvider/CloudProviderRegistry.ts
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.spec.ts
  app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.ts
  app/scripts/modules/core/src/cluster/allClusters.controller.js
  app/scripts/modules/core/src/cluster/allClusters.html
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/loadBalancer/CreateLoadBalancerButton.tsx
  app/scripts/modules/core/src/securityGroup/SecurityGroups.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
  app/scripts/modules/kubernetes/src/kubernetes.module.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.controller.ts
  app/scripts/modules/kubernetes/src/loadBalancer/details/details.html
  app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/securityGroup/details/details.html
  app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroup/details/details.html
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.controller.ts
  app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/TitusMapLayout.less
  settings-local.js
Labels: ready to merge

#9075 fix(md): Manual judgement failed text
  app/scripts/modules/core/src/managed/constraints/ManualJudgement.tsx
Labels: ready to merge

#9072 feat(md): allowed times constraints - add times group and fixed timezone
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.spec.ts
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
Labels: ready to merge

#9080 fix(core): unique pipeline graph ids
  app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
Labels: ready to rebase

#9081 chore(package): core@0.0.567
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9083 feat(core/taskExecutor): Adds failure message to error
  app/scripts/modules/core/src/task/taskExecutor.ts
Labels: ready to merge

#9082 fix(core): Fix lint error
  app/scripts/modules/core/src/cloudProvider/CloudProviderRegistry.ts
Labels: ready to rebase

#9090 fix(changelog-link): refactor changelog logic
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/help/HelpMenu.tsx
Labels: ready to merge

#9096 feat(core/pipeline): filter by stages awaiting judgement
  app/scripts/modules/core/src/filterModel/IFilterModel.ts
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
  app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Labels: ready to merge

#9095 fix(pipeline): Do not infer user from parent
  app/scripts/modules/core/src/pipeline/status/ExecutionUserStatus.tsx
Labels: ready to merge

#9097 Remove webpack modules + webpack consolidation
  app/scripts/modules/amazon/package.json
  app/scripts/modules/amazon/webpack.config.js
  app/scripts/modules/app.ts
  app/scripts/modules/appengine/package.json
  app/scripts/modules/appengine/webpack.config.js
  app/scripts/modules/azure/package.json
  app/scripts/modules/azure/webpack.config.js
  app/scripts/modules/base.webpack.config.js
  app/scripts/modules/cloudfoundry/package.json
  app/scripts/modules/cloudfoundry/webpack.config.js
  app/scripts/modules/core/package.json
  app/scripts/modules/core/webpack.config.js
  app/scripts/modules/docker/package.json
  app/scripts/modules/docker/webpack.config.js
  app/scripts/modules/ecs/package.json
  app/scripts/modules/ecs/webpack.config.js
  app/scripts/modules/google/package.json
  app/scripts/modules/google/webpack.config.js
  app/scripts/modules/huaweicloud/package.json
  app/scripts/modules/huaweicloud/webpack.config.js
  app/scripts/modules/kubernetes/package.json
  app/scripts/modules/kubernetes/src/kubernetes.module.ts
  app/scripts/modules/kubernetes/webpack.config.js
  app/scripts/modules/oracle/package.json
  app/scripts/modules/oracle/webpack.config.js
  app/scripts/modules/strictDi.ts
  app/scripts/modules/tencentcloud/package.json
  app/scripts/modules/tencentcloud/webpack.config.js
  app/scripts/modules/titus/package.json
  app/scripts/modules/titus/webpack.config.js
  karma-shim.js
  package.json
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: ready to merge

#9098 pluginsdk updates
  packages/pluginsdk-peerdeps/Dockerfile.upgrade-interactive
  packages/pluginsdk-peerdeps/package.json
  packages/pluginsdk/package.json
  packages/pluginsdk/pluginconfig/rollup.config.js
Labels: ready to merge

#9101 chore(core): bumped date-fns version
  app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
  app/scripts/modules/core/src/utils/timeFormatters.ts
  package.json
  yarn.lock
Labels: ready to merge

#9103 feat(core): updated notifications to react-toastify
  app/scripts/modules/core/src/widgets/notifier/Notifier.tsx
  app/scripts/modules/core/src/widgets/notifier/notifier.component.less
  app/scripts/modules/core/src/widgets/notifier/notifier.service.ts
  package.json
  yarn.lock
Labels: ready to merge

#9114 chore: update to kayenta 1.0.4
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9117 feat: upgrade husky to 6.x
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9119 chore(pluginsdk-peerdeps): remove husky (comes for free with pluginsdk now)
  packages/pluginsdk-peerdeps/package.json
Labels: ready to rebase, self merge

#8885 feat(codebuild): Secondary Sources Version
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildSourceList.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSecondarySourceVersionModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
  app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/IAwsCodeBuildSource.tsx
Labels: ready to merge

#9124 feat: update to kayenta 2.0.0 lazy loaded
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9128 chore: pin exact @spinnaker/* versions in package.json
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9111 fix(core): pushed modal overlay to the background
  app/scripts/modules/azure/src/loadBalancer/configure/AzureLoadBalancerChoiceModal.tsx
  app/scripts/modules/core/src/securityGroup/CreateSecurityGroupButton.tsx
Labels: ready to merge

#9127 fix(titus): Fixing React.Children.only issue
  app/scripts/modules/titus/src/serverGroup/details/TitusSecurityGroups.tsx
Labels: ready to merge
