Repository spinnaker/deck, pull requests merged in 2021-01, with the labels that each got.

#8823 feat(cloudfoundry): add create service binding stage
  app/scripts/modules/cloudfoundry/src/cf.module.ts
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsConfig.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsStageConfigForm.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/cloudFoundryCreateServiceBindingsStage.ts
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/cloudFoundryCreateServiceBindingsStageForm.spec.tsx
Labels: ready to merge

#8826 feat(cloudfoundry): Simplification
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsConfig.spec.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsConfig.tsx
Labels: ready to merge

#8827 fix(amazon/vpc): Fix error: "cannot call setState on an unmounted component" by migrating to FC/useData
  app/scripts/modules/amazon/src/vpc/VpcTag.tsx
Labels: ready to merge

#8828 fix(amazon/loadBalancer): Fix target group health interface
  app/scripts/modules/amazon/src/domain/IAmazonHealth.ts
  app/scripts/modules/amazon/src/instance/details/utils.ts
  app/scripts/modules/amazon/src/loadBalancer/amazonLoadBalancerDataUtils.ts
Labels: ready to merge

#8830 feat(amazon): Display updated ALB redirect config
  app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
Labels: ready to merge

#8829 refactor(presentation): Create a new npm package for core presentation modules in deck
  packages/presentation/package.json
  packages/presentation/rollup.config.js
  packages/presentation/src/index.ts
  packages/presentation/src/utils/index.ts
  packages/presentation/src/utils/noop.ts
  packages/presentation/tsconfig.json
  packages/presentation/yarn.lock
Labels: ready to rebase

#8802 fix(kubernetes): Fix Details link on pipeline deploy status for global resources
  app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/ManifestDetailsLink.tsx
Labels: ready to merge

#8800 feat(kubernetes): Raw resources UI MVP
  app/scripts/modules/core/src/config/settings.ts
  app/scripts/modules/core/src/presentation/icons/iconsByName.ts
  app/scripts/modules/core/src/presentation/icons/vectors/spMenuK8s.svg
  app/scripts/modules/kubernetes/src/index.ts
  app/scripts/modules/kubernetes/src/kubernetes.module.ts
  app/scripts/modules/kubernetes/src/rawResource/component/K8sResources.less
  app/scripts/modules/kubernetes/src/rawResource/component/K8sResources.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/K8sResourcesFilters.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/RawResourceUtils.ts
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResouceGroup.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResource.less
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResource.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResourceDetails.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResourceGroups.tsx
  app/scripts/modules/kubernetes/src/rawResource/controller/FiltersPubSub.ts
  app/scripts/modules/kubernetes/src/rawResource/index.ts
  app/scripts/modules/kubernetes/src/rawResource/model/resource.ts
  app/scripts/modules/kubernetes/src/rawResource/rawResource.dataSource.ts
  app/scripts/modules/kubernetes/src/rawResource/rawResource.module.ts
  app/scripts/modules/kubernetes/src/rawResource/rawResource.states.ts
  package.json
  settings.js
  yarn.lock
Labels: ready to merge

#8836 feat(md): waiting status
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/managedResourceStatusConfig.tsx
Labels: ready to merge

#8837 fix(gitlab): fix help text for gitlab artifacts
  app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/GitlabArtifactEditor.tsx
Labels: ready to merge

#8838 fix(core/pipeline): Remove note that pipelines are only paused for 72 hours
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Labels: ready to rebase

#8844 feat(amazon): Display updated ALB redirect config
  app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
Labels: ready to merge

#8846 chore(peerdeps): Update core to 0.0.540
  packages/pluginsdk-peerdeps/package.json
Labels: ready to rebase

#8835 fix(aws): Add Connection termination on deregistration flag on NLB's
  app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
  app/scripts/modules/amazon/src/help/amazon.help.ts
  app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
  app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
Labels: ready to merge

#8853 fix(core): Fix incorrect removal when merging serverGroups response
  app/scripts/modules/core/src/cluster/cluster.service.spec.ts
  app/scripts/modules/core/src/cluster/cluster.service.ts
Labels: ready to merge

#8834 Deangularize instance writer
  app/scripts/modules/amazon/src/instance/amazon.instance.write.service.ts
  app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
  app/scripts/modules/amazon/src/instance/index.ts
  app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
  app/scripts/modules/appengine/src/instance/details/details.controller.ts
  app/scripts/modules/azure/src/instance/details/instance.details.controller.js
  app/scripts/modules/cloudfoundry/src/instance/details/CloudFoundryInstanceActions.tsx
  app/scripts/modules/cloudfoundry/src/instance/details/CloudFoundryInstanceDetails.tsx
  app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceBindings/cloudFoundryCreateServiceBindingsStageForm.spec.tsx
  app/scripts/modules/core/src/instance/details/multipleInstances.controller.js
  app/scripts/modules/core/src/instance/instance.write.service.spec.ts
  app/scripts/modules/core/src/instance/instance.write.service.ts
  app/scripts/modules/dcos/instance/details/details.controller.js
  app/scripts/modules/google/src/instance/details/instance.details.controller.js
  app/scripts/modules/oracle/src/instance/details/instance.details.controller.js
  app/scripts/modules/titus/src/instance/details/instance.details.controller.js
Labels: ready to merge

#8822 fix(core): remove save pipeline error message if success
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
Labels: ready to merge

#8821 fix(core/search): Exclude duplicate results in search views
  app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.service.ts
Labels: ready to merge

#8820 fix(core/projects): Align 404 error message to center if project not found
  app/scripts/modules/core/src/projects/ProjectHeader.tsx
Labels: ready to merge

#8817 Update dependabot to v2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ready to merge

#8848 fix(pipeline/overlay): fix overlay placement with long desc
  app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
  app/scripts/modules/core/src/presentation/Popover.tsx
Labels: ready to merge

#8646 fix(API): encodeURIComponent for each path element
  app/scripts/modules/core/src/api/ApiService.spec.ts
  app/scripts/modules/core/src/api/ApiService.ts
  app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
  app/scripts/modules/core/src/pipeline/service/execution.service.ts
Labels: ready to merge

#8748 fix(core/pipelines): break and wrap long comments text
  app/scripts/modules/core/src/pipeline/config/stages/common/executionSummary.html
  app/scripts/modules/core/src/pipeline/details/stageExecutionDetails.less
Labels: ready to merge

#8860 chore(presentation): Fix package.json
  packages/presentation/package.json
  packages/presentation/yarn.lock
Labels: ready to merge

#8862 chore(package): core@0.0.542
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8867 fix(core): Fix eslint failures
  packages/eslint-plugin/test/api-deprecation.spec.js
Labels: ready to rebase

#8871 chore(package): core@0.0.543
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8872 fix(core): handle errors on confirmation modal submission
  app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx
Labels: ready to rebase

#8873 feat(core): export StageSummary props in core module
  app/scripts/modules/core/src/pipeline/details/index.ts
Labels: ready to merge, ready to rebase

#8874 chore(package): core@0.0.544
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8863 fix(ecs): Determine invalid target groups for the ECS provider
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
Labels: ready to merge

#8875 feat(ecs): improve the Capacity Providers configuration UI
  app/scripts/modules/ecs/src/ecsCluster/IEcsCapacityProviderDetails.ts
  app/scripts/modules/ecs/src/ecsCluster/ecsCluster.read.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/capacityProvider.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.js
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.html
  test/functional/cypress/fixtures/ecs/shared/ecsClusters.json
  test/functional/cypress/fixtures/ecs/shared/ecsDescribeClusters.json
  test/functional/cypress/integration/ecs/server_group.spec.js
Labels: ready to merge

#8877 feat(core) Expose raw subnet ID
  app/scripts/modules/core/src/subnet/SubnetTag.tsx
Labels: ready to merge
