Repository spinnaker/deck, pull requests merged in 2021-09, with the labels that each got.

#9630 chore(md): dismiss notifications when debug mode enabled
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/messages/MessageBox.less
  packages/core/src/managed/messages/MessageBox.tsx
  packages/core/src/managed/messages/Messages.tsx
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge

#9632 feat(provider/azure): Add image settings to server group
  packages/azure/src/serverGroup/configure/serverGroup.configure.azure.module.js
  packages/azure/src/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
  packages/azure/src/serverGroup/configure/wizard/image/ServerGroupImageSettings.controller.js
  packages/azure/src/serverGroup/configure/wizard/image/imageSettings.html
  packages/azure/src/serverGroup/configure/wizard/image/imageSettingsSelector.directive.html
  packages/azure/src/serverGroup/configure/wizard/image/imageSettingsSelector.directive.js
  packages/azure/src/serverGroup/configure/wizard/serverGroupWizard.html
  packages/azure/src/serverGroup/serverGroup.transformer.js
Labels: ready to merge

#9627 feat(provider/azure): Add userAssignedIdentities to azure UI
  packages/azure/src/help/azure.help.ts
  packages/azure/src/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.html
  packages/azure/src/serverGroup/serverGroup.transformer.js
Labels: ready to merge

#9634 feat(md): added "import now" to delivery config
  .prettierignore
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge

#9631 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9635 feat(provider/azure): Allow specifying App Gateway sku
  packages/azure/src/loadBalancer/configure/advancedSettings.html
  packages/azure/src/loadBalancer/configure/createLoadBalancer.controller.js
  packages/azure/src/loadBalancer/loadBalancer.transformer.js
Labels: ready to merge

#9637 chore(md): reorg of files
  packages/core/src/core.module.ts
  packages/core/src/managed/externals/DeployingIntoManagedClusterWarning.tsx
  packages/core/src/managed/externals/ManagedMenuItem.tsx
  packages/core/src/managed/externals/ManagedResourceConfig.less
  packages/core/src/managed/externals/ManagedResourceConfig.tsx
  packages/core/src/managed/externals/ManagedResourceDetailsIndicator.css
  packages/core/src/managed/externals/ManagedResourceDetailsIndicator.tsx
  packages/core/src/managed/externals/ManagedResourceStatusIndicator.less
  packages/core/src/managed/externals/ManagedResourceStatusIndicator.tsx
  packages/core/src/managed/externals/ManagedResourceStatusPopover.tsx
  packages/core/src/managed/externals/managedResourceDecorators.ts
  packages/core/src/managed/externals/managedResourceDetailsIndicator.component.ts
  packages/core/src/managed/externals/managedResourceStatusConfig.tsx
  packages/core/src/managed/externals/toggleResourceManagement.tsx
  packages/core/src/managed/index.ts
  packages/core/src/managed/managed.dataSource.ts
Labels: ready to merge, self merge

#9638 chore(artifacts): remove unused angularjs component artifact-list-icon
  packages/core/src/artifact/artifactIconList.ts
  packages/core/src/artifact/index.ts
Labels: ready to merge

#9639 chore(md): added logging to git integration
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/config/GitIntegration.tsx
Labels: ready to merge, self merge

#9641 fix(titus/subnet): Support default titus subnetType in SubnetSelectInput
  packages/amazon/src/subnet/SubnetSelectField.tsx
  packages/amazon/src/subnet/SubnetSelectInput.tsx
  packages/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  packages/titus/src/titus.settings.ts
Labels: ready to merge, self merge

#9610 fix(core/application): Fix for `requiredGroupMembership` breaking UI
  packages/core/src/application/modal/editApplication.controller.modal.js
Labels: ready to merge

#9642 Titus: Support default subnets
  packages/amazon/src/subnet/SubnetSelectField.tsx
  packages/amazon/src/subnet/SubnetSelectInput.spec.tsx
  packages/amazon/src/subnet/SubnetSelectInput.tsx
  packages/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
  packages/titus/src/titus.settings.ts
Labels: ready to merge, self merge

#9636 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, publish

#9643 fix(amazon/serverGroup): SubnetSelectField: Use default subnets from settings if no defaultSubnetTypes prop is passed
  packages/amazon/src/subnet/SubnetSelectField.tsx
Labels: ready to merge, self merge

#9616 fix(help): change entering to entered
  packages/ecs/src/ecs.help.ts
Labels: ready to merge

#9617 fix(help): Correct And to Add
  packages/amazon/src/help/amazon.help.ts
Labels: ready to merge

#9644 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, publish

#9645 fix(core): do not show "0" when no scaling activities detected
  packages/core/src/serverGroup/details/scalingActivities/ScalingActivitiesModal.tsx
Labels: ready to rebase

#9633 feat(core): Allow notification email SpEL
  packages/core/src/notification/selector/types/email/EmailNotificationType.tsx
  packages/core/src/presentation/forms/validation/validators.ts
Labels: ready to merge

#8990 feat(travis): Remove Property File field from Travis stages and triggers
  packages/core/src/pipeline/config/stages/travis/travisStage.html
  packages/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
  packages/core/src/pipeline/config/triggers/travis/TravisTrigger.tsx
Labels: ready to merge

#9651 fix(style): keep submit button status indicator inline with label
  packages/core/src/modal/buttons/submitButton.component.ts
Labels: ready to rebase

#9640 feat(md): extended and simplified constraint title rendering
  packages/core/src/managed/constraints/AllowedTimes.tsx
  packages/core/src/managed/constraints/DependsOn.tsx
  packages/core/src/managed/constraints/ManualJudgement.tsx
  packages/core/src/managed/constraints/registry.tsx
  packages/core/src/managed/overview/artifact/Artifact.less
  packages/core/src/managed/overview/artifact/Constraints.less
  packages/core/src/managed/overview/artifact/Constraints.tsx
  packages/core/src/managed/overview/artifact/VersionOperation.tsx
  packages/core/src/managed/overview/artifact/VersionOperationIcon.less
  packages/core/src/managed/overview/baseStyles.less
Labels: ready to merge, self merge

#9646 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9657 feat(md): display manifest path and make it configurable
  packages/core/src/managed/config/GitIntegration.less
  packages/core/src/managed/config/GitIntegration.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/baseStyles.less
  packages/core/src/managed/overview/queries.graphql
Labels: ready to merge, self merge

#9660 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9665 fix(core): break words in notifications to prevent overflow
  packages/core/src/widgets/notifier/notifier.component.less
Labels: ready to merge, self merge

#9659 fix(md): Added DELETING state to resource states.
  packages/core/src/domain/IManagedEntity.ts
  packages/core/src/managed/externals/managedResourceStatusConfig.tsx
Labels: ready to merge

#9668 chore(md): moved all urls of MD to settings to allow overriding
  packages/core/src/config/settings.ts
  packages/core/src/managed/UnmanagedMessage.tsx
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/externals/ManagedResourceConfig.tsx
  packages/core/src/managed/externals/ManagedResourceDetailsIndicator.tsx
  packages/core/src/managed/externals/managedResourceStatusConfig.tsx
  packages/core/src/managed/overview/artifact/ArtifactActionModal.tsx
  packages/core/src/managed/utils/defaults.ts
Labels: ready to merge, self merge

#9662 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9669 fix(md): replaced status with statusSummary
  packages/core/src/managed/versionsHistory/VersionHeading.tsx
Labels: ready to merge, self merge

#9670 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9671 fix(md): fix version message style
  packages/core/src/managed/versionMetadata/MetadataComponents.tsx
  packages/core/src/managed/versionMetadata/VersionMetadata.less
Labels: ready to merge, self merge

#9672 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9674 fix(md): render resource status as markdown
  packages/core/src/managed/overview/Resource.less
  packages/core/src/managed/overview/Resource.tsx
Labels: ready to merge

#9676 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9677 fix(pipelines): Reduce pipelineConfig fetches
  packages/core/src/pipeline/details/SingleExecutionDetails.tsx
  packages/core/src/pipeline/service/execution.service.ts
Labels: ready to merge

#9679 fix(aws/lambda): Lists Event Source details for functions
  packages/amazon/src/function/details/AmazonFunctionDetails.tsx
Labels: ready to merge, backport-candidate

#9683 fix(aws/lambda): Lists Event Source details for functions
  packages/amazon/src/function/details/AmazonFunctionDetails.tsx
Labels: ready to merge

#9686 fix(aws/lambda): Fix functions icon on menu
  packages/core/src/function/function.dataSource.ts
  packages/presentation/src/icons/iconsByName.ts
  packages/presentation/src/icons/vectors/spMenuFunctions.svg
Labels: ready to merge, backport-candidate

#9673 chore(deps): switch to Source Sans 3
  packages/app/index.deck
  packages/app/index.html
  packages/core/package.json
  packages/core/src/core.module.ts
  packages/core/src/modal/modals.less
  packages/core/src/presentation/main.less
  packages/google/src/serverGroup/configure/wizard/loadBalancers/elSevenOptions/backendServiceSelector.component.html
  packages/google/src/serverGroup/configure/wizard/securityGroups/tagSelector.component.html
  yarn.lock
Labels: ready to merge

#9678 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/presentation/CHANGELOG.md
  packages/presentation/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, publish

#9691 fix(md): notify users when an error occurs in mutations
  packages/core/src/managed/config/Configuration.tsx
  packages/core/src/managed/config/DeliveryConfig.tsx
  packages/core/src/managed/config/GitIntegration.tsx
  packages/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  packages/core/src/managed/overview/artifact/Constraints.tsx
  packages/core/src/managed/utils/useNotifyOnError.hook.ts
Labels: ready to merge

#9692 chore(core): bump presentation dependency
  package.json
  yarn.lock
Labels: ready to merge

#9693 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9699 chore(app): make packages/app/tsconfig.json extend ../tsconfig.app.base.json
  packages/app/tsconfig.json
Labels: ready to merge, self merge

#9690 fix(md): allow users to enable resource management
  packages/core/src/managed/externals/toggleResourceManagement.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/overview/Resource.tsx
  packages/core/src/managed/overview/queries.graphql
  packages/core/src/managed/resources/ToggleResourceManagement.tsx
Labels: ready to merge

#9700 fix(core): previous commit updated the font to sans serif 3, but not the styleguide
  packages/core/package.json
  yarn.lock
Labels: ready to merge, self merge

#9697 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9701 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9707 fix(kubernetes): hide ad-hoc infrastructure action buttons when spinnaker has multiple accounts
  packages/core/src/cloudProvider/providerSelection/ProviderSelectionService.spec.ts
  packages/core/src/cloudProvider/providerSelection/ProviderSelectionService.ts
  packages/core/src/cluster/allClusters.html
  packages/core/src/config/settings.ts
  packages/core/src/instance/details/multipleInstances.controller.js
  packages/core/src/instance/details/multipleInstances.view.html
  packages/core/src/serverGroup/details/multipleServerGroups.controller.js
  packages/core/src/serverGroup/details/multipleServerGroups.view.html
  packages/kubernetes/src/instance/details/details.controller.ts
  packages/kubernetes/src/instance/details/details.html
  packages/kubernetes/src/rawResource/component/group/RawResourceDetails.tsx
Labels: ready to merge

#9711 fix(titus): Deal with absence of non-required fields
  packages/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
Labels: ready to merge

#9713 feat(md): added a default component if preview environments configured but don't exist
  packages/core/src/config/settings.ts
  packages/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
  packages/core/src/managed/graphql/graphql-sdk.ts
  packages/core/src/managed/graphql/schema.graphql
  packages/core/src/managed/overview/EnvironmentsOverview.tsx
  packages/core/src/managed/overview/PreviewEnvironments.tsx
  packages/core/src/managed/overview/queries.graphql
  packages/core/src/managed/utils/defaults.ts
Labels: ready to merge

#9705 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9712 feat(aws/infrastructure): Hide aws ad hoc infrastructure action buttons
  packages/amazon/src/aws.module.ts
  packages/amazon/src/function/details/FunctionActions.spec.tsx
  packages/amazon/src/function/details/FunctionActions.tsx
  packages/amazon/src/instance/details/instance.details.controller.js
  packages/amazon/src/instance/details/instanceDetails.html
  packages/amazon/src/loadBalancer/details/LoadBalancerActions.tsx
  packages/amazon/src/securityGroup/details/securityGroupDetail.controller.js
  packages/amazon/src/securityGroup/details/securityGroupDetail.html
  packages/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
  packages/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/AmazonCapacityDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScalingProcessesDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScheduledActionsDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx
  packages/core/src/cloudProvider/CloudProviderRegistry.ts
  packages/core/src/cloudProvider/providerSelection/ProviderSelectionService.spec.ts
  packages/core/src/config/settings.ts
  packages/core/src/function/CreateFunctionButton.tsx
  packages/core/src/loadBalancer/CreateLoadBalancerButton.tsx
  packages/core/src/securityGroup/SecurityGroups.tsx
  packages/kubernetes/src/kubernetes.module.ts
Labels: ready to merge

#9715 feat(md): clean artifact version details by moving the bake and build details to a popover
  packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
  packages/core/src/managed/versionMetadata/MetadataComponents.tsx
  packages/core/src/managed/versionMetadata/VersionMetadata.less
  packages/core/src/managed/versionMetadata/VersionMetadata.tsx
  packages/core/src/managed/versionsHistory/VersionContent.tsx
  packages/core/src/managed/versionsHistory/VersionsHistory.tsx
Labels: ready to merge, self merge

#9723 fix(package-bumper): Also commit yarn.lock when creating package bumps via 'lerna version'
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, self merge

#9724 fix(publish): Commit lerna version bumps -- remove --no-git-tag-version for CI because it causes lerna not to commit files
  .github/workflows/package-bump-pr.yml
Labels: self merge

#9728 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/eslint-plugin/CHANGELOG.md
  packages/eslint-plugin/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/presentation/CHANGELOG.md
  packages/presentation/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish
