Repository spinnaker/deck, pull requests merged in 2021-10, with the labels that each got.

#9730 feat(lambda): add alias details to infra view
  packages/amazon/src/domain/IAmazonFunctionSourceData.ts
  packages/amazon/src/function/details/AmazonFunctionDetails.tsx
Labels: ready to merge

#9729 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/presentation/CHANGELOG.md
  packages/presentation/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9732 refactor(aws/infrastructure): move aws ad-hoc infra write flag
  packages/amazon/src/aws.module.ts
  packages/amazon/src/aws.settings.ts
  packages/amazon/src/function/details/FunctionActions.spec.tsx
  packages/amazon/src/function/details/FunctionActions.tsx
  packages/amazon/src/instance/details/instance.details.controller.js
  packages/amazon/src/loadBalancer/details/LoadBalancerActions.tsx
  packages/amazon/src/securityGroup/details/securityGroupDetail.controller.js
  packages/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
  packages/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/AmazonCapacityDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScalingProcessesDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/ScheduledActionsDetailsSection.tsx
  packages/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx
  packages/core/src/config/settings.ts
Labels: ready to merge

#9739 chore(jasmine): remove custom jasmine matcher 'textMatch'
  karma-shim.js
  packages/core/src/presentation/navigation/pageNavigator.component.spec.ts
  test/helpers/custom-matchers.d.ts
  test/helpers/customMatchers.ts
  tsconfig.json
Labels: ready to merge

#9743 fix(md): build links
  packages/core/src/managed/versionMetadata/MetadataComponents.tsx
Labels: ready to merge, self merge

#9740 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9741 refactor(amazon/vpc): Remove angularjs vpc-tag directive
  packages/amazon/src/instance/details/instance.details.controller.js
  packages/amazon/src/vpc/VpcTag.spec.tsx
  packages/amazon/src/vpc/vpc.module.ts
  packages/amazon/src/vpc/vpcTag.directive.js
  packages/amazon/src/vpc/vpcTag.directive.spec.js
Labels: ready to merge
