Repository spinnaker/deck, pull requests merged in 2021-03, with the labels that each got.

#8948 feat(core): global search box - search on enter
  app/scripts/modules/core/src/search/global/GlobalSearch.tsx
  app/scripts/modules/core/src/search/global/GlobalSearchResults.tsx
  app/scripts/modules/core/src/search/global/globalSearch.less
  app/scripts/modules/core/src/search/global/utils.ts
Labels: ready to merge

#8957 fix(amazon/serverGroup): Move spelLoadBalancers and spelTargetGroups to viewState
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
  app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
  app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
Labels: ready to merge

#8958 fix(docker): DockerImageAndTagSelector.tsx: do not setState when unmounted
  app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
Labels: ready to merge

#8963 feat(md): resource history title - add resource display name to title
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#8964 fix(core/forms): MapEditor: make trash icon position: relative to avoid scrollbars
  app/scripts/modules/core/src/forms/mapEditor/MapEditor.less
  app/scripts/modules/core/src/forms/mapEditor/MapEditor.tsx
  app/scripts/modules/core/src/forms/mapEditor/MapEditorInput.tsx
  app/scripts/modules/core/src/forms/mapEditor/MapPair.css
  app/scripts/modules/core/src/forms/mapEditor/MapPair.tsx
Labels: ready to merge

#8966 fix(md): Resource history - added explicit log level
  app/scripts/modules/core/src/managed/resourceHistory/HistoryEventRow.tsx
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.less
  app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
Labels: ready to merge

#8967 fix(pipelines): Add deps to breadcrumbs useMemo
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionBreadcrumbs.tsx
Labels: ready to merge

#8968 fix(md): remove beta tag
  app/scripts/modules/core/src/managed/managed.dataSource.ts
Labels: ready to merge

#8976 fix(amazon/subnet): fix NPE when AWSProviderSettings.serverGroups is undefined
  app/scripts/modules/amazon/src/subnet/SubnetSelectField.tsx
Labels: ready to merge

#8977 feat(core/application): Export the ApplicationContext values
  app/scripts/modules/core/src/application/ApplicationContext.tsx
  app/scripts/modules/core/src/application/index.ts
Labels: ready to merge, self merge

#8975 feat(titus): Add placeholder for custom scaling policy details
  app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/TitusCustomScalingPolicy.tsx
  app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/scalingPolicy.module.ts
  app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/titusCustomScalingPolicy.component.ts
  app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
Labels: ready to merge

#8979 fix(pluginsdk-peerdeps): fix broken logic in sync scripts
  packages/pluginsdk-peerdeps/package.json
  packages/pluginsdk-peerdeps/sync-versions-from-deck.js
Labels: ready to merge, self merge

#8980 chore(pluginsdk-peerdeps): release 0.0.10
  packages/pluginsdk-peerdeps/package.json
Labels: ready to merge, self merge

#8982 chore(pluginsdk): fix scaffold tmpl for newer spinnaker versions
  packages/pluginsdk/scaffold/src/WidgetizeStage.tsx
Labels: ready to merge

#8985 chore(package): core@0.0.555
  app/scripts/modules/core/package.json
Labels: ready to rebase

#8973 feat(core/application): Add a PlatformHeatlhOverrideInput wrapper component that adheres to the FormInput api
  app/scripts/modules/core/src/application/modal/PlatformHealthOverride.tsx
Labels: ready to merge

#8972 fix(core/presentation): CheckboxInput.tsx: render a &nbsp; if no text is present to align on baseline in flexbox containers
  app/scripts/modules/core/src/presentation/forms/inputs/CheckboxInput.tsx
Labels: ready to merge

#8989 feat(core/InsightMenu): Make component overridable
  app/scripts/modules/core/src/insight/InsightMenu.spec.tsx
  app/scripts/modules/core/src/insight/InsightMenu.tsx
Labels: ready to merge

#8971 fix(core/presentation): Avoid remounting CheckListInput on every render
  app/scripts/modules/core/src/presentation/forms/inputs/ChecklistInput.less
  app/scripts/modules/core/src/presentation/forms/inputs/ChecklistInput.tsx
Labels: ready to merge

#8993 feat(core/presentation): add `mode="CREATABLE"` to the ReactSelectInput
  app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
Labels: ready to merge

#8974 feat(core/presentation): Add a react hook useFormInputValueMapper
  app/scripts/modules/core/src/presentation/forms/hooks/index.ts
  app/scripts/modules/core/src/presentation/forms/hooks/useFormInputValueMapper.hook.ts
Labels: ready to merge

#9004 chore(presentation): publish 0.0.3
  packages/presentation/package.json
Labels: ready to rebase

#8995 fix(core/presentation): Change standard field layout flex to justify-content: space-between
  app/scripts/modules/core/src/presentation/forms/layouts/StandardFieldLayout.tsx
Labels: ready to merge

#9009 fix(core): Trim cloud providers after splitting
  app/scripts/modules/core/src/application/service/ApplicationReader.ts
Labels: ready to merge

#9010 fix(md): constraint status was using the global status var
  app/scripts/modules/core/src/managed/artifactDetail/constraints/constraintRegistry.tsx
Labels: ready to merge

#9011 chore(package): core@0.0.557
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9015 chore: eslint --fix
  app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
Labels: ready to merge, self merge

#8961 fix(appengine/docker): Allow save the Artifact in the Pipeline JSON f…
  app/scripts/modules/appengine/src/serverGroup/transformer.ts
  app/scripts/modules/appengine/src/serverGroup/transformet.spec.ts
Labels: ready to merge

#9016 fix(titus/serverGroup): allow underscores in the first character of environment variables
  app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
Labels: ready to merge

#9013 fix(pipeline): Move configure into execution
  app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/details/singleExecutionDetails.less
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Labels: ready to merge

#9017 fix(pipeline): Collapse parameters in ancestry
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Labels: ready to merge

#9018 feat(git): Add a .git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: ready to merge

#9021 fix(core/presentation): Add deps to useCallback
  app/scripts/modules/core/src/presentation/forms/hooks/useFormInputValueMapper.hook.ts
Labels: ready to merge, self merge

#9026 chore: eslint --fix
  app/scripts/modules/appengine/src/serverGroup/transformer.ts
Labels: ready to merge, self merge

#8997 feat(core/ProjectHeader): Make component overridable
  app/scripts/modules/core/src/projects/ProjectHeader.tsx
Labels: ready to merge

#9003 feat(core/ApplicationDataSourceRegistry): Remove data source based on key
  app/scripts/modules/core/src/application/service/ApplicationDataSourceRegistry.ts
Labels: ready to merge

#9000 feat(core/Execution): make component overridable
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Labels: ready to merge

#8999 feat(core/ExecutionGroup): make component overridable
  app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
Labels: ready to merge

#9024 fix(core/projects): Recent projects: only save the link to project dashboard
  app/scripts/modules/core/src/projects/projects.states.ts
Labels: ready to merge

#9027 feat(core/pipeline): Validate that submitted pipeline is not stale (hasn't been changed by another user)
  app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
Labels: ready to merge

#9031 fix(deck): Handles an undefined reference on `TaskMonitorWrapper`.
  app/scripts/modules/core/src/task/monitor/TaskMonitorWrapper.tsx
Labels: ready to merge

#9030 chore(functional): Remove remnants of selenium functional tests
  package.json
  wdio.conf.js
  yarn.lock
Labels: ready to merge

#9002 feat(core/Executions): Make component overridable
  app/scripts/modules/core/src/pipeline/executions/Executions.spec.tsx
  app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Labels: ready to merge

#8849 feat(pipelines): Enable filtering on dynamic categories
  app/scripts/modules/core/src/domain/IPipeline.ts
  app/scripts/modules/core/src/filterModel/IFilterModel.ts
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
  app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
  app/scripts/modules/core/src/pipeline/service/execution.service.ts
Labels: ready to merge

#9040 chore(package): core@0.0.561
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9043 fix(core/presentation): make hidePopover prop optional in HoverablePopover Component type
  app/scripts/modules/core/src/presentation/HoverablePopover.tsx
Labels: ready to merge, self merge

#9036 feat(md): change pending verification icon color to blue
  app/scripts/modules/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
Labels: ready to merge

#9037 fix(md): remove depends-on icon from the artifacts list
  app/scripts/modules/core/src/managed/artifactsList/ArtifactsList.tsx
Labels: ready to merge

#9042 feat(presentation): Add trash icon (renamed from delete which isn't a valid javascript identifier)
  packages/presentation/package.json
  packages/presentation/src/icons/iconsByName.ts
  packages/presentation/src/icons/vectors/trash.svg
Labels: ready to merge

#9044 feat(nav): new overridable section at the bottom of the left navigation bar
  app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
  app/scripts/modules/core/src/application/nav/BottomSection.tsx
  app/scripts/modules/core/src/application/nav/verticalNav.less
Labels: ready to merge

#9046 fix(core/presentation): allow null observable in useObservable.hook also export all the hooks from index.ts
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/useObservable.hook.ts
Labels: ready to merge

#9041 feat(core/confirmationModal): Close dialog when esc is pressed
  app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx
  app/scripts/modules/core/src/presentation/hooks/index.ts
  app/scripts/modules/core/src/presentation/hooks/useEscapeKeyCallback.hook.ts
Labels: ready to merge

#9050 fix(core/pipeline): After saving a pipeline, use the value from the server as the new "original" This change fixes multiple saves of a pipeline from the same configuration screen
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
Labels: ready to merge

#9054 chore(package): core@0.0.562
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9059 chore: update commit hook to run eslint first, then prettier
  package.json
Labels: ready to merge, self merge

#9060 chore(ci): replace hex colors with closes css variables
  app/scripts/modules/core/src/ci/components/builds.less
Labels: ready to merge

#9056 feat(pipeline): Pipeline Tags config UI
  app/scripts/modules/core/src/help/help.contents.ts
  app/scripts/modules/core/src/pipeline/config/triggers/DescriptionPageContent.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/MetadataPageContent.tsx
  app/scripts/modules/core/src/pipeline/config/triggers/Triggers.tsx
Labels: ready to merge
