Repository spinnaker/deck, pull requests merged in 2021-05, with the labels that each got.

#9134 fix(core): fix issue in console log modal
  app/scripts/modules/core/src/instance/details/console/ConsoleOutputModal.tsx
Labels: ready to merge

#9140 feat(pluginsdk-peerdeps): Add --no-spinnaker option to sync-versions-from-deck.js
  packages/pluginsdk-peerdeps/sync-versions-from-deck.js
Labels: ready to merge, self merge

#9155 chore(webpack): ignore source maps of some packages that are generating warnings
  webpack.config.js
Labels: ready to merge

#9159 chore(pluginsdk-peerdeps): Upgrade to 0.0.15
  packages/pluginsdk-peerdeps/package.json
Labels: ready to rebase, self merge

#9160 chore(pluginsdk-peerdeps): Upgrade to 0.0.16
  packages/pluginsdk-peerdeps/package.json
Labels: ready to rebase, self merge

#9156 fix(appengine): Allows ng to be injected.
  app/scripts/modules/appengine/src/serverGroup/transformer.ts
  app/scripts/modules/appengine/src/serverGroup/transformet.spec.ts
Labels: backport-candidate

#9163 fix(core): fix state update for pipeline tags
  app/scripts/modules/core/src/pipeline/config/triggers/MetadataPageContent.tsx
Labels: backport-candidate, ready to merge, ready to rebase

#9153 fix(deck): Attempt to fix `Cannot read property 'length' of undefined`
  app/scripts/modules/core/src/filterModel/FilterTags.tsx
Labels: backport-candidate, ready to merge, ready to rebase

#9166 feat(md): show post deploy tasks
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.less
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/overview/types.ts
Labels: ready to merge

#9168 feat(md): handle BLOCKED state for constraints
  app/scripts/modules/core/src/domain/IManagedEntity.ts
  app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
  app/scripts/modules/core/src/managed/constraints/ManualJudgement.tsx
  app/scripts/modules/core/src/managed/constraints/registry.tsx
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.less
  app/scripts/modules/core/src/managed/overview/artifact/VersionOperation.tsx
  app/scripts/modules/core/src/managed/overview/artifact/utils.spec.ts
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  graphql.schema.json
Labels: ready to merge

#9174 fix(md): ignore the status event field if it's identical to the reason
  app/scripts/modules/core/src/managed/overview/Resource.tsx
Labels: ready to merge

#9172 feat(core): logger component
  app/scripts/modules/core/src/presentation/SpinErrorBoundary.tsx
  app/scripts/modules/core/src/utils/Logger.ts
  app/scripts/modules/core/src/utils/index.ts
Labels: ready to merge

#9176 chore(package): core@0.0.577
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9173 fix(core): classnames package cleanup
  app/scripts/modules/core/src/utils/classnames.d.ts
  app/scripts/modules/core/src/utils/index.ts
  package.json
  yarn.lock
Labels: ready to merge

#8818 feat(core/ManualJudgment): Enhanced ManualJudgment
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/executionMarker.less
  app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroups.tsx
Labels: ready to rebase

#9179 fix(md): check if should use the new ui
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#9180 chore(package): core@0.0.578
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9181 fix(md): renamed feature flag
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
Labels: ready to merge

#9182 chore(package): core@0.0.579
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9177 fix(core/task): Render "submitting task" instead of throwing an error in MultiTaskMonitor.tsx
  app/scripts/modules/core/src/task/monitor/MultiTaskMonitor.tsx
  app/scripts/modules/core/src/task/monitor/TaskMonitorStatus.tsx
Labels: ready to merge, self merge

#9020 feat(pipeline): Change back button to breadcrumbs
  app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
Labels: ready to merge

#9189 feat(build): Add base tsconfig for independent packages
  tsconfig.base.json
Labels: ready to rebase

#9110 fix(core/pipeline): Resolved pipeline header alignment issue by ellip…
  app/scripts/modules/core/src/account/AccountTag.tsx
  app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
  app/scripts/modules/core/src/pipeline/executions/executionGroup/executionGroup.less
Labels: ready to merge

#9092 feat(ecs): Override Task Def Artifacts
  app/scripts/modules/ecs/src/ecs.help.ts
  app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
  app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
  test/functional/cypress/integration/ecs/server_group.spec.js
Labels: ready to rebase

#9191 feat(md): versions history page
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/BaseEnvironment.less
  app/scripts/modules/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentItem.tsx
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/managed.states.ts
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.less
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/overview/Resource.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.less
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/VersionMetadata.tsx
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  app/scripts/modules/core/src/managed/versionsHistory/types.ts
  app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
  app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionRegexField.tsx
  app/scripts/modules/core/src/presentation/main.less
  package.json
  yarn.lock
Labels: ready to merge

#9198 chore(scripts): Bump @spinnaker/scripts to 0.0.4
  packages/scripts/package.json
Labels: ready to rebase

#9205 feat(md): show error message if there are no artifacts or resources
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/overview/baseStyles.less
Labels: ready to merge

#9207 fix(md): fix order of environments
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
Labels: ready to merge

#9211 feat(amazon/serverGroup): export datelinechart and MetricAlarmChart
  app/scripts/modules/amazon/src/serverGroup/index.ts
Labels: ready to merge, self merge

#9213 feat(md): added commit sha to text and a link the tooltip
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
Labels: ready to merge

#9218 docs(scripts): Add comment about externals
  packages/scripts/config/rollup.config.base.module.js
Labels: ready to rebase

#9223 fix(md): sort versions even when no current exists
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
Labels: ready to merge, self merge

#9224 feat(md): only show first two pending versions (with expandable section)
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/overview/Resource.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
Labels: ready to merge, self merge

#9226 feat(md): show management warning in history
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
Labels: ready to merge, self merge

#9225 fix(md): refetch version on constraint action (works in all cases)
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
Labels: ready to merge, self merge

#9228 fix(md): order of environments 2
  app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
Labels: ready to merge, self merge

#9227 style(md): fix constraints style
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.less
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
Labels: ready to merge, self merge

#9199 fix(aws/lambda): Shows function details and actions menu.
  app/scripts/modules/amazon/src/function/details/FunctionActions.spec.tsx
  app/scripts/modules/amazon/src/function/details/FunctionActions.tsx
Labels: ready to merge

#9208 feat(md): pinned data tooltip info
  app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
  app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
  app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentItem.tsx
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
  app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.less
  app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  app/scripts/modules/core/src/managed/overview/baseStyles.less
  app/scripts/modules/core/src/managed/utils/defaults.ts
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  app/scripts/modules/core/src/managed/versionsHistory/types.ts
  app/scripts/modules/core/src/presentation/main.less
Labels: ready to merge, self merge

#9231 feat(md): build version tooltip
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
Labels: ready to merge, self merge

#9232 feat(md): limit history versions to 100
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  graphql.schema.json
Labels: ready to merge, self merge

#9233 fix(md): lifecycle data was missing in the query
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/overview/queries.graphql
Labels: ready to merge, self merge

#9234 feat(md): version veto info
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/graphql/schema.graphql
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
  app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
  graphql.schema.json
Labels: ready to merge, self merge

#9235 chore(package): core@0.0.584
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9239 fix(amazon): Add back ng template handling
  app/scripts/modules/amazon/src/aws.module.ts
Labels: self merge

#9240 chore(package): amazon@0.0.313
  app/scripts/modules/amazon/package.json
Labels: ready to rebase

#9241 fix(md): wrap tooltip content with span
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
Labels: ready to merge, self merge

#9242 chore(package): core@0.0.585
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9244 feat(presentation): mark as good illustration
  packages/presentation/package.json
  packages/presentation/src/illustrations/illustrationsByName.ts
  packages/presentation/src/illustrations/vectors/markArtifactVersionAsGood.svg
Labels: ready to merge, self merge

#9245 feat(md): Added mark as good + refactor actions to mutations and hooks
  app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
  app/scripts/modules/core/src/managed/overview/artifact/ArtifactActionModal.tsx
  app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
  app/scripts/modules/core/src/managed/overview/artifact/hooks.ts
  app/scripts/modules/core/src/managed/overview/artifact/utils.ts
  app/scripts/modules/core/src/managed/overview/queries.graphql
  app/scripts/modules/core/src/managed/utils/ActionModal.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
  package.json
  yarn.lock
Labels: ready to merge, self merge

#9249 fix(modules): chdir to modules before showing package bumps
  app/scripts/modules/show_package_bumps.js
Labels: ready to merge, self merge

#9222 feat(md): History - scroll to version + share link
  app/scripts/modules/core/src/managed/Environments.tsx
  app/scripts/modules/core/src/managed/Environments2.less
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/managed.states.ts
  app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
  app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
  app/scripts/modules/core/src/managed/versionsHistory/types.ts
  app/scripts/modules/core/src/presentation/main.less
  app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx
Labels: ready to merge, self merge

#9251 chore(package): core@0.0.586
  app/scripts/modules/core/package.json
Labels: ready to rebase

#9246 feat(core): add google analytics to logger
  app/scripts/modules/amazon/src/loadBalancer/AmazonLoadBalancersTag.tsx
  app/scripts/modules/core/src/application/config/managedResources/ManagedResourceConfig.tsx
  app/scripts/modules/core/src/entityTag/notifications/NotificationsPopover.tsx
  app/scripts/modules/core/src/filterModel/FilterTags.tsx
  app/scripts/modules/core/src/help/HelpField.tsx
  app/scripts/modules/core/src/instance/details/InstanceInsights.tsx
  app/scripts/modules/core/src/loadBalancer/LoadBalancersTag.tsx
  app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
  app/scripts/modules/core/src/managed/ToggleManagedResourceForApplication.tsx
  app/scripts/modules/core/src/managed/artifactDetail/MarkArtifactAsBadModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PinArtifactModal.tsx
  app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
  app/scripts/modules/core/src/managed/artifactDetail/UnpinArtifactModal.tsx
  app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
  app/scripts/modules/core/src/managed/managedResourceStatusConfig.tsx
  app/scripts/modules/core/src/managed/utils/logging.ts
  app/scripts/modules/core/src/pipeline/config/CreatePipeline.tsx
  app/scripts/modules/core/src/pipeline/config/graph/PipelineGraphNode.tsx
  app/scripts/modules/core/src/pipeline/create/CreatePipelineButton.tsx
  app/scripts/modules/core/src/pipeline/details/ExecutionDetailsSectionNav.tsx
  app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
  app/scripts/modules/core/src/pipeline/executionBuild/ExecutionBuildLink.tsx
  app/scripts/modules/core/src/pipeline/executions/Executions.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionBreadcrumbs.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
  app/scripts/modules/core/src/pipeline/executions/execution/ExecutionPermalink.tsx
  app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
  app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
  app/scripts/modules/core/src/presentation/SpinErrorBoundary.tsx
  app/scripts/modules/core/src/reactShims/react.ga.ts
  app/scripts/modules/core/src/search/global/GlobalSearch.tsx
  app/scripts/modules/core/src/search/infrastructure/RecentlyViewedItems.tsx
  app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
  app/scripts/modules/core/src/serverGroup/details/ServerGroupInsightActions.tsx
  app/scripts/modules/core/src/utils/Logger.ts
  app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.spec.tsx
  app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx
  app/scripts/modules/core/src/widgets/tags/TagList.tsx
  app/scripts/modules/kubernetes/src/rawResource/component/group/RawResourceDetails.tsx
Labels: ready to merge

#9253 fix(md): constraint icon size
  app/scripts/modules/core/src/managed/overview/artifact/Constraints.less
Labels: ready to merge, self merge

#9254 feat(md): log MD ui toggling
  app/scripts/modules/core/src/managed/Environments2.tsx
  app/scripts/modules/core/src/managed/utils/defaults.ts
Labels: ready to merge, self merge

#9157 fix(ecs): Cannot see instance details for ecs cluster
  app/scripts/modules/ecs/src/instance/details/instance.details.controller.js
  app/scripts/modules/ecs/src/instance/details/instanceDetails.html
  test/functional/cypress/integration/ecs/clusters_list.spec.js
Labels: ready to merge

#9265 fix(core): Fix imports in core for rollup
  app/scripts/modules/core/src/ci/components/BuildInfoDetails.tsx
  app/scripts/modules/core/src/ci/components/BuildInfoLogsTab.tsx
  app/scripts/modules/core/src/ci/components/BuildInfoSummaryCard.tsx
  app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
  app/scripts/modules/core/src/pipeline/triggers/NextRunTag.tsx
  app/scripts/modules/core/src/presentation/spel/SpelToggle.tsx
  app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx
Labels: self merge
