Repository spinnaker/deck, pull requests merged in 2022-06, with the labels that each got.

#9859 feat(core): Synchronize the verticalNavExpandedAtom using an atom effect
  packages/core/package.json
  packages/core/src/application/nav/navAtoms.ts
  packages/core/src/cache/collapsibleSectionStateCache.ts
Labels: backport-candidate

#9858 fix(Oracle): Fixes Spinnaker configuration issue with Oracle object storage
  packages/appengine/src/pipeline/stages/deployAppengineConfig/DeployAppengineConfigForm.tsx
  packages/cloudfoundry/src/pipeline/stages/bakeCloudFoundryManifest/BakeCloudFoundryManifestConfigForm.tsx
  packages/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsStageConfigForm.tsx
  packages/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
Labels: ready to merge, auto merged

#9861 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
  yarn.lock
Labels: ready to merge, auto merged, publish

#9863 style(core): pipelines adapt to sub pipeline with manual judgment color
  packages/core/src/pipeline/executions/execution/ExecutionMarker.tsx
Labels: ready to merge, auto merged
