Repository spinnaker/deck, pull requests merged in 2022-03, with the labels that each got.

#9812 fix(cf): return credentials in an array
  packages/cloudfoundry/src/pipeline/stages/runJob/cloudFoundryRunJob.module.ts
Labels: ready to merge

#9821 Publish packages to NPM
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
Labels: publish

#9807 fix(scripts): update rollup-plugin-esbuild
  packages/scripts/config/rollup.config.base.js
  packages/scripts/package.json
  yarn.lock
Labels: ready to merge

#9822 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk/CHANGELOG.md
  packages/pluginsdk/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#9826 chore(build): run yarn modules before yarn build
  build.gradle
  version.json
Labels: ready to merge

#9832 chore(build): remove duplication in build steps
  .github/workflows/build.yml
  .github/workflows/package-bump-pr.yml
  .github/workflows/pr.yml
  build.gradle
  version.json
Labels: ready to merge, auto merged
