Repository spinnaker/deck, pull requests merged in 2023-02, with the labels that each got.

#9936 fix(core): Missing config elements after Angular 1.8 update
  packages/core/src/widgets/accountNamespaceClusterSelector.component.js
  packages/core/src/widgets/accountRegionClusterSelector.component.js
Labels: ready to merge, auto merged

#9935 fix(deck): Apache user should own the settings-local.js file, not spi…
  docker/run-apache2.sh
Labels: ready to merge, auto merged

#9904 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, auto merged, publish

#9937 fix(timeout): Added feature flag for rollback timeout ui input.
  halconfig/settings.js
  packages/amazon/src/pipeline/stages/rollbackCluster/awsRollbackClusterStage.js
  packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
  packages/app/src/settings.js
Labels: ready to merge, auto merged

#9938 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: ready to merge, auto merged, publish

#9942 fix(timeout): Added feature flag for rollback timeout ui input.
  packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
Labels: ready to merge

#9943 fix(timeout): Added feature flag for rollback timeout ui input.
  app/scripts/modules/app/src/settings.js
  packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
  yarn.lock
Labels: ready to merge

#9944 fix(timeout): Added feature flag for rollback timeout ui input.
  packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
Labels: ready to merge

#9945 fix(ecs): skip checking for upstream stages for ECS deploy
  packages/ecs/src/ecs.module.ts
Labels: ready to merge, auto merged

#9946 Publish packages to NPM
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
Labels: publish

#9949 Publish packages to NPM
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
Labels: publish
