Repository spinnaker/deck, pull requests merged in 2023-05, with the labels that each got.

#9971 feat(provider/google): Added Cloud Run manifest functionality in Deck.
  packages/cloudrun/src/cloudrun.module.ts
  packages/cloudrun/src/help/cloudrun.help.ts
  packages/cloudrun/src/loadBalancer/configure/wizard/basicSettings.component.html
  packages/cloudrun/src/loadBalancer/configure/wizard/stageAllocationConfigurationRow.component.html
  packages/cloudrun/src/loadBalancer/configure/wizard/stageAllocationConfigurationRow.component.ts
  packages/cloudrun/src/loadBalancer/details/details.html
  packages/cloudrun/src/loadBalancer/loadBalancerTransformer.ts
  packages/cloudrun/src/manifest/ManifestSource.ts
  packages/cloudrun/src/manifest/index.ts
  packages/cloudrun/src/manifest/manifest.service.ts
  packages/cloudrun/src/manifest/manifestCommandBuilder.service.ts
  packages/cloudrun/src/manifest/wizard/BasicSettings.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/DeployStageConfig.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/DeployStageForm.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/ManifestBindArtifactsSelector.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/deploy.validator.ts
  packages/cloudrun/src/pipeline/stages/deployManifest/deployStage.ts
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/DeployStatus.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/DeployStatusPills.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/ManifestDetailsLink.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/ManifestEvents.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/ManifestStatus.less
  packages/cloudrun/src/pipeline/stages/deployManifest/manifestStatus/ManifestStatus.tsx
  packages/cloudrun/src/pipeline/stages/deployManifest/serverGroupNamePreview.tsx
  packages/cloudrun/src/pipeline/stages/editLoadBalancer/cloudrunEditLoadBalancerStage.ts
  packages/cloudrun/src/rolloutStrategy/redblack.strategy.ts
  packages/cloudrun/src/serverGroup/configure/wizard/ConfigFiles.tsx
Labels: ready to merge, auto merged

#9984 Publish packages to NPM
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/cloudrun/CHANGELOG.md
  packages/cloudrun/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
Labels: publish

#9987 update(Rolling Red/Black) remove experimental label
  packages/core/src/deploymentStrategy/strategies/rollingredblack/rollingredblack.strategy.ts
Labels: ready to merge, auto merged

#9989 fix(angular): fix missed AngularJS bindings
  packages/core/src/region/regionSelectField.directive.js
  packages/dcos/src/job/general.component.js
  packages/dcos/src/job/labels.component.js
  packages/dcos/src/job/schedule.component.js
  packages/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.js
  packages/google/src/autoscalingPolicy/components/scalingSchedules/scalingSchedules.component.js
  packages/google/src/loadBalancer/configure/http/backendService/backendService.component.js
  packages/google/src/loadBalancer/configure/http/basicSettings/basicSettings.component.js
  packages/google/src/loadBalancer/configure/http/healthCheck/healthCheck.component.js
  packages/google/src/loadBalancer/configure/http/hostRule/hostRule.component.js
  packages/google/src/loadBalancer/configure/http/listeners/listener.component.js
  packages/google/src/loadBalancer/details/loadBalancerType/loadBalancerType.component.js
Labels: ready to merge, auto merged

#9992 fix(ecs): VPC Subnet dropdown fix in ecs server group creation.
  packages/ecs/src/serverGroup/configure/wizard/networking/Networking.tsx
Labels: auto merged, ready to rebase

#9995 chore(build): fix package bump PR action
  .github/workflows/package-bump-pr.yml
Labels: ready to merge, auto merged

#9993 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/cloudrun/CHANGELOG.md
  packages/cloudrun/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish
