Repository spinnaker/deck, pull requests merged in 2024-05, with the labels that each got.

#10097 fix(lambda): Invoke stage excludedArtifactTypes not including the embedded-artifact type
  packages/amazon/src/pipeline/stages/invokeLambda/components/InvokeLambdaOperation.tsx
Labels: ready to merge, auto merged

#10099 fix(tasksView): Resolving conflicts on yarn.lock backport
  yarn.lock
Labels: ready to merge

#10103 fix(pipeline): Handle render/validation when stageTimeoutMs is a Spel expression
  packages/core/src/pipeline/config/stages/overrideTimeout/OverrideTimeout.tsx
  packages/core/src/pipeline/config/validation/PipelineConfigValidator.ts
Labels: ready to merge, auto merged

#10074 Publish packages to NPM
  packages/amazon/CHANGELOG.md
  packages/amazon/package.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/appengine/CHANGELOG.md
  packages/appengine/package.json
  packages/azure/CHANGELOG.md
  packages/azure/package.json
  packages/cloudfoundry/CHANGELOG.md
  packages/cloudfoundry/package.json
  packages/cloudrun/CHANGELOG.md
  packages/cloudrun/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/dcos/CHANGELOG.md
  packages/dcos/package.json
  packages/docker/CHANGELOG.md
  packages/docker/package.json
  packages/ecs/CHANGELOG.md
  packages/ecs/package.json
  packages/google/CHANGELOG.md
  packages/google/package.json
  packages/huaweicloud/CHANGELOG.md
  packages/huaweicloud/package.json
  packages/kubernetes/CHANGELOG.md
  packages/kubernetes/package.json
  packages/oracle/CHANGELOG.md
  packages/oracle/package.json
  packages/pluginsdk-peerdeps/CHANGELOG.md
  packages/pluginsdk-peerdeps/package.json
  packages/tencentcloud/CHANGELOG.md
  packages/tencentcloud/package.json
  packages/titus/CHANGELOG.md
  packages/titus/package.json
Labels: publish

#10107 fix(redblack): fixing redblack onchange values
  packages/core/src/deploymentStrategy/strategies/redblack/AdditionalFields.tsx
Labels: ready to merge, auto merged
